"use client";
import {useState,useEffect} from "react";
import {Leaf,LockKeyhole,ShieldCheck,CheckCircle2,CalendarDays,Award} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
import {beginnerProgress,weekInfo,type WeekCheck} from "@/lib/beginner";
import {MILESTONES,MILESTONE_NOTE,earnedMilestones} from "@/lib/levels";
import {CHAPTERS,PROGRAMME_WEEKS,STORY_READY_CHAPTERS,chapterForWeek} from "@/lib/curriculum";
import type {RecordEntry} from "@/lib/training";
export default function BeginnerJourney({records,checks,today,loaded,saving,persist}:{records:RecordEntry[];checks:WeekCheck[];today:string;loaded:boolean;saving:boolean;persist:(body:object)=>Promise<boolean>}){
 const progress=beginnerProgress(records,checks,today);const [view,setView]=useState(progress.week);const [goals,setGoals]=useState([false,false,false]);
 useEffect(()=>setView(progress.week),[progress.week]);
 useEffect(()=>setGoals(checks.find(c=>c.week===view)?.goals??[false,false,false]),[checks,view]);
 const current=view===progress.week;const w=weekInfo(view);const remaining=Math.max(0,view*6-progress.sessions);const daysRemaining=Math.max(0,view*7-progress.days);
 const chapter=chapterForWeek(Math.min(view,PROGRAMME_WEEKS));const continuing=view>PROGRAMME_WEEKS;
 const lastWeek=chapter.firstWeek+chapter.weeks-1;const trialWeek=!continuing&&view===lastWeek;
 const earned=earnedMilestones(progress);const chapterEarned=earned.includes(chapter.chapter);
 const unlockedChapters=CHAPTERS.filter(c=>c.chapter<=Math.min(progress.chapter,STORY_READY_CHAPTERS));
 return <Tabs defaultValue="chapter" className="progression"><TabsList className="journey-tabs"><TabsTrigger value="chapter">{continuing?"Continuing practice":`Chapter ${chapter.chapter} · ${chapter.phase}`}</TabsTrigger><TabsTrigger value="milestones">Solo milestones</TabsTrigger></TabsList>
 <TabsContent value="chapter"><div className="program-intro"><div><span className="eyebrow">{continuing?"CONTINUING PRACTICE":`CHAPTER ${chapter.chapter} · ${chapter.milestone.toUpperCase()}`}</span><h2>{continuing?"Practice for life.":chapter.chapter===1?"Eight weeks. A real foundation.":`${chapter.weeks} weeks. ${chapter.phase}.`}</h2><p>{chapter.goal} Weeks advance after six completed practices, seven days, and your check-in. Take longer whenever needed.</p></div><div className="program-badge"><CalendarDays/><strong>Week {continuing?view-PROGRAMME_WEEKS:view-chapter.firstWeek+1}</strong><span>{continuing?"of continuing practice":`of ${chapter.weeks} · your own pace`}</span></div></div>
 {unlockedChapters.length>1&&<div className="chapter-picker" role="group" aria-label="Chapters">{unlockedChapters.map(c=><button key={c.chapter} aria-pressed={chapter.chapter===c.chapter&&!continuing} onClick={()=>setView(c.chapter===progress.chapter?progress.week:c.firstWeek+c.weeks-1)}>Chapter {c.chapter}{earned.includes(c.chapter)&&<CheckCircle2 size={13} aria-label="milestone earned"/>}</button>)}</div>}
 {!continuing&&<div className="week-picker" style={{"--weeks":chapter.weeks} as React.CSSProperties} aria-label={`Chapter ${chapter.chapter} weeks`}>{Array.from({length:chapter.weeks},(_,i)=>{const n=chapter.firstWeek+i;return <button aria-pressed={view===n} aria-label={`Week ${i+1} of chapter ${chapter.chapter}`} className={`${view===n?"active":""} ${n>progress.week?"future":""}`} key={n} onClick={()=>setView(n)}><span>{chapter.chapter===1?(i<4?"MONTH 1":"MONTH 2"):chapter.feels[i].toUpperCase()}</span><strong>Week {i+1}</strong>{n<progress.week?<CheckCircle2 size={14}/>:n>progress.week?<LockKeyhole size={14}/>:<Leaf size={14}/>}</button>})}</div>}
 <section className="panel week-mission"><div className="section-heading"><div><span className="eyebrow">{current?"YOUR CURRENT WEEK":view<progress.week?"COMPLETED WEEK":"FUTURE WEEK · PREVIEW"}</span><h2 className="journey-title">{w.name}</h2><p className="subtext">{w.focus}</p></div><span>{continuing?"Continuing":`Week ${view-chapter.firstWeek+1}`}</span></div>
 {trialWeek&&<div className="trial-checks"><strong><Award size={16}/>Chapter trial · {chapter.trial.title}</strong><ul>{chapter.trial.checks.map(c=><li key={c}>{c}</li>)}</ul><p className="small-note">Saturday's trial session asks you to mark these honestly. A “not yet” is useful: repeat any week without penalty. Results never block story episodes.</p></div>}
 <div className="week-goals">{w.goals.map((g,i)=><label key={g} className="checkbox-line"><Checkbox disabled={!current||!loaded||saving} checked={goals[i]} onCheckedChange={v=>setGoals(goals.map((old,j)=>j===i?v===true:old))}/><span>{g}</span></label>)}</div><div className="week-requirements"><span><CheckCircle2 size={16}/>{remaining===0?"Practice requirement met":`${remaining} more completed practices`}</span><span><CalendarDays size={16}/>{daysRemaining===0?"Calendar requirement met":`${daysRemaining} more days before moving on`}</span></div><p className="small-note">Self-checks describe your own practice. They are honest self-review, not an assessment or proof of fighting ability.</p>{current&&<button className="primary" disabled={!loaded||saving} onClick={()=>void persist({type:"weekcheck",week:view,goals})}>{saving?"Saving…":"Save this week’s check-in"}</button>}
 {chapterEarned&&!continuing&&<div className="success-banner"><CheckCircle2/>{chapter.milestone} milestone recorded. {MILESTONE_NOTE}{chapter.chapter===STORY_READY_CHAPTERS&&chapter.chapter<CHAPTERS.length?" Keep practising freely; the next chapter's training opens together with its story.":""}</div>}</section>
 </TabsContent>
 <TabsContent value="milestones"><div className="roadmap-intro"><span className="eyebrow">TEN SOLO MILESTONES · NO INSTRUCTOR OR PARTNER NEEDED</span><h2>A training arc you can finish alone.</h2><p>Each chapter ends in a milestone, earned by completing its practices and its trial-week self-check. Every one can be reached standing, supported or seated; gentle practice counts the same.</p><div className="tip"><ShieldCheck size={20}/><div><strong>Milestones are records, not ranks.</strong><p>{MILESTONE_NOTE} A chapter's training opens together with its story; later milestones show only their direction until then.</p></div></div></div>
 <div className="level-roadmap">{MILESTONES.map(m=>{const isEarned=earned.includes(m.number),isCurrent=!isEarned&&m.number===progress.chapter&&!progress.continuing,open=m.playable&&m.number<=progress.chapter;return <details key={m.number} className={isCurrent?"current-level":isEarned?"earned-level":""} open={isCurrent}><summary><span className="level-number">{String(m.number).padStart(2,"0")}</span><div><h3>{m.name}</h3><p>{m.phase}</p></div><span className="level-status">{isEarned?"EARNED":isCurrent?"CURRENT":m.playable?"AHEAD":"OPENS WITH ITS STORY"}</span></summary><div className="level-body"><p>{m.focus}</p>{open?<><div className="level-targets"><span>{m.weeks} weeks</span><span>{m.practices} practices</span><span>{m.totalPractices} in total</span></div><p><strong>Trial · {m.trial}</strong></p><ul>{m.checks.map(c=><li key={c}>{c}</li>)}</ul></>:<p className="planned-feature"><LockKeyhole size={15}/>{m.playable?"Opens when you reach this chapter.":`Its training opens together with Chapter ${m.number}'s story.`}</p>}</div></details>;})}</div><p className="roadmap-final">Lifelong is the last milestone, not a master title. After it, continuing practice rotates weeks from every chapter with a lighter week every seventh, for as long as you like.</p></TabsContent></Tabs>;
}
