"use client";
import {useState,useEffect} from "react";
import {Leaf,LockKeyhole,ShieldCheck,CheckCircle2,CalendarDays} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
import {WEEKS,beginnerProgress,type WeekCheck} from "@/lib/beginner";
import {LEVELS} from "@/lib/levels";
import type {RecordEntry} from "@/lib/training";
export default function BeginnerJourney({records,checks,today,loaded,saving,persist}:{records:RecordEntry[];checks:WeekCheck[];today:string;loaded:boolean;saving:boolean;persist:(body:object)=>Promise<boolean>}){
 const progress=beginnerProgress(records,checks,today);const [view,setView]=useState(progress.week);const [goals,setGoals]=useState([false,false,false]);
 useEffect(()=>setView(progress.week),[progress.week]);
 useEffect(()=>setGoals(checks.find(c=>c.week===view)?.goals??[false,false,false]),[checks,view]);
 const current=view===progress.week;const w=WEEKS[view-1];const remaining=Math.max(0,view*6-progress.sessions);const daysRemaining=Math.max(0,view*7-progress.days);
 return <Tabs defaultValue="beginner" className="progression"><TabsList className="journey-tabs"><TabsTrigger value="beginner">First two months</TabsTrigger><TabsTrigger value="roadmap">Ten-level roadmap</TabsTrigger></TabsList>
 <TabsContent value="beginner"><div className="program-intro"><div><span className="eyebrow">LEVEL 1 · BEGINNER</span><h2>Eight weeks. A real foundation.</h2><p>Build comfortable movement before punches and kicks. Weeks advance after six completed practices, seven days, and your movement check-in. Take longer whenever needed.</p></div><div className="program-badge"><CalendarDays/><strong>Week {progress.week}</strong><span>of 8 · your own pace</span></div></div>
 <div className="week-picker" aria-label="Beginner program weeks">{WEEKS.map((_,i)=>{const n=i+1;return <button aria-pressed={view===n} className={`${view===n?"active":""} ${n>progress.week?"future":""}`} key={n} onClick={()=>setView(n)}><span>{n<=4?"MONTH 1":"MONTH 2"}</span><strong>Week {n}</strong>{n<progress.week?<CheckCircle2 size={14}/>:n>progress.week?<LockKeyhole size={14}/>:<Leaf size={14}/>}</button>})}</div>
 <section className="panel week-mission"><div className="section-heading"><div><span className="eyebrow">{current?"YOUR CURRENT WEEK":view<progress.week?"COMPLETED WEEK":"FUTURE WEEK · PREVIEW"}</span><h2 className="journey-title">{w.name}</h2><p className="subtext">{w.focus}</p></div><span>Week {view}</span></div><div className="week-goals">{w.goals.map((g,i)=><label key={g} className="checkbox-line"><Checkbox disabled={!current||!loaded||saving} checked={goals[i]} onCheckedChange={v=>setGoals(goals.map((old,j)=>j===i?v===true:old))}/><span>{g}</span></label>)}</div><div className="week-requirements"><span><ClockLabel/>{remaining===0?"Practice requirement met":`${remaining} more completed practices`}</span><span><CalendarDays size={16}/>{daysRemaining===0?"Calendar requirement met":`${daysRemaining} more days before moving on`}</span></div><p className="small-note">Self-checks describe your experience. They are not an instructor assessment or proof of fighting ability.</p>{current&&<button className="primary" disabled={!loaded||saving} onClick={()=>void persist({type:"weekcheck",week:view,goals})}>{saving?"Saving…":"Save this week’s check-in"}</button>}{progress.complete&&<div className="success-banner"><CheckCircle2/>Eight-week foundation complete. Keep practicing and arrange an instructor review before progressing.</div>}</section>
 </TabsContent>
 <TabsContent value="roadmap"><div className="roadmap-intro"><span className="eyebrow">PLANNED CURRICULUM · LEVELS 2–10 ARE NOT ENABLED</span><h2>Skill has to survive the real dojo.</h2><p>Your goal is strong punches, controlled kicks, and fluid movement. This roadmap builds toward that through years of practice and external assessment. Logging time alone will never award an advanced level.</p><div className="tip"><ShieldCheck size={20}/><div><strong>Standards must be set with your instructor.</strong><p>The practice and time targets below are proposed app milestones, not recognized belts or universal martial arts standards. Later levels require actual instructor assessment and supervised partner practice. The app cannot verify form or guarantee combat performance.</p></div></div></div>
 <div className="level-roadmap">{LEVELS.map(l=><details key={l.number} className={l.number===1?"current-level":""} open={l.number===1}><summary><span className="level-number">{String(l.number).padStart(2,"0")}</span><div><h3>{l.name}</h3><p>{l.focus}</p></div><span className="level-status">{l.number===1?"ACTIVE":"PLANNED"}</span></summary><div className="level-body">{l.number===1?<p>The current app supports this level: your eight-week foundation, 30–45 minute practices, weekly self-checks, mobility tracking, and journal.</p>:<><div className="level-targets"><span>{l.sessions.toLocaleString()} completed practices</span><span>{Math.round(l.minutes/60)} hours total</span><span>{Math.round(l.days/7)} weeks minimum</span>{l.coachedMinutes>0&&<span>{l.coachedMinutes/60} instructor-led hours</span>}</div><ul>{l.tests.map(t=><li key={t}>{t}</li>)}</ul><p className="planned-feature"><LockKeyhole size={15}/>{l.number===2?"Future feature: foundation review and a progression gate before Level 2.":l.number===10?"Future feature: independent assessments from two qualified instructors, with performance tracked across six months.":"Future feature: instructor assessment records, coached-session tracking, and skill-gated drills."}</p></>}</div></details>)}</div><p className="roadmap-final">Level 10 is planned as advanced practitioner, not an app-created “master” title. It requires sustained advanced performance in a named real martial art, including punching, kicking, defense, distance, and movement.</p></TabsContent></Tabs>;
}
function ClockLabel(){return <CheckCircle2 size={16}/>;}
