"use client";
import {useState,useEffect} from "react";
import {BookOpen,Play,Leaf,Hammer,Package,Clock3,Check,Users,Lock,Archive} from "lucide-react";
import {DOJO_MEMBERS,type DojoMemberId} from "@/lib/dojo-members";
import {PROJECTS,JOBS,availableScenes,bondLabel,claimable,mainCompleted,earnedEpisodes} from "@/lib/game";
import {MAIN,EPISODE_TITLES,SCENE_BY_ID} from "@/lib/story";
import {activeSession} from "@/lib/session-actions";
import {hallImage} from "@/lib/story/cast";
import type {DojoGameApi} from "./use-dojo-game";
import {StoryReader} from "./story-reader";
export default function DojoHub({api,companion,setCompanion,onPractice,isRest,isDone,onResume}:{api:DojoGameApi;companion:DojoMemberId;setCompanion:(id:DojoMemberId)=>void;onPractice:()=>void;onResume:()=>void;isRest:boolean;isDone:boolean}){
 const [scene,setScene]=useState<string|null>(null),[section,setSection]=useState<"visits"|"projects"|"archive">("visits"),[jobMember,setJobMember]=useState<DojoMemberId>("akari"),[jobHours,setJobHours]=useState<12|24>(12),[job,setJob]=useState("stock"),[,tick]=useState(0);
 useEffect(()=>{const t=setInterval(()=>tick(n=>n+1),30000);return()=>clearInterval(t);},[]);
 const g=api.game;if(!g)return <section className="panel"><h2>Opening Lantern Hall…</h2>{api.error&&<><p role="alert">{api.error}</p><button className="secondary" onClick={()=>void api.load()}>Retry</button></>}</section>;
 const available=availableScenes(g),primary=available.find(s=>s.kind==="prologue"||s.kind==="main"),visits=available.filter(s=>s.kind!=="prologue"&&s.kind!=="main");const count=mainCompleted(g),episode=Math.min(8,Math.floor(count/6)+1);const active=activeSession(g);
 return <div className="dojo-game"><section className="hall-stage"><img className="hall-background" src={hallImage(count,g.facilities.includes("floor"))} alt={count===48?"Lantern Hall after the season\'s repairs":count>=12||g.facilities.includes("floor")?"Lantern Hall with repairs under way":"Lantern Hall, a worn timber dojo with warm daylight"}/><div className="hall-gradient"/><div className="hall-content"><span className="eyebrow">CHAPTER 1 · BEGINNER</span><h2>Lantern Hall</h2><p>{count===48?"The door stays open. Your next chapter will need new training and new stories.":EPISODE_TITLES[episode-1]}</p><div className="hall-actions">{primary?<button className="primary" onClick={()=>setScene(primary.id)}><BookOpen/>{g.scenes[primary.id]?"Continue":"Read"} {primary.kind==="prologue"?"the opening":"next scene"}</button>:<span className="hall-wait">{count===48?"Starter season complete":isRest?"Wednesday is yours to rest.":"Your next completed practice opens the next scene."}</span>}{active?<button className="secondary" onClick={onResume}><Play/>Resume saved practice</button>:<button className="secondary" onClick={onPractice}><Leaf/>{isRest?"Full rest day":isDone?"Review today's practice":"Today's 30–45 min practice"}</button>}</div><div className="story-meter"><span>{count} / 48 scenes read</span><span>{Math.max(0,Math.min(48,g.practices)-count)} waiting</span></div><div className="story-track">{Array.from({length:8},(_,i)=><span key={i} className={count>=(i+1)*6?"complete":i===episode-1?"current":""} title={`Episode ${i+1}${count>=(i+1)*6?" complete":""}`}/>)}</div></div><img className="hall-companion" src={DOJO_MEMBERS.find(m=>m.id===companion)?.portrait} alt={`${DOJO_MEMBERS.find(m=>m.id===companion)?.name}, selected practice companion`}/></section>
 <section className="companion-picker"><div><h3>Practice companion</h3><p>Choose who joins your next practice. A saved session keeps its companion.</p></div><div className="companion-options">{DOJO_MEMBERS.map(m=><button key={m.id} aria-pressed={m.id===companion} onClick={()=>setCompanion(m.id)} style={{"--member-accent":m.accent} as React.CSSProperties}><img src={m.portrait} alt=""/><span>{m.name}<small>{bondLabel(g,m.id)}</small></span></button>)}</div></section>
 <div className="game-toolbar"><div className="game-sections" role="group" aria-label="Dojo activities"><button aria-pressed={section==="visits"} onClick={()=>setSection("visits")}><Users/>Visits{visits.length>0&&<b>{visits.length}</b>}</button><button aria-pressed={section==="projects"} onClick={()=>setSection("projects")}><Hammer/>Projects</button><button aria-pressed={section==="archive"} onClick={()=>setSection("archive")}><Archive/>Story archive</button></div><span className="supply-count"><Package/>{g.supplies} supplies</span></div>
 {api.error&&<div className="game-error" role="alert">{api.error}<button className="text-button" onClick={()=>void api.load()}>Reload dojo</button></div>}
 {section==="visits"&&<div className="visits-grid">{visits.length?visits.map(s=><button className="visit-card" key={s.id} onClick={()=>setScene(s.id)}>{s.member&&<img src={DOJO_MEMBERS.find(m=>m.id===s.member)?.portrait??`/story/characters/${s.member}-neutral.webp`} alt=""/>}<span><small>{s.kind==="personal"?"A PERSONAL CONVERSATION":s.kind==="relationship"?"AN INVITATION":"AROUND THE HALL"}</small><strong>{s.title}</strong><span>{s.member?.[0].toUpperCase()}{s.member?.slice(1)}</span></span><BookOpen size={18}/></button>):<div className="panel quiet-visits"><h3>No new visits waiting</h3><p>Conversations open as you practise together and the season moves forward. You can rest, read an unlocked scene, or leave the hall for today.</p></div>}</div>}
 {section==="projects"&&<><div className="project-intro"><h3>Make room for more</h3><p>Completed practice adds 20 supplies. Normal and gentle recovery count equally. Build optional facilities and open new companion jobs as the hall grows.</p></div><div className="projects-grid">{PROJECTS.map(p=>{const owned=g.facilities.includes(p.id),unlocked=earnedEpisodes(g)>=p.episode;return <article className="project-card" key={p.id}><span className="project-icon">{owned?<Check/>:unlocked?<Hammer/>:<Lock/>}</span><h3>{p.name}</h3><p>{p.description}</p><button className={owned?"secondary":"primary"} disabled={owned||!unlocked||g.supplies<p.cost||api.saving} onClick={()=>void api.act({action:"upgrade",id:p.id})}>{owned?"Ready":!unlocked?`After Episode ${p.episode}`:`Build · ${p.cost} supplies`}</button></article>;})}</div>
 <section className="panel assignments"><div className="section-heading"><h3>Companions' jobs</h3><span>{g.assignments.length} / {earnedEpisodes(g)>=3?2:1} slots</span></div><p>They continue between visits. Collect when convenient; up to 48 hours of finished work is kept. Jobs earn supplies, not affection or training skill.</p>{g.assignments.map(a=><div className="assignment-row" key={a.id}><div><strong>{DOJO_MEMBERS.find(m=>m.id===a.member)?.name} · {JOBS.find(j=>j.id===(a.job??"stock"))?.name}</strong><span><Clock3 size={15}/>{a.hours}h cycles · {claimable(a,api.now())} supplies ready</span></div><button className="secondary" disabled={api.saving||claimable(a,api.now())===0} onClick={()=>void api.act({action:"claim",id:a.id})}>Collect</button><button className="text-button" disabled={api.saving} onClick={()=>void api.act({action:"release",id:a.id})}>Collect & finish job</button></div>)}{earnedEpisodes(g)<1?<p className="small-note">Jobs open after Episode 1. The second slot opens after Episode 3.</p>:g.assignments.length<(earnedEpisodes(g)>=3?2:1)&&<div className="assignment-form"><label>Companion<select value={jobMember} onChange={e=>setJobMember(e.target.value as DojoMemberId)}>{DOJO_MEMBERS.filter(m=>!g.assignments.some(a=>a.member===m.id)).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Work<select value={job} onChange={e=>setJob(e.target.value)}>{JOBS.filter(j=>!j.requires||g.facilities.includes(j.requires)).map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><label>Cycle<select value={jobHours} onChange={e=>setJobHours(Number(e.target.value) as 12|24)}><option value={12}>12 hours · 8 supplies</option><option value={24}>24 hours · 16 supplies</option></select></label><button className="primary" disabled={api.saving} onClick={()=>void api.act({action:"assign",member:DOJO_MEMBERS.some(m=>m.id===jobMember&&!g.assignments.some(a=>a.member===m.id))?jobMember:DOJO_MEMBERS.find(m=>!g.assignments.some(a=>a.member===m.id))!.id,hours:jobHours,job})}>Begin job</button></div>}</section></>}
 {section==="archive"&&<section className="panel story-archive"><h3>Your story so far</h3><p>Replays keep your original choices and award no extra supplies or bond.</p>{Object.entries(g.scenes).filter(([,s])=>s.done).map(([id,s])=><button key={id} onClick={()=>setScene(id)}><BookOpen size={17}/><span>{SCENE_BY_ID[id]?.title}{s.choice&&<small>{SCENE_BY_ID[id]?.choice?.options.find(o=>o.id===s.choice)?.label}</small>}</span><span>Replay</span></button>)}{!Object.values(g.scenes).some(s=>s.done)&&<p>The opening scene is ready above.</p>}</section>}
 <p className="game-footnote">Visits and projects are optional. Taking time away never removes trust or supplies. Training level remains separate from the story.</p>
 <StoryReader sceneId={scene} api={api} onClose={()=>setScene(null)}/>
 </div>;
}
