"use client";
import {useState,useEffect} from "react";
import {BookOpen,Play,Leaf,Hammer,Package,Clock3,Check,Users,Lock,Archive} from "lucide-react";
import {DOJO_MEMBERS,type DojoMemberId} from "@/lib/dojo-members";
import {PROJECTS,JOBS,availableScenes,bondLabel,claimable,mainCompleted,campaignMain,earnedEpisodes,companionsUnlocked,requiredOpening,type PracticeCompanion} from "@/lib/game";
import {EPISODE_TITLES,SCENE_BY_ID} from "@/lib/story";
import {activeSession} from "@/lib/session-actions";
import {hallImage} from "@/lib/story/cast";
import type {DojoGameApi} from "./use-dojo-game";
import {StoryReader} from "./story-reader";
export default function DojoHub({api,companion,setCompanion,onPractice,isRest,isDone,onResume,today,onReset}:{today:string;api:DojoGameApi;companion:PracticeCompanion;setCompanion:(id:PracticeCompanion)=>void;onReset:()=>void;onPractice:()=>void;onResume:()=>void;isRest:boolean;isDone:boolean}){
 const resetToken=useState(()=>crypto.randomUUID())[0];
 const [scene,setScene]=useState<string|null>(null),[section,setSection]=useState<"visits"|"projects"|"archive">("visits"),[jobMember,setJobMember]=useState<DojoMemberId>("akari"),[jobHours,setJobHours]=useState<12|24>(12),[job,setJob]=useState("stock"),[,tick]=useState(0);
 useEffect(()=>{const t=setInterval(()=>tick(n=>n+1),30000);return()=>clearInterval(t);},[]);
 const g=api.game;if(!g)return <section className="hall-loading" aria-live="polite"><Leaf size={30}/><h2>Opening Lantern Hall…</h2>{api.error&&<><p role="alert">{api.error}</p><button className="secondary" onClick={()=>void api.load()}>Retry</button></>}</section>;
 const available=availableScenes(g),primary=available.find(s=>s.kind==="prologue")??available.find(s=>s.id===requiredOpening(g)?.id)??available.find(s=>s.kind==="main"),visits=available.filter(s=>!["prologue","main","opening"].includes(s.kind));const count=mainCompleted(g),episode=Math.min(8,Math.floor(count/6)+1);const active=activeSession(g),nextEpisode=campaignMain(g)[count];
 const unlocked=companionsUnlocked(g),host=unlocked.find(m=>m.id===companion),opening=available.find(s=>s.kind==="opening");
 const date=today?new Date(`${today}T12:00:00Z`):null;
 return <div className="dojo-game">{!g.storyRevision&&<section className="panel pilot-start"><h2>A new first month</h2><p>Twenty-four visual novel episodes, story openings before selected workouts, and companions you meet along the way. Begin with a fresh save: this replaces your story, hall, and workout history.</p><button className="primary" disabled={api.saving} onClick={async()=>{if(await api.act({action:"reset-pilot",token:resetToken})){setScene(null);setCompanion("solo");onReset();}}}>Begin the first-month story</button></section>}<div className="hall-arrival"><section className="hall-stage" aria-labelledby="hall-title">
 <img className="hall-background" src={hallImage(count,g.facilities.includes("floor"))} alt={count>=33?"Lantern Hall after its repairs":count>=12||g.facilities.includes("floor")?"Lantern Hall with repairs under way":"Lantern Hall, a worn timber dojo with warm daylight"}/><div className="hall-gradient"/><div className="hall-atmosphere" aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i} style={{"--mote":i} as React.CSSProperties}/>)}</div>
 <div className="hall-location"><span className="eyebrow"><span/> AMAHARA · YOUR TRAINING GROUND</span><h1 id="hall-title">Lantern Hall<span>.</span></h1><p>A place on the mats. A practice of your own.</p></div>
 <time className="hall-calendar" dateTime={today||undefined}><span>{date?.toLocaleDateString("en-US",{month:"short",timeZone:"UTC"})??"TODAY"}</span><strong>{date?.getUTCDate()??"—"}</strong><small>{date?.toLocaleDateString("en-US",{weekday:"long",timeZone:"UTC"})??""}</small></time>
 <div className="hall-content"><div className="chapter-label"><span>CHAPTER 01</span><span>{count===48?"SEASON COMPLETE":nextEpisode?.revision?`WEEK ${nextEpisode.episode} · EPISODE ${nextEpisode.beat} / 6`:`STORY WEEK ${String(episode).padStart(2,"0")} / 08`}</span></div><h2>{count===48?"The door stays open.":nextEpisode?.revision?nextEpisode.title:EPISODE_TITLES[episode-1]}</h2><p>{count===48?"Keep your practice close. New training and new stories will meet you here.":primary?.kind==="prologue"?"An open door. Five unfamiliar faces. Your story at Lantern Hall begins here.":primary?"There’s another moment waiting for you at the hall.":isRest?"Let the hall be quiet today. Wednesday is yours to rest.":"Take your place on the mats. Your next completed practice opens the next story installment."}</p>
 <div className="hall-actions">{primary&&<button className="primary" onClick={()=>setScene(primary.id)}><BookOpen/>{g.scenes[primary.id]?"Continue story":primary.kind==="prologue"?"Begin your story":primary.kind==="opening"?`Read opening · ${primary.readingMinutes??"3–5"} min`:primary.readingMinutes?`Start episode · ${primary.readingMinutes} min`:"Read next scene"}</button>}{active?<button className={primary?"secondary":"primary"} onClick={onResume}><Play/>Resume practice</button>:<button className={primary?"secondary":"primary"} onClick={onPractice}><Leaf/>{isRest?"Full rest day":isDone?"Review practice":"Today’s practice"}</button>}</div>
 {opening&&!isRest&&<div className="optional-opening"><span>Before practice</span><button className="text-button" onClick={()=>setScene(opening.id)}>{g.scenes[opening.id]?"Continue":"Read"} {opening.title} · {opening.readingMinutes??"3–5"} min</button><span>Read this opening before the next practice.</span></div>}<div className="story-progress"><div className="story-meter"><span>YOUR CHAPTER</span><strong>{String(count).padStart(2,"0")} <span>/ 48 scenes</span></strong></div><div className="story-track" role="progressbar" aria-label="Chapter 1 story progress" aria-valuemin={0} aria-valuemax={48} aria-valuenow={count}>{Array.from({length:8},(_,i)=><span key={i} className={count>=(i+1)*6?"complete":i===episode-1?"current":""}><i style={{width:`${Math.max(0,Math.min(1,(count-i*6)/6))*100}%`}}/></span>)}</div></div></div>
 {host?<div className="hall-character" key={host.id}><img className="hall-companion" src={host.portrait} alt={`${host.name}, your selected practice companion`}/><div className="companion-nameplate"><span>PRACTICE COMPANION</span><strong>{host.name}</strong><p>“{host.introduction}”</p></div></div>:<div className="hall-solo"><Leaf size={32}/><strong>Your own beginning</strong><p>Solo practice is ready. Meet the founders through the story to practise together.</p></div>}
 </section>
 <section className="companion-picker" aria-labelledby="companion-title"><div className="companion-heading"><h3 id="companion-title">Choose your companion</h3><p>A saved practice keeps its companion.</p><span>FIVE FOUNDERS · ONE HALL</span></div><div className="companion-options"><button aria-pressed={companion==="solo"} onClick={()=>setCompanion("solo")} className="solo-companion"><Leaf/><span className="companion-card-copy"><strong>Solo practice</strong><small>Your own pace</small></span></button>{unlocked.map((m,i)=><button key={m.id} aria-label={`Practise with ${m.name}: ${bondLabel(g,m.id)}`} aria-pressed={m.id===companion} onClick={()=>setCompanion(m.id)} style={{"--member-accent":m.accent} as React.CSSProperties}><span className="companion-number" aria-hidden="true">0{i+1}</span><img src={m.portrait} alt=""/><span className="companion-card-copy"><strong>{m.name}</strong><small>{bondLabel(g,m.id)}</small></span><span className="companion-selected" aria-hidden="true">{m.id===companion?<Check size={13}/>:<span/>}</span></button>)}{unlocked.length<5&&<div className="companion-locked"><Lock/><span>{5-unlocked.length} companions to meet in the story</span></div>}</div></section></div>
 <div className="hall-details">
 <div className="game-toolbar"><div className="game-sections" role="group" aria-label="Dojo activities"><button aria-pressed={section==="visits"} onClick={()=>setSection("visits")}><Users/>Visits{visits.length>0&&<b>{visits.length}</b>}</button><button aria-pressed={section==="projects"} onClick={()=>setSection("projects")}><Hammer/>Projects</button><button aria-pressed={section==="archive"} onClick={()=>setSection("archive")}><Archive/>Story archive</button></div><span className="supply-count"><Package/>{g.supplies} supplies</span></div>
 {api.error&&<div className="game-error" role="alert">{api.error}<button className="text-button" onClick={()=>void api.load()}>Reload dojo</button></div>}
 {section==="visits"&&<div className="visits-grid">{visits.length?visits.map(s=><button className="visit-card" key={s.id} onClick={()=>setScene(s.id)}>{s.member&&<img src={DOJO_MEMBERS.find(m=>m.id===s.member)?.portrait??`/story/characters/${s.member}-neutral.webp`} alt=""/>}<span><small>{s.kind==="personal"?"A PERSONAL CONVERSATION":s.kind==="relationship"?"AN INVITATION":"AROUND THE HALL"}</small><strong>{s.title}</strong><span>{s.member?.[0].toUpperCase()}{s.member?.slice(1)}</span></span><BookOpen size={18}/></button>):<div className="panel quiet-visits"><h3>No new visits waiting</h3><p>Conversations open as you practise together and the season moves forward. You can rest, read an unlocked scene, or leave the hall for today.</p></div>}</div>}
 {section==="projects"&&<><div className="project-intro"><h3>Make room for more</h3><p>Completed practice adds 20 supplies. Normal and gentle recovery count equally. Build optional facilities and open new companion jobs as the hall grows.</p></div><div className="projects-grid">{PROJECTS.map(p=>{const owned=g.facilities.includes(p.id),unlocked=earnedEpisodes(g)>=p.episode;return <article className="project-card" key={p.id}><span className="project-icon">{owned?<Check/>:unlocked?<Hammer/>:<Lock/>}</span><h3>{p.name}</h3><p>{p.description}</p><button className={owned?"secondary":"primary"} disabled={owned||!unlocked||g.supplies<p.cost||api.saving} onClick={()=>void api.act({action:"upgrade",id:p.id})}>{owned?"Ready":!unlocked?`After story week ${p.episode}`:`Build · ${p.cost} supplies`}</button></article>;})}</div>
 <section className="panel assignments"><div className="section-heading"><h3>Companions' jobs</h3><span>{g.assignments.length} / {earnedEpisodes(g)>=3?2:1} slots</span></div><p>They continue between visits. Collect when convenient; up to 48 hours of finished work is kept. Jobs earn supplies, not affection or training skill.</p>{g.assignments.map(a=><div className="assignment-row" key={a.id}><div><strong>{DOJO_MEMBERS.find(m=>m.id===a.member)?.name} · {JOBS.find(j=>j.id===(a.job??"stock"))?.name}</strong><span><Clock3 size={15}/>{a.hours}h cycles · {claimable(a,api.now())} supplies ready</span></div><button className="secondary" disabled={api.saving||claimable(a,api.now())===0} onClick={()=>void api.act({action:"claim",id:a.id})}>Collect</button><button className="text-button" disabled={api.saving} onClick={()=>void api.act({action:"release",id:a.id})}>Collect & finish job</button></div>)}{earnedEpisodes(g)<1?<p className="small-note">Jobs open after story week 1. The second slot opens after story week 3.</p>:g.assignments.length<(earnedEpisodes(g)>=3?2:1)&&<div className="assignment-form"><label>Companion<select value={jobMember} onChange={e=>setJobMember(e.target.value as DojoMemberId)}>{unlocked.filter(m=>!g.assignments.some(a=>a.member===m.id)).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Work<select value={job} onChange={e=>setJob(e.target.value)}>{JOBS.filter(j=>!j.requires||g.facilities.includes(j.requires)).map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><label>Cycle<select value={jobHours} onChange={e=>setJobHours(Number(e.target.value) as 12|24)}><option value={12}>12 hours · 8 supplies</option><option value={24}>24 hours · 16 supplies</option></select></label><button className="primary" disabled={api.saving} onClick={()=>void api.act({action:"assign",member:unlocked.some(m=>m.id===jobMember&&!g.assignments.some(a=>a.member===m.id))?jobMember:unlocked.find(m=>!g.assignments.some(a=>a.member===m.id))!.id,hours:jobHours,job})}>Begin job</button></div>}</section></>}
 {section==="archive"&&<section className="panel story-archive"><h3>Your story so far</h3><p>Replays keep your original choices and award no extra supplies or bond.</p>{Object.entries(g.scenes).filter(([,s])=>s.done).map(([id,s])=><button key={id} onClick={()=>setScene(id)}><BookOpen size={17}/><span>{SCENE_BY_ID[id]?.title}{s.choice&&<small>{SCENE_BY_ID[id]?.choice?.options.find(o=>o.id===s.choice)?.label}</small>}</span><span>Replay</span></button>)}{!Object.values(g.scenes).some(s=>s.done)&&<p>The opening scene is ready above.</p>}</section>}
 <p className="game-footnote">Visits and projects are optional. Taking time away never removes trust or supplies. Training level remains separate from the story.</p>
 </div>
 <StoryReader sceneId={scene} api={api} onClose={()=>setScene(null)}/>
 </div>;
}
