import {makeDrills,type ChapterSpec} from "./build";

// Chapter 4 · Kicks and balance. Low kicks only (at or below hip height), a stable chamber,
// support always available, both legs. The low lines are the ones that work in real life.
const drills = makeDrills(4,{
 "c4-warm":{name:"Hips, knees and ankles",family:"Preparation",timing:"warmup",cue:"Loose hips, quiet ankles. The kicks will thank you.",
  steps:["First 30 seconds: clear your space and stand the chair beside you so a hand can rest on its back. Every kick this chapter has support within reach. Find your point across the room.","Next 2 minutes: march in place, gradually letting the knees rise a little higher within comfort. Then ankle circles, each foot, holding the chair.","Next 90 seconds: holding the chair, small front-to-back leg swings (about 10 per leg, knee soft, well below hip height), 8 small side swings per leg, 6 slow calf raises and easy hip circles.","Final minute: feet together, eyes on your point, a small bow. Step into stance, raise your guard with one sharp breath out and hold one breath of stillness. Practice begins."],
  checks:["My hips and ankles feel warm and loose.","Every swing stayed small, controlled and below hip height."],
  supported:"Keep both hands on the chair for every swing and make them smaller.",
  seated:"Seated marches, ankle circles and gentle knee lifts, then a seated bow and guard.",
  avoid:"No ballistic high swings, no bouncing stretches. Stop with hip, knee or ankle pain.",sources:["aaos","nhs-balance"]},
 "c4-cool":{name:"Release the hips",family:"Finish",timing:"cooldown",cue:"Kicks borrow from the hips. Give it back.",
  steps:["First 2 minutes: lower your hands and walk slowly; let the legs feel heavy and easy.","Next 2 minutes: holding the chair, a gentle standing hip-flexor stretch in a split stance with the pelvis tucked (20 seconds each side), a calf stretch against the wall and an easy side lean for the inner thighs.","Final minute: breathe in for 4 counts and out for 6. Name one kick that returned cleanly and one to repeat.","Feet together, a small bow. Practice ends. If a hip or knee complains tomorrow, choose the gentle option or rest."],
  checks:["My breathing settled before I finished.","Every stretch stayed at mild tension."],
  supported:"Use the chair for every stretch.",
  seated:"Seated figure-four stretch within comfort, seated calf stretch with the leg out straight, breathing and a seated bow.",
  avoid:"No forced splits or bouncing. Stop with sharp pain, tingling or numbness.",sources:["nhs-flex"]},
 "c4-balance":{name:"Supported single-leg balance",family:"Balance",format:"H",hold:20,cue:"Grow tall on one leg. The chair is a friend, not a failure.",
  steps:["Stand side-on to the chair with one hand resting on its back. Soften the standing knee and shift your weight onto that leg.","Lift the other foot just off the floor and hold, tall and still, eyes on your point. Fingertip support is fine; use more whenever you need it.","Each hold lasts about 20 seconds, then set the foot down and rest. Hold 1 on one leg, hold 2 on the other, hold 3 on the leg that wobbled more.","Progress only when steady: lighter fingertips first, then the knee lifted a little toward chamber height."],
  checks:["My standing knee stays soft and my hips stay level.","I keep a hand near the chair and step down early when I wobble."],
  supported:"Both hands on the chair back, the lifted foot only just off the floor or resting on its toes.",
  seated:"Sit tall and lift one foot a few centimetres off the floor, hold, then switch. This builds hip control without standing balance.",
  avoid:"No eyes-closed or wobble-board holds, no hopping to recover. Step down whenever balance goes.",sources:["nhs-balance","balance-training"]},
 "c4-chamber":{name:"Knee raise to chamber",family:"Kicks",cue:"The chamber is the loaded spring.",
  steps:["Stand side-on to the chair with one hand on it, stance and a guard with the free hand. Lift the lead knee up in front of you toward hip height or lower, the foot relaxed under the knee.","Hold the chamber for two counts: standing knee soft, back tall, hips level, eyes on your point.","Set the foot down exactly where it came from, back in stance. Breathe out as the knee rises.","5 chambers per round: round 1 lead leg, round 2 rear leg (it travels further), round 3 the weaker leg. Turn around to keep the chair on your free-hand side."],
  checks:["I hold the chamber for two counts with a soft standing knee.","The foot sets down in my stance, not in a new place."],
  supported:"Both hands on the chair and a lower knee lift.",
  seated:"Sit tall and lift one knee a few centimetres, hold two counts, lower; alternate.",
  avoid:"No kicking yet, no forcing the knee above hip height, no leaning back to lift it.",sources:["kicks","nhs-balance"]},
 "c4-knee":{name:"Knee strike in the air",family:"Kicks",cue:"Hands pull down. Hips drive in. The knee rises.",
  steps:["From stance with a hand on the chair, reach the free hand forward at chest height as if holding an imagined opponent's shoulder.","Drive the rear knee up and forward toward your point, at hip height or lower, as the reaching hand pulls down to your hip. Push the hips forward slightly. Breathe out.","Set the foot back down in stance and bring the guard home.","4–5 knees per round. Round 2 with the other leg (turn so the chair is on your free side). Round 3 the weaker side."],
  checks:["The knee rises no higher than my hip and my back stays tall.","I set the foot down in stance without hopping."],
  supported:"Both hands on the chair and a smaller knee lift without the reaching hand.",
  seated:"Sit tall at the front of the chair and lift each knee briskly a few centimetres while the hands pull down.",
  avoid:"No jumping knees, no hitting objects, no leaning back.",sources:["kicks"]},
 "c4-teep":{name:"Low front push kick",family:"Kicks",cue:"Push the door shut with your heel.",
  steps:["Hand on the chair, stance and guard. Chamber the lead knee and hold for two counts.","Extend the foot forward from the chamber, pushing through the heel to an imagined thigh, no higher than your own hip. The hip pushes slightly forward; the standing knee stays soft. Breathe out.","Stop just short of a straight knee, re-chamber, then set the foot down in stance. Four parts: chamber, extend, re-chamber, set down.","4–5 kicks per round: round 1 lead leg, round 2 rear leg, round 3 the weaker leg."],
  checks:["Every kick goes chamber, extend, re-chamber, set down.","The kick stays at or below hip height with a soft standing knee."],
  supported:"Both hands on the chair, a lower chamber and a shorter extension.",
  seated:"Sit at the front of the chair, lift the knee and press the heel forward slowly, then return.",
  avoid:"No snapping the knee straight, no kicks above the hip, no hopping, no kicking objects or furniture.",sources:["kicks","jkd"]},
 "c4-round":{name:"Low round kick",family:"Kicks",cue:"Turn the standing heel. The shin swings like a gate.",
  steps:["Hand on the chair on your lead side, stance. Lift the rear knee toward chamber, slightly out to the side.","Turn on the ball of the standing foot so its heel points toward your point and let the hip turn over. The shin swings in a low arc to an imagined thigh, no higher than your own hip.","Bring the leg back along the same path to chamber, then set it down in stance and turn the standing foot back. Breathe out on the kick.","Slowly, 4 per round: round 1 rear leg, round 2 lead leg with a smaller swing, round 3 the weaker leg."],
  checks:["The standing heel turns so the hip can turn.","The kick returns along the same path to chamber, then stance."],
  supported:"Both hands on the chair back and a slow swing at knee height.",
  seated:"Sit sideways near the front of the chair and swing the lower leg slowly in a small arc and back.",
  avoid:"No spinning through, no high kicks, no twisting on a planted heel, no kicking furniture.",sources:["kicks"]},
 "c4-side":{name:"Low side step-kick",family:"Kicks",cue:"Step, chamber, press low. The stop sign.",
  steps:["Stand with the chair beside your rear hand. Step the rear foot a short way up behind the lead foot, stopping behind the front heel. The feet never cross.","Chamber the lead knee across your body with the sole of the foot facing your point.","Press the heel out sideways to an imagined knee or shin, well below hip height, leaning the body slightly away. Re-chamber and set the foot down in your stance.","4 per round on the lead leg; round 2 on the other lead; round 3 the weaker side. This is the low stop-kick of Jeet Kune Do: short, direct, aimed at the knee line."],
  checks:["The rear foot steps up behind without crossing the front foot.","The heel presses out low and re-chambers before setting down."],
  supported:"Skip the step: hand on the chair, chamber and press the heel out sideways at shin height.",
  seated:"Sit sideways, lift the knee and press the heel out to the side at low height, then return.",
  avoid:"No jumping step-ins, no kicks above the hip, no locking the knee, no kicking objects.",sources:["jkd","kicks"]},
 "c4-check":{name:"The check",family:"Kicks",cue:"Lift the shin like a shield, then plant.",
  steps:["Stance and guard, a hand on the chair if needed. Picture a low round kick coming at your lead leg.","Lift the lead knee up and slightly out, shin turned a little outward and the knee pointing toward the same-side elbow, foot relaxed below the knee. The guard stays up.","Hold one count, then set the foot back down in stance. Breathe.","5 checks per round. Round 2 on the other lead. Round 3: check, then answer with a jab or cross as the foot lands."],
  checks:["The knee lifts toward the elbow and the guard stays up.","I plant back in stance without a hop."],
  supported:"Both hands on the chair and a smaller lift.",
  seated:"Sit tall and lift one knee slightly out and up, guard up, then lower.",
  avoid:"Never test a check against a real kick or an object; this is shape and balance only.",sources:["nhs-balance"]},
 "c4-chamber-hold":{name:"Chamber holds",family:"Balance",format:"H",hold:20,cue:"Hold the spring loaded. Breathe.",
  steps:["Side-on to the chair, one hand on it. Raise the lead knee to your chamber height (hip height or lower).","Hold the chamber about 20 seconds: standing knee soft, back tall, guard with the free hand, slow breaths.","Hold 1 on one leg, hold 2 on the other, hold 3 on the weaker leg. Set down early whenever form changes.","Progress by lighter fingertips, never by lifting the knee higher than the hip."],
  checks:["My hips stay level and the standing knee stays soft.","I set the foot down with control, not by dropping it."],
  supported:"Both hands on the chair and a lower knee.",
  seated:"Seated knee lifts held for 10–20 seconds each side.",
  avoid:"No holds through knee or hip pain, no eyes-closed holds.",sources:["nhs-balance","balance-training"]},
 "c4-kick-build":{name:"Kick, chamber, return",family:"Kicks",format:"B",cue:"Every kick goes out and comes home the same way.",
  steps:["Round 1: lead-leg front push kicks with full chamber and return, 4–5.","Round 2: rear-leg low round kicks, 4. Round 3: the same two kicks on the other side.","Round 4: alternate a front kick and a round kick with a stance check after each.","The chair stays within reach. Breathe out on every kick and rebuild your stance before the next."],
  checks:["Every kick returns to chamber, then stance.","My stance is rebuilt before the next kick."],
  supported:"Hand on the chair throughout and smaller kicks.",
  seated:"Seated knee lift and extension alternating with seated side swings.",
  avoid:"No hopping, no kicks above the hip, no speed beyond control.",sources:["kicks"]},
 "c4-links":{name:"Hands into kicks",family:"Kicks",format:"B",cue:"The hands open the door. The low kick walks through it.",
  steps:["1-2 into a rear low round kick: jab, cross, and as the cross returns the rear leg swings low. Set down in stance.","Jab into a lead front push kick: jab, chamber, push, re-chamber, set down.","Check and answer: lift the check, land, cross.","Rounds 1 and 3 on your usual lead, 2 and 4 on the other. Pause after each link to check your balance; the chair stays within reach."],
  checks:["After every kick I am balanced in my stance.","The guard returns between the hands and the kick."],
  supported:"Throw the hands at half range, then the kick with a hand on the chair.",
  seated:"Seated 1-2 followed by a seated knee lift and extension.",
  avoid:"No high kicks, no hopping, no speed until each link is clean.",sources:["kicks","jkd"]},
 "c4-mobility":{name:"Hip and ankle care",family:"Mobility",cue:"Free hips, quiet ankles.",
  steps:["Round 1: hip circles in each direction, then gentle knee hugs (one knee toward the chest, holding the chair).","Round 2: ankle circles and alphabet tracing with each foot, holding the chair or seated.","Round 3: a gentle standing hip-flexor stretch in a split stance, 15–20 seconds each side.","Rest between rounds. Recovery, not a workout."],
  checks:["Every movement stayed easy.","My hips and ankles feel freer than at the start."],
  supported:"Hold the chair for every round.",
  seated:"Seated hip circles, ankle circles and a seated knee hug.",
  avoid:"No forcing range, no bouncing.",sources:["nhs-flex","nhs-sitting"]},
 "c4-strength":{name:"Hips and legs for kicking",family:"Strength",format:"S",cue:"Strong hips keep low kicks honest.",exercises:["Hip flexor stretch","Adductor rock-back","Side-lying leg raise","Calf raise"],
  steps:["Hip flexor stretch: half-kneeling on a cushion, or a standing split stance holding the chair. Tuck the pelvis and shift gently forward. Switch sides halfway.","Adductor rock-back: on hands and knees with one leg out to the side, rock the hips slowly back within comfort. Switch sides halfway.","Side-lying leg raise: lie on your side and lift the top leg slightly behind the body line, toes forward, 8–10 per side.","Calf raise: holding the chair, rise onto the toes and lower slowly, 10–12. Stop every exercise 2–3 reps before it gets hard."],
  checks:["Every rep was controlled with 2–3 left in reserve.","Stretches stayed at mild tension."],
  supported:"Standing hip-flexor stretch and standing side leg lifts holding the chair; a shallow standing side lunge for the inner thighs.",
  seated:"Seated knee-out stretch, seated leg lifts and seated heel raises.",
  avoid:"No splits, no forcing range, no pain.",sources:["nhs-strength","nhs-flex","rir"]},
 "c4-selfcheck":{name:"Kicks self-check",family:"Self-check",cue:"Low, balanced, both sides.",
  steps:["Round 1, one leg: three of this week's kicks or holds, slowly. Watch the two form checks for that skill.","Round 2, the other leg: the same. Which side is steadier?","Round 3: repeat the weaker side, slowly, with support.","Review minute: one repeatable kick and one correction for next week. Self-recording is optional and stays on your device."],
  checks:["I can name my steadier and weaker side.","I chose a correction instead of kicking higher or faster."],
  supported:"Do the whole check with a hand on the chair.",seated:"Do the seated versions and judge the knee path.",
  avoid:"No extra rounds, no height chasing.",sources:["nhs-balance"]},
 "c4-trial-1":{name:"Trial · chamber and height",family:"Chapter trial",format:"B",cue:"Show the chamber you built.",
  steps:["Round 1: chamber holds of two counts on the lead leg, 4–5, then front push kicks.","Round 2: the same on the rear leg.","Round 3: low round kicks, both legs. Round 4: low side step-kicks, both sides.","Mark the checks honestly. Support counts fully; this trial measures control, not balance without help."],
  checks:["The chamber is held for two counts (support allowed) with a soft standing knee.","No kick goes above hip height."],
  supported:"Take the trial with a hand on the chair throughout.",seated:"Take the seated knee-lift and extension version and judge the path and control.",
  avoid:"Low and controlled is the test. No hopping or height chasing.",sources:["kicks","nhs-balance"]},
 "c4-trial-2":{name:"Trial · kicks that come home",family:"Chapter trial",format:"B",cue:"Out, back, plant. Both sides.",
  steps:["Round 1: 1-2 into a rear low round kick, usual lead, 3–4 times.","Round 2: jab into a lead front push kick, other lead.","Round 3: check and answer, both legs. Round 4: your weaker kick on its weaker side, slowly.","Review: compare the two sides honestly. The week can be repeated without penalty."],
  checks:["Every kick returns to chamber, then stance, without hopping.","Both sides were tested."],
  supported:"Hand on the chair for every kick.",seated:"Seated hands then seated knee extensions.",
  avoid:"No kicks above the hip, no hopping, no speed for its own sake.",sources:["kicks"]},
});

export const CHAPTER_4:ChapterSpec = {chapter:4,warm:"c4-warm",cool:"c4-cool",drills,weeks:[
 {name:"Balance and the chamber",focus:"Supported single-leg balance, the knee raise to chamber and the knee strike in the air.",
  goals:["I can hold a supported single-leg balance for about 20 seconds per side, or the seated lift.","I can raise my knee to chamber and hold it for two counts with a soft standing knee.","I stepped down whenever I wobbled instead of hopping to recover."],
  days:[["The loaded spring","Balance & chamber",["c4-balance","c4-chamber","c4-chamber","c4-knee","c2-onetwo"],"Kicks start on one leg. Hold blocks begin: steady holds with the chair beside you."],
   ["One leg, easy","Easy review",["c4-balance","c3-slip","c2-onetwo","c4-mobility"]],
   ["Knee to the line","Chamber & knee volume",["c4-balance","c4-chamber","c4-knee","c3-curves","c4-knee"],"Main volume: chambers and knee strikes, both legs, support always allowed."],
   ["Hips and hands","Chamber & strength",["c4-balance","c4-chamber","c3-counters","c4-knee","c4-strength"]],
   ["Check the chamber","Balance self-check",["c4-balance","c4-chamber","c4-knee","c3-flow","c4-selfcheck"],"Test-style: two-count chambers on both legs."],
   ["Easy legs","Easy flow",["f2-shift","c4-chamber","c3-cover","c4-mobility"]]]},
 {name:"The front push kick",focus:"Chamber, extend, re-chamber, set down: a low push kick on both legs.",
  goals:["I can do a low front push kick in four parts: chamber, extend, re-chamber, set down.","My front kicks stay at or below hip height with a soft standing knee, on both legs.","I kept the chair within reach for every kick."],
  days:[["Shut the door","Front push kick",["c4-balance","c4-chamber","c4-teep","c4-teep"],"A calmer week to learn the first kick in four clean parts."],
   ["Easy legs","Easy review",["c4-balance","c4-knee","c2-onetwo","c4-mobility"]],
   ["Push and return","Front kick volume",["c4-chamber","c4-teep","c4-balance","c4-teep","c3-counters"],"Volume with control: every kick comes home to chamber before it lands."],
   ["Kick and strength","Front kick & strength",["c4-teep","c4-knee","c4-chamber","c4-strength"]],
   ["Check the push","Front kick self-check",["c4-balance","c4-teep","c4-knee","c4-teep","c4-selfcheck"],"Four parts, both legs, low."],
   ["Easy hips","Easy flow",["f2-shift","c4-chamber","c4-teep","c4-mobility"]]]},
 {name:"The low round kick",focus:"Turn the standing heel so the hip turns; the shin swings low and returns on the same path.",
  goals:["I can turn the standing heel so my hip turns on the low round kick.","My round kick returns along the same path to chamber, then stance, on both legs.","I kept round kicks low (knee to thigh height) instead of chasing height."],
  days:[["The gate swings","Low round kick",["c4-balance","c4-chamber","c4-round","c4-round","c4-teep"],"The round kick lives low. Turn the standing heel; the hip follows."],
   ["Easy legs","Easy review",["c4-balance","c4-teep","c3-slip","c4-mobility"]],
   ["Low and back","Round kick volume",["c4-chamber","c4-round","c4-teep","c4-round","c4-kick-build"],"Main volume: both kicks, both legs, every one returning on its path."],
   ["Kicks and curves","Round kick & strength",["c4-round","c4-teep","c4-kick-build","c3-curves","c4-strength"]],
   ["Check the swing","Round kick self-check",["c4-balance","c4-round","c4-kick-build","c4-teep","c4-selfcheck"],"Heel turn, low arc, same path home."],
   ["Easy turn","Easy flow",["f2-shift","c4-chamber","c4-round","c4-mobility"]]]},
 {name:"Side step-kick and the check",focus:"The low side step-kick (a stop-kick at knee height) and the shin check; chamber holds.",
  goals:["I can step up behind without crossing and press a low side kick out and back.","I can lift a check with the guard up and plant back in stance.","I held the chamber in 20-second supported holds on both legs."],
  days:[["The stop sign","Side step-kick & check",["c4-chamber-hold","c4-side","c4-side","c4-check","c4-round"],"Two new shapes: a low stop-kick and the check. Both short, both low."],
   ["Easy legs","Easy review",["c4-balance","c4-teep","c4-round","c4-mobility"]],
   ["Stop and shield","Side kick & check volume",["c4-chamber-hold","c4-side","c4-check","c4-kick-build","c4-side","c4-check"],"The chapter's fullest day so far. Low, slow, supported."],
   ["Shields and strength","Kicks & strength",["c4-side","c4-check","c4-kick-build","c4-teep","c4-strength"]],
   ["Check every kick","Kick self-check",["c4-chamber-hold","c4-side","c4-check","c4-round","c4-kick-build","c4-selfcheck"],"Test-style: all four kicks, both sides."],
   ["Easy legs","Easy flow",["f2-shift","c4-chamber","c4-check","c4-mobility"]]]},
 {name:"Hands into kicks",focus:"1-2 into a low round kick, jab into a front kick, check and answer, with balance after each.",
  goals:["I can throw 1-2 into a low round kick and jab into a front kick with balance after each.","I can check and answer with a cross without hopping.","I slowed down whenever my balance after a kick slipped."],
  days:[["Open the door","Hands into kicks",["c4-chamber-hold","c2-onetwo","c4-links","c4-links","c4-check"],"The classic kickboxing link: hands high, kick low."],
   ["Easy legs","Easy review",["c4-balance","c4-round","c4-teep","c4-mobility"]],
   ["High hands, low kicks","Links volume",["c4-chamber-hold","c4-round","c4-links","c4-side","c4-links","c4-kick-build"],"The chapter's peak: still 40 minutes, still controlled."],
   ["Links and strength","Links & strength",["c4-links","c4-check","c4-kick-build","c3-counters","c4-strength"]],
   ["Check the links","Links self-check",["c4-chamber-hold","c4-links","c4-kick-build","c4-links","c4-check","c4-selfcheck"],"Balance after every kick, on both leads."],
   ["Easy flow","Easy flow",["f2-shift","c4-chamber","c4-links","c4-mobility"]]]},
 {name:"Trial week · Kicks",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Kicks trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the base","Light review",["c4-balance","c4-chamber","c4-teep","c4-mobility"]],
   ["Review the swing","Light review",["c4-balance","c4-round","c4-check","c4-mobility"]],
   ["Crisp and low","Light review",["c4-chamber-hold","c4-side","c4-links","c4-kick-build"]],
   ["Calm before the trial","Light review",["c4-teep","c4-round","c4-check","c4-strength"]],
   ["Trial: Kicks","Chapter trial",["c4-balance","c4-kick-build","c4-trial-1","c4-trial-2","c4-links","c4-mobility"],"The chapter trial: low controlled kicks with chamber and return, both sides. Support counts fully."],
   ["After the trial","Easy flow",["f2-shift","c4-chamber","c4-teep","c4-mobility"]]]},
]};
