import {makeDrills,type ChapterSpec} from "./build";

// Chapter 3 · Guard and defense. Covers, parries, the slip, the roll and exits that always
// return to stance; then the compact curved strikes.
const drills = makeDrills(3,{
 "c3-warm":{name:"Trunk, neck and knees",family:"Preparation",timing:"warmup",cue:"Defense lives in the knees and the eyes. Wake both.",
  steps:["First 30 seconds: clear your space, put the chair within reach and find your point at chin height across the room.","Next 2 minutes: march gently in place, then add slow trunk turns with your hands on your chest and easy shoulder circles. Let your breathing rise a little.","Next 90 seconds: turn your head slowly left and right with the chin level, then small ear-toward-shoulder tilts. No circles. Then 6 slow quarter-squats holding the chair, and 5 half-range jabs per hand.","Final minute: feet together, eyes on your point, a small bow. Step into your stance, raise your guard with one sharp breath out, and hold one breath of stillness. Practice begins."],
  checks:["My neck and trunk turned easily within a comfortable range.","I opened with the bow and the ready."],
  supported:"Hold the chair throughout and do the knee bends with a smaller range.",
  seated:"Seated marches, seated trunk turns, slow neck turns and tilts, then a seated bow and guard.",
  avoid:"No neck circles, no forced turns, no bouncing. Stop if you feel dizzy.",sources:["aaos","neck"]},
 "c3-cool":{name:"Settle the spine",family:"Finish",timing:"cooldown",cue:"Slow eyes, slow breath, long spine.",
  steps:["First 2 minutes: lower the hands and walk slowly, shaking out the arms and letting the head stay still and level.","Next 2 minutes: a gentle trunk rotation with your hands on the chair back, a calf stretch against the wall (15–20 seconds each side), and two slow neck turns each way.","Final minute: breathe in for 4 counts and out for 6. Name one defense that felt clean and one that needs work. A note is optional.","Close with feet together and a small bow. If you felt dizzy at any point today, rest and keep tomorrow gentle."],
  checks:["My breathing settled and my head feels clear.","I can name one clean defense and one to repeat."],
  supported:"Use the chair for every stretch and walk with a hand near it.",
  seated:"Seated trunk turns, seated calf stretch with the leg out straight, slow breathing and a seated bow.",
  avoid:"Mild stretch only. Stop with tingling, numbness or dizziness.",sources:["nhs-flex","neck"]},
 "c3-cover":{name:"High cover and guard recovery",family:"Defense",cue:"Shell up. Eyes open. Come back out with an answer.",
  steps:["From guard, bring both forearms up to frame your head: fists against your forehead, elbows in front of your ribs, chin slightly down. Look at your point through the gap between your forearms.","Hold the cover for two counts as if a flurry is landing on your arms. Keep breathing out and keep the knees soft.","Open back to your normal guard and answer with a jab: covering is temporary and ends in your reply. Then guard home.","4–5 cover-and-answer cycles per round; round 2 on the other lead; round 3: cover, then step back out of range and reset your guard."],
  checks:["My eyes stay open and forward inside the cover.","I return to my usual guard after every cover."],
  supported:"Stand beside the chair with feet planted and practise the cover and the reopening slowly.",
  seated:"Sit tall and bring the forearms up to frame the head, hold two counts, open to guard.",
  avoid:"Do not close your eyes, hold your breath or curl forward. Never let anyone test the cover with real strikes.",sources:["boxing-beginner"]},
 "c3-parry":{name:"Parries in the air",family:"Defense",cue:"A small catch on a short path. The hand never leaves home for long.",
  steps:["Picture your opponent's jab coming at your face from your point. Your rear hand meets it a few centimetres in front of your face: open palm, a small push toward your lead shoulder. Then home.","Lead-hand parry: picture a cross; your lead palm turns it aside with a small movement and a slight turn of the shoulders, then returns.","Keep every parry small and near the centre line, never a big swipe. Breathe out with each and keep your eyes on the point.","Round 1: six rear-hand parries. Round 2: six lead-hand parries. Round 3: alternate, then try parry-jab: catch with the rear hand, answer with your jab."],
  checks:["Each parry is small and close to my face.","The parrying hand returns to guard straight away."],
  supported:"Plant the feet beside the chair and parry with one hand while the other rests on the chair back.",
  seated:"Sit tall in guard and make the same small parries at face height.",
  avoid:"No wide swipes or reaching out to meet the punch. Never practise parries against a real partner's strikes in this programme.",sources:["boxing-beginner"]},
 "c3-slip":{name:"The slip",family:"Defense",cue:"Let it pass by a hand's width. Not a metre.",
  steps:["Picture a jab coming at your nose. Bend the knees slightly and turn the shoulders so your head moves about a hand's width to the side, outside the punch (to the right first if you lead with the left foot). Your head stays above your stance, never outside your feet.","Hold for a heartbeat, then come straight back to centre with the guard up. The punch should miss by centimetres. Eyes on the point the whole time.","Then slip to the other side by the same small distance and back to centre. Move with the knees and shoulders; do not bend sideways at the waist or drop the hands.","Slowly: one slip every 3–4 seconds, about 6 per round. Round 2 on the other lead; round 3 alternate sides. Stop at once if you feel dizzy."],
  checks:["My head moves a hand's width and returns to centre over my stance.","My hands stay up and my eyes stay forward through every slip."],
  supported:"Hold the chair back with one hand and make the slip a small shoulder turn and knee bend.",
  seated:"Sit tall and lean the torso a hand's width to each side from the hips, returning to centre with the hands up.",
  avoid:"No fast head movement, no bending sideways at the waist, no slipping outside your feet. Stop if dizzy.",sources:["boxing-club"]},
 "c3-roll":{name:"The roll",family:"Defense",cue:"Bend the knees, not the back. Under, and up.",
  steps:["Picture a hook swinging at head height from your lead side. Bend both knees to lower your head a short way, keeping a long back and your eyes forward, like ducking under a branch.","Move the head in a shallow U: down, across under the imagined hook, and up on the other side. The hands stay up by your cheeks.","Come up in your full stance and guard. The roll is shallow, no deeper than a comfortable quarter squat.","One roll every 4 seconds, about 5 per round, in both directions. Round 2 on the other lead. Round 3: roll, then jab as you rise."],
  checks:["My knees bend while my back stays long.","The roll is shallow and I come up in stance with the guard up."],
  supported:"Hold the chair back with both hands and practise the knee bend and shallow U slowly.",
  seated:"Sit tall and trace a small U with the upper body by leaning slightly forward from the hips, hands up. This rehearses the path only.",
  avoid:"No bending at the waist, no deep squats, no fast head movement and no rolling on the floor. Stop if dizzy or with knee pain.",sources:["boxing-club"]},
 "c3-exits":{name:"Step-back and pivot exits",family:"Defense",cue:"Don't stay where the punch is going.",
  steps:["Step-back exit: from stance, step back with the rear foot, then the front foot, guard high, eyes forward. Stop.","Pivot exit: turn on the ball of the front foot and let the rear foot swing a short arc behind you, a quarter turn or less, so you face your point from a new angle. Feet never cross.","Pivot back to your starting angle the same way and check: still in stance, guard up.","Round 1: step-backs. Round 2: small pivots. Round 3: alternate a step-back and a pivot. Change lead between rounds."],
  checks:["My front foot turns on its ball and my feet never cross.","After every exit I am in stance, guard up, facing my point."],
  supported:"Hold the chair and make the pivot a quarter of the size; replace the step-back with a weight shift.",
  seated:"Turn the knees and trunk a little to each side in the chair to rehearse the change of angle.",
  avoid:"No spinning, no fast turns on a planted knee, no backward hopping.",sources:["boxing-club"]},
 "c3-hook":{name:"Lead hook",family:"Curved strikes",cue:"Short and compact. The body turns the arm.",
  steps:["From stance, shift a little weight toward the rear leg. Bend the lead arm to about a right angle at shoulder height, elbow behind the fist.","Turn the hips and shoulders together toward the rear side while the lead heel turns out on the ball of the foot. The arm keeps its shape; the turning body carries it in a short arc to your point. Breathe out.","The fist travels no wider than your shoulder line and stops at the point. The rear hand stays glued to your cheek. Turn back and return the hand to guard.","Slowly, about 5 per round. Round 2 on the other lead. Round 3: jab, then the hook from the returning jab."],
  checks:["The arm angle stays fixed; the body's turn drives it.","The hook stops at my point and the rear hand stays home."],
  supported:"Hold the chair with the rear hand and turn the hip and shoulder slowly with the lead arm shaped.",
  seated:"Sit tall and rotate the trunk with the lead arm shaped at shoulder height, in a small arc.",
  avoid:"No wide swinging arms, no twisting on a planted knee, no full-power hooks into the air.",sources:["boxing-club"]},
 "c3-counters":{name:"Defense into counter",family:"Defense",format:"B",cue:"Defend and answer in one breath.",
  steps:["Slip-2: slip outside the imagined jab, then throw the cross as your head comes back to centre.","Parry-1: catch the imagined jab with the rear hand and answer at once with your own jab.","Each 40-second round: alternate the two pairs, about 4–5 of each, at slow tempo with a pause after each pair. Rounds 1 and 3 on your usual lead, 2 and 4 on the other.","Feet stay planted and apart. The answer starts only when the defense is complete."],
  checks:["The defense finishes before the counter starts.","My feet stay apart and planted; nothing crosses."],
  supported:"Keep a hand near the chair and do both pairs at half range with feet still.",
  seated:"Seated slip lean or parry, then the seated strike at chest height.",
  avoid:"No speed before the pair is clean. Do not practise counters against a real partner.",sources:["boxing-beginner","jkd"]},
 "c3-uppercut":{name:"Short uppercuts",family:"Curved strikes",cue:"Close, short, up through the chin line.",
  steps:["Rear uppercut: shift a little weight toward the rear side and let the rear hand drop a few centimetres, palm facing you, elbow bent at about a right angle.","Turn the rear heel and hip toward your point and drive the fist up through an imagined chin in front of your chest. Breathe out. The fist rises no higher than your own chin.","Bring it straight home. Lead uppercut: the same on the lead side with a small turn the other way.","About 5 slow uppercuts per round: round 1 rear, round 2 lead, round 3 alternating on the other lead."],
  checks:["The elbow stays bent and the fist stops at chin height.","The other hand stays home at the cheek."],
  supported:"Plant the feet beside the chair and practise the hip turn and short arm path slowly.",
  seated:"Sit tall and drive short uppercuts at chest height with a small trunk turn.",
  avoid:"No looping wind-ups, no straightening the arm, no full power.",sources:["boxing-club"]},
 "c3-curves":{name:"Hook and uppercut, guard home",family:"Curved strikes",format:"B",cue:"Two short arcs. The guard is already home.",
  steps:["1-2-hook: jab, cross, lead hook. The cross's turn loads the hook.","Uppercut-hook: rear uppercut, then lead hook. Both short, both driven by the turn of the hips.","After each combination, guard home and hold your eyes on the point for one count. About 4 of each per round.","Rounds 1 and 3 on your usual lead, rounds 2 and 4 on the other. If either strike widens, slow down."],
  checks:["Both curved strikes stay compact.","The guard returns after every combination."],
  supported:"Throw the combinations at half range with the feet planted beside the chair.",
  seated:"Seated combinations at chest height with small trunk turns.",
  avoid:"No wide swings, no twisting the front knee, no locked elbows on the straights.",sources:["boxing-club"]},
 "c3-flow":{name:"Defense flow",family:"Defense",format:"B",cue:"Every defense comes home before the next one starts.",
  steps:["A slow chain: cover for two counts and open; parry an imagined jab; slip; roll under an imagined hook; step back.","Each defense returns to stance and guard before the next. One chain takes about 10 seconds.","3–4 chains per round. In rounds 3 and 4, finish each chain with a 1-2.","Change the lead between rounds. If you lose the order, do just the first three defenses."],
  checks:["Each defense returns to stance before the next.","My eyes stay on my point through the whole chain."],
  supported:"Run the chain with feet planted beside the chair, replacing the step with a weight shift.",
  seated:"Seated cover, parry and slip lean in sequence with a guard reset between each.",
  avoid:"Slow head movement only. Stop if dizzy.",sources:["boxing-beginner","boxing-club"]},
 "c3-mobility":{name:"Spine and neck care",family:"Mobility",cue:"A free spine turns faster than a strong one.",
  steps:["Round 1: slow trunk rotations with your hands on your chest, within a comfortable range.","Round 2: turn your head left and right with the chin level, 5 each side, then small ear-toward-shoulder tilts. Never neck circles.","Round 3: gentle cat-cow on hands and knees, or seated: arch and round the back slowly.","Rest with hands down between rounds. Recovery, not a workout."],
  checks:["Every movement stayed easy and pain-free.","My neck and back feel looser than when I started."],
  supported:"Stand holding the chair for the trunk turns and do cat-cow with hands on the chair seat.",
  seated:"Do every round seated with feet supported.",
  avoid:"No forced turns, no neck circles, no pain.",sources:["neck","nhs-flex","nhs-sitting"]},
 "c3-strength":{name:"Trunk and legs for defense",family:"Strength",format:"S",cue:"Strong legs make the roll; a free spine makes the slip.",exercises:["Thoracic rotation","Squat to chair","Side plank","Neck mobility"],
  steps:["Thoracic rotation (open book): lie on your side, knees bent, arms out in front. Open the top arm across to the other side, following it with your eyes, within comfort. Switch sides halfway.","Squat to chair: feet hip-width in front of a sturdy chair. Sit back to touch the seat lightly and stand, chest up, knees following the toes. 6–10 slow reps. This is the roll's knee bend.","Side plank: forearm under the shoulder, knees bent (easier) or legs long, hips lifted in a straight line. 10–20 seconds each side.","Neck mobility: slow turns and tilts within a comfortable range, 5 each way, never forced circles. Stop every exercise 2–3 reps before it gets hard."],
  checks:["Every rep was controlled with 2–3 left in reserve.","My back stayed long in the squat and my hips stayed level in the side plank."],
  supported:"Open book standing with hands on a wall; squat to a higher seat or with hands on a table; side plank as a standing forearm lean on a wall.",
  seated:"Seated trunk rotations, sit-to-stand with hand help, seated neck turns.",
  avoid:"No breath-holding, no knee or back pain, no forced neck range.",sources:["nhs-strength","neck","rir"]},
 "c3-selfcheck":{name:"Defense self-check",family:"Self-check",cue:"Defense is honest or it isn't defense.",
  steps:["Round 1, usual lead: three of this week's defenses at slow tempo. Watch the two form checks for that skill.","Round 2, other lead: the same. Notice which side and which defense is cleaner.","Round 3: repeat whichever defense needed the most help, slowly.","Review minute: name one repeatable defense and one correction for next week. Self-recording is optional and stays on your device."],
  checks:["I can name my cleanest defense and the one that needs practice.","I picked one correction instead of adding speed."],
  supported:"Do the check with feet planted beside the chair.",seated:"Do the check with the seated versions and judge the hands and eyes.",
  avoid:"Slow head movement only. No extra rounds.",sources:["boxing-club"]},
 "c3-trial-1":{name:"Trial · slips, rolls and curves",family:"Chapter trial",format:"B",cue:"Show defense that always comes home.",
  steps:["Round 1, usual lead: slow slips to both sides, 5–6. Watch your head return to centre over the stance.","Round 2: slow rolls in both directions, 4–5. Watch the knees bend and the back stay long.","Round 3: the lead hook, rear uppercut and 1-2-hook with the guard returning, usual lead. Round 4: the same on the other lead.","In the review, mark the checks honestly. 'Not yet' means repeat a week; it never blocks the story."],
  checks:["Slips return to centre over the stance.","Rolls bend the knees with a long back."],
  supported:"Take the trial with a hand on the chair and smaller movements.",seated:"Take the trial with the seated slip lean, U path and seated strikes.",
  avoid:"Slow head movement only. Stop if dizzy.",sources:["boxing-club"]},
 "c3-trial-2":{name:"Trial · defense into counter",family:"Chapter trial",format:"B",cue:"Defend, answer, come home.",
  steps:["Round 1: slip-2 at slow tempo, 4–5 times, usual lead.","Round 2: parry-1, 4–5 times, other lead.","Rounds 3–4: a defense-counter pair of your choice, then a compact hook with the guard returning, one round on each lead.","Review: which pair flowed, and which needs another week?"],
  checks:["Curved strikes stay compact with the guard returning.","A defense-counter pair flows at slow tempo without crossing my feet."],
  supported:"Keep the feet planted beside the chair and work at half range.",seated:"Seated defense lean or parry, then the seated counter.",
  avoid:"Slow tempo is the test. No speed for its own sake.",sources:["boxing-beginner","boxing-club"]},
});

export const CHAPTER_3:ChapterSpec = {chapter:3,warm:"c3-warm",cool:"c3-cool",drills,weeks:[
 {name:"Cover and parry",focus:"Cover with your eyes open and return to guard; turn imagined strikes aside with small parries close to your face.",
  goals:["I can cover with my eyes open and return to my guard on both leads, or with the seated version.","I can parry an imagined jab with a small movement close to my face and bring the hand straight home.","I kept breathing inside the cover instead of holding my breath."],
  days:[["Shell and answer","Cover & parry",["c2-onetwo","c3-cover","c3-parry","c3-parry","c3-cover"],"Defense begins. Every cover ends in an answer; every parry stays small."],
   ["Hands home","Easy review",["c2-jab","c3-cover","c2-onetwo","c3-mobility"]],
   ["Small catches","Parry volume",["c3-cover","c3-parry","c2-onetwo","c3-parry","c2-exit"],"Main volume: small, quick parries and a strike after each cover."],
   ["Parry and a strong middle","Parry & strength",["c3-cover","c3-parry","c2-double","c2-onetwo","c3-strength"]],
   ["Defend, then strike","Defense self-check",["c2-stepjab-build","c3-parry","c3-cover","c2-tempo","c3-selfcheck"],"Check both leads: eyes open in the cover, small parries."],
   ["Easy guard","Easy flow",["f2-shift","c3-cover","c2-onetwo","c3-mobility"]]]},
 {name:"The slip",focus:"Move the head a hand's width outside an imagined jab and back to centre, over your stance, slowly.",
  goals:["I can slip a hand's width to each side and return to centre over my stance, or use the supported/seated version.","My hands stay up and my eyes stay forward through every slip.","I moved my head slowly and stopped if I felt dizzy."],
  days:[["A hand's width","The slip",["c3-cover","c3-parry","c3-slip","c3-slip","c2-onetwo"],"The famous one. Small, slow, back to centre every time."],
   ["Easy defense","Easy review",["c3-cover","c3-parry","c2-onetwo","c3-mobility"]],
   ["Slip and return","Slip volume",["c3-parry","c3-slip","c2-onetwo","c3-slip","c2-exit","c3-cover"],"The fullest day of the chapter's first half. Head movement stays slow."],
   ["Knees and spine","Slip & strength",["c3-slip","c3-parry","c2-double","c3-slip","c3-strength"]],
   ["Check the slip","Slip self-check",["c2-stepjab-build","c3-slip","c3-parry","c3-slip","c2-tempo","c3-selfcheck"],"Do your slips come back to centre on both leads?"],
   ["Still head, easy body","Easy flow",["f2-shift","c3-slip","c3-cover","c3-mobility"]]]},
 {name:"The roll and the exits",focus:"Roll under an imagined hook from the knees with a long back; leave with a step back or a pivot.",
  goals:["I can roll under an imagined hook by bending my knees with a long back, no deeper than a comfortable quarter squat.","I can step back or pivot out without crossing my feet and finish in stance.","I chose the supported version whenever my knees or balance asked for it."],
  days:[["Under the branch","The roll",["c3-slip","c3-roll","c3-roll","c3-exits"],"A calmer week. The roll comes from the knees, never the waist."],
   ["Easy defense","Easy review",["c3-cover","c3-slip","c2-onetwo","c3-mobility"]],
   ["Roll and leave","Roll & exits",["c3-slip","c3-roll","c3-exits","c2-onetwo","c3-exits"],"Roll, then leave: a step back or a small pivot, feet never crossing."],
   ["Strong knees","Roll & strength",["c3-roll","c3-exits","c3-parry","c3-strength"]],
   ["Check the escape","Exit self-check",["c3-cover","c3-slip","c3-roll","c3-exits","c3-selfcheck"],"Every defense ends in your stance, facing your point."],
   ["Easy and level","Easy flow",["f2-shift","c3-roll","c3-slip","c3-mobility"]]]},
 {name:"Lead hook and counters",focus:"A compact lead hook driven by the body's turn; slip-2 and parry-1 at slow tempo.",
  goals:["I can throw a compact lead hook where the body turns the arm and the rear hand stays home.","I can do slip-2 and parry-1 at slow tempo with the defense finished before the counter.","I kept the hook short instead of swinging wide for power."],
  days:[["The first curve","Lead hook",["c2-onetwo","c3-hook","c3-hook","c3-slip","c3-exits"],"The lead hook: short, with the arm locked in shape and the body doing the work."],
   ["Easy defense","Easy review",["c3-cover","c3-slip","c3-roll","c3-mobility"]],
   ["Defend and answer","Counter volume",["c3-hook","c3-slip","c3-counters","c3-parry","c3-counters","c3-roll"],"Defense into counter: the answer starts only when the defense is done."],
   ["Hook and strength","Counters & strength",["c3-hook","c3-counters","c3-exits","c3-roll","c3-strength"]],
   ["Check the counters","Counter self-check",["c2-onetwo","c3-hook","c3-counters","c3-roll","c3-counters","c3-selfcheck"],"Slow tempo is the skill. Check both pairs on both leads."],
   ["Easy curves","Easy flow",["f2-shift","c3-hook","c3-cover","c3-mobility"]]]},
 {name:"Short uppercuts",focus:"Short rear and lead uppercuts that stop at chin height; hooks and uppercuts linked with the guard returning.",
  goals:["I can throw short rear and lead uppercuts that stop at chin height with the other hand home.","I can link a hook and an uppercut with my guard returning after each.","I ran the defense flow slowly with every defense returning to stance."],
  days:[["Up through the line","Uppercuts",["c3-hook","c3-uppercut","c3-uppercut","c3-counters","c3-roll"],"Close-range strikes: short, from the hips, no wind-up."],
   ["Easy defense","Easy review",["c3-cover","c3-hook","c3-slip","c3-mobility"]],
   ["Two short arcs","Curves volume",["c3-uppercut","c3-hook","c3-curves","c3-counters","c3-curves"],"Link the curves and keep them compact to the end of the session."],
   ["Flow and strength","Defense flow & strength",["c3-uppercut","c3-curves","c3-flow","c3-exits","c3-strength"]],
   ["Everything comes home","Defense flow self-check",["c3-flow","c3-curves","c3-counters","c3-roll","c3-selfcheck"],"The whole chapter in one session: defense, counter, curves."],
   ["Easy and loose","Easy flow",["f2-shift","c3-uppercut","c3-slip","c3-mobility"]]]},
 {name:"Trial week · Guard",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Guard trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the shell","Light review",["c3-cover","c3-parry","c3-slip","c3-mobility"]],
   ["Review the escapes","Light review",["c3-roll","c3-exits","c2-onetwo","c3-mobility"]],
   ["Crisp curves","Light review",["c3-hook","c3-uppercut","c3-counters","c3-flow"]],
   ["Calm before the trial","Light review",["c3-curves","c3-counters","c3-roll","c3-strength"]],
   ["Trial: Guard","Chapter trial",["c3-flow","c3-counters","c3-trial-1","c3-trial-2","c3-curves","c3-mobility"],"The chapter trial: defense into counter at slow tempo. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["f2-shift","c3-slip","c3-cover","c3-mobility"]]]},
]};
