import {makeDrills,type ChapterSpec} from "./build";
import {COMBINATION_MENU} from "./chapter-05";

// Chapter 9 · Integration: steady count. Long, rhythmic practice on the bell's steady count
// (metronome mode with a visual pulse), stance holds with breathing, the form under mild fatigue.
const menu = `Menu: ${COMBINATION_MENU.join(" · ")}.`;
const STOP = "Stop for dizziness, chest discomfort or unusual breathlessness and seek medical advice. Keep water near and go easier in heat.";
const REST_ON_COUNT = "Step out to rest whenever you need: march gently in place on the count, or sit and tap your hands on your knees on the count, and rejoin on the next accent. Resting on the count is part of the drill.";

const drills = makeDrills(9,{
 "c9-warm":{name:"Find the count",family:"Preparation",timing:"warmup",cue:"Feel the count before you hear it.",
  steps:["First 30 seconds: clear your space, water near, support within reach. Find your point.","Next 2 minutes: march, matching your steps to an easy inner count of four. Let the breathing rise a little and settle into the rhythm.","Next 90 seconds: ankle circles, hip circles and shoulder rolls, then 30 seconds of the base pattern at half pace: step in, guard, breathe, step back.","Final minute: feet together, a small bow. Step into stance and raise the guard with one sharp breath out. One breath of stillness. Practice begins."],
  checks:["I found an easy rhythm before the first block.","I opened with the bow and the ready."],
  supported:"March and step holding your support.",
  seated:"Seated marching on an inner count, seated mobility, a seated bow.",
  avoid:STOP,sources:["aaos","heat"]},
 "c9-cool":{name:"Slow the count",family:"Finish",timing:"cooldown",cue:"Let the count get slower until it stops.",
  steps:["First 2 minutes: walk slowly, each lap a little slower than the last.","Next minute: calf, hip-flexor and chest stretches, mild tension.","Next 90 seconds: breathe in for 4 counts and out for 8, letting your inner count slow down.","Final 30 seconds: feet together, a small bow, then water. If your breathing hasn't settled within a few minutes, rest and seek advice if you feel unwell."],
  checks:["My breathing settled before I finished.","I drank water and feel steady."],
  supported:"Use your support for the walk and the stretches.",
  seated:"Seated breathing and stretches, a seated bow.",
  avoid:STOP,sources:["breath","nhs-flex"]},
 "c9-count-base":{name:"The Line · base count",family:"Count",format:"G",tempo:56,countCycle:8,cue:"Hold the line. The count holds you.",
  steps:["The base pattern, eight counts, repeated for six minutes on the bell's steady count: step forward (1, 2: front foot, rear foot), guard reset (3), breathe (4), step back (5, 6: rear foot, front foot), guard reset (7), breathe (8). The accent marks count 1.","Stay on the count: one action per count, relaxed and exact. If you lose it, stand in guard and rejoin on the next accent.",REST_ON_COUNT,"Then three minutes of breathing and review: in for 4 counts, out for 6. Notice how steady you were, not how hard you worked."],
  checks:["I stayed on the count, rejoining on the accent when I lost it.","I rested on the count when I needed instead of stopping the block."],
  supported:"Replace the steps with forward and back weight shifts beside your support, still on the count.",
  seated:"Seated base count: foot taps forward and back, guard resets and breaths on the count.",
  avoid:"Steady, easy-to-moderate work. Never race the count; slow the tempo instead. "+STOP,sources:["talk-test","focus"]},
 "c9-count-hands":{name:"The Line · hands count",family:"Count",format:"G",tempo:60,countCycle:4,cue:"Forty clean 1-2s look like the first one.",
  steps:["Four counts, repeated: jab (1), cross (2), guard (3), breathe (4). Change lead when the clock shows 4:00 and 2:00 left in the count, between count 4 and the next accent.","Relaxed strikes, a breath out on each, elbows short of straight. The aim is the same quality on the last cycle as the first.",REST_ON_COUNT,"Then three minutes of breathing and review."],
  checks:["My 1-2s stayed clean to the end of the count.","I changed lead on the marks without losing the count."],
  supported:"Half-range 1-2s with the feet planted beside your support.",
  seated:"Seated hands count at chest height.",
  avoid:"No locked elbows, no racing. "+STOP,sources:["talk-test","boxing-beginner"]},
 "c9-count-full":{name:"The Line · full count",family:"Count",format:"G",tempo:56,countCycle:8,cue:"Every family, one rhythm.",
  steps:["Eight counts: jab (1), cross (2), slip right (3), cross (4), lead hook (5), guard (6), lead check (7), set down (8). The accent marks count 1.","Change lead when the clock shows 4:00 and 2:00 left, between count 8 and the next accent. Support within reach for the check.",REST_ON_COUNT,"Then three minutes of breathing and review."],
  checks:["I held the full pattern on the count.","My balance stayed steady through every check."],
  supported:"Hands and slips with feet planted; a small supported knee lift for the check.",
  seated:"Seated full count: strikes, a slip lean and a knee lift on the count.",
  avoid:"Slow head movement, low check, no racing. "+STOP,sources:["talk-test","boxing-club"]},
 "c9-hold":{name:"Stance hold with breathing",family:"Stance",format:"H",hold:30,cue:"Be the stone in the river.",
  steps:["Hand on your support, build your stance a little lower than usual (knees softly bent, never deeper than is comfortable), guard up, eyes on your point.","Hold still and breathe slowly through the nose: in for 4, out for 6. Shoulders down, face relaxed.","Holds of about 30 seconds: hold 1 on your usual lead, hold 2 on the other, hold 3 your choice. Rise or rest early whenever form or comfort changes.","This is stillness training: the rooted, calm stance is a breathing skill as much as a leg skill."],
  checks:["My knees track over my toes and my back stays tall.","My breathing stays slow and quiet through the hold."],
  supported:"Both hands on your support and a taller stance.",
  seated:"A tall seated hold: feet planted, guard up, slow breathing.",
  avoid:"No deep horse stances, no holding through knee pain, no breath-holding.",sources:["nhs-balance","breath"]},
 "c9-form-tired":{name:"The Lantern Form after rounds",family:"Lantern Form",format:"E",minutes:10,tempo:44,cue:"When you're tired, the form is a map home.",
  steps:["This block follows rounds, while you are mildly tired. Slow run: the whole Lantern Form, slower than usual and precise.","Review: three long exhales; rebuild your stance.","Count-tempo run on the bell's count, set a little slower than usual. Turn it down further with the tempo control if you need to.","If form breaks, slow down or switch to one section at a time. Mild fatigue only: short sentences still possible."],
  checks:["The form came from memory while I was mildly tired.","I slowed the tempo when I needed to instead of rushing."],
  supported:"Section by section with your support near for the kicks.",
  seated:"The seated Lantern Form.",
  avoid:STOP,sources:["kata-balance","talk-test"]},
 "c9-intent":{name:"Shadow rounds with intent",family:"Rounds",format:"C",cue:"Every round has a reason.",
  steps:["Before each round, choose an intent and say it. For example: round 1 'jab first' (every combination starts with the jab); round 2 'defend, then answer'; round 3 'finish low' (end combinations with a low kick or a check).",`Choose your own combinations to serve the intent, including defense. After each, guard home and move. ${menu}`,"Effort at 'short sentences'. In each rest, walk, breathe out long and choose the next intent.","In the last rest, review: did the intent change how you met your imagined opponent?"],
  checks:["Every round followed the intent I chose.","My self-chosen combinations stayed controlled."],
  supported:"Hands-only intents, kicks with your support.",
  seated:"Seated rounds with an intent.",
  avoid:STOP,sources:["imagery","practice-order"]},
 "c9-intent-d":{name:"Long rounds with intent",family:"Rounds",format:"D",cue:"Three minutes, one purpose.",
  steps:["Two 3-minute rounds, each with an intent you choose and say aloud before the bell: 'jab first', 'defend, then answer', 'finish low', 'angles after everything'.",menu,"Rests: walk, breathe out long, choose the second intent.","Effort never past 'short sentences'. If form breaks, slow down: that is still the intent."],
  checks:["Both rounds followed their intent.","Effort never went past 'short sentences'."],
  supported:"Hands-only intents, kicks with your support.",
  seated:"Seated long rounds with an intent.",
  avoid:STOP,sources:["imagery","talk-test"]},
 "c9-crisp":{name:"Crisp, low volume",family:"Taper",format:"B",cue:"Fewer, sharper, calmer.",
  steps:["A lighter week means less volume, not less care. Each round: only 3–4 repetitions of one technique, done as crisply and exactly as you can.","Round 1: 1-2. Round 2: slip-2-hook. Round 3: 1-2-low kick (support near). Round 4: an elbow or a check.","Between repetitions, stand still in guard and breathe; the round can be mostly stillness.","Crisp means exact and quick, never maximal."],
  checks:["Each repetition was exact.","I rested in stillness between repetitions instead of adding more."],
  supported:"Fewer, half-range repetitions with support.",
  seated:"Seated crisp strikes with stillness between.",
  avoid:"No extra volume. No maximal speed or power.",sources:["focus"]},
 "c9-selfcheck":{name:"Integration self-check",family:"Self-check",cue:"Does it all still hold together?",
  steps:["Round 1: one minute of this week's count pattern at a comfortable tempo.","Round 2: one section of the Lantern Form, slowly.","Round 3: one combination from your intent rounds, checking guard, feet and elbows.","Review minute: which family holds up best when you're tired, and which slips first? That's next week's focus."],
  checks:["I can name the family that holds up best and the one that slips first.","My breathing settled in the review."],
  supported:"Check with support near.",seated:"Check seated.",
  avoid:STOP,sources:["kata-balance"]},
 "c9-trial-count":{name:"Trial · the long count",family:"Chapter trial",format:"G",tempo:56,countCycle:8,cue:"Six minutes. One line. Unbroken.",
  steps:["The base count or the full count, your choice, for six minutes on the bell's count. Set the tempo where you trained it.","Stay on the count; rejoin on the accent whenever you lose it.",REST_ON_COUNT,"Then three minutes of breathing and review. Mark the checks honestly; 'not yet' means repeat a week and never blocks the story."],
  checks:["I held the count without losing the rhythm (resting on the count is allowed).","My breathing stayed steady."],
  supported:"The supported base count with weight shifts.",seated:"The seated count.",
  avoid:STOP,sources:["talk-test"]},
 "c9-trial-form":{name:"Trial · the form, mildly tired",family:"Chapter trial",format:"E",minutes:10,tempo:44,cue:"The map home, from memory.",
  steps:["Slow run: the whole Lantern Form from memory, straight after the count.","Review: three long exhales, rebuild your stance.","Count-tempo run on a slightly slower count.","If you forget a count, hold your guard and continue from the next one you remember."],
  checks:["The Lantern Form came from memory while mildly tired.","My stance was rebuilt at each section end."],
  supported:"Section by section with support.",seated:"The seated form.",
  avoid:STOP,sources:["kata-balance"]},
 "c9-trial-rounds":{name:"Trial · two rounds with intent",family:"Chapter trial",format:"D",cue:"Your rounds. Your reasons. Your control.",
  steps:["Two 3-minute rounds with intents you choose and say before the bell.",menu,"Rests: walk and breathe out long.","Then the cool-down is your long cool-down: slow the count until it stops."],
  checks:["Self-chosen rounds stayed controlled.","My guard came home between combinations."],
  supported:"Hands-only intents, kicks with support.",seated:"Seated rounds with intent.",
  avoid:STOP,sources:["imagery","talk-test"]},
});

export const CHAPTER_9:ChapterSpec = {chapter:9,warm:"c9-warm",cool:"c9-cool",drills,weeks:[
 {name:"The base count",focus:"Count blocks begin: a continuous base pattern of steps, guard and breath on the bell's steady count.",
  goals:["I can hold the base count for six minutes, resting on the count whenever needed.","When I lost the count I rejoined on the next accent.","I slowed the tempo rather than racing the count."],
  days:[["Hold the line","Base count",["c8-breath","c9-count-base","c7-smooth","c8-rhythm"],"Count blocks begin: six minutes on a steady count. Steady, never racing; rest on the count whenever you need."],
   ["Easy count","Easy review",["c9-count-base","c8-breath","c7-mobility"]],
   ["Count and long rounds","Count volume",["c9-count-base","c8-long","c8-breath"],"Main volume: the count, then long rounds."],
   ["Count and strength","Count & strength",["c9-count-base","c7-cue-mixed","c6-strength-1","c6-strength-2"]],
   ["Count and form","Count self-check",["c9-count-base","c7-form","c9-selfcheck"],"Test-style: the count and the form, honestly reviewed."],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c7-smooth","c6-flow-hips"]]]},
 {name:"Stance and the hands count",focus:"Supported stance holds with slow breathing; the hands count.",
  goals:["I can hold a supported stance for about 30 seconds with slow, quiet breathing.","I can keep the hands count clean from the first cycle to the last.","I rose from the hold early whenever form or comfort changed."],
  days:[["The stone in the river","Stance holds",["c9-hold","c9-count-base","c9-hold","c8-breath"],"Stillness training: rooted stance, quiet breath."],
   ["Easy review","Easy review",["c9-hold","c8-rhythm","c7-smooth","c7-mobility"]],
   ["Forty clean 1-2s","Hands count",["c9-hold","c9-count-hands","c8-long"],"Main volume: holds, the hands count and long rounds."],
   ["Count and strength","Count & strength",["c9-hold","c9-count-hands","c8-engine","c6-strength-1"]],
   ["Check the line","Count self-check",["c9-count-hands","c7-form","c9-selfcheck"],"Does the count hold your form together?"],
   ["Easy flow","Easy flow",["c7-mobility","c9-hold","c8-breath","c6-flow-upper"]]]},
 {name:"The form when tired",focus:"The Lantern Form after rounds, under mild fatigue, with the tempo turned down as needed.",
  goals:["I can perform the Lantern Form after rounds while mildly tired.","I used a slower tempo or the section-by-section version when tired.","My effort stayed at 'short sentences' before the form."],
  days:[["The map home","Form after rounds",["c9-hold","c8-long","c9-form-tired"],"Rounds first, then the form while a little tired: calm, slow, exact."],
   ["Easy count","Easy review",["c9-hold","c9-count-base","c7-mobility"]],
   ["Rounds, then form","Form after rounds",["c5-rounds","c9-form-tired","c8-breath"],"Main volume: rounds, then the whole form."],
   ["Count and strength","Count & strength",["c9-count-hands","c7-cue-menu","c6-strength-2","c8-engine"]],
   ["Check the map","Form self-check",["c8-long","c9-form-tired","c9-selfcheck"],"Does the form survive the rounds?"],
   ["Easy flow","Easy flow",["c7-mobility","c9-hold","c7-smooth","c6-flow-hips"]]]},
 {name:"Rounds with intent",focus:"Shadow rounds where you choose the combinations, including defense, to serve an intent you name.",
  goals:["I can run shadow rounds with a chosen intent, including defense.","My self-chosen combinations stayed controlled.","I chose a new intent for each round and reviewed it."],
  days:[["Every round has a reason","Rounds with intent",["c9-hold","c9-intent","c8-composure","c7-cue-defense"],"Your rounds now have reasons. Name the intent before the bell."],
   ["Easy count","Easy review",["c9-count-base","c8-breath","c7-mobility"]],
   ["Intent and count","Intent volume",["c9-intent","c9-count-hands","c9-hold"],"Main volume: rounds with intent and the hands count."],
   ["Intent and strength","Intent & strength",["c9-intent","c7-cue-menu","c6-strength-1","c8-engine"]],
   ["Check the intent","Rounds self-check",["c9-intent","c9-form-tired","c9-selfcheck"],"Did each intent change how you moved?"],
   ["Easy flow","Easy flow",["c7-mobility","c9-hold","c7-smooth","c6-flow-upper"]]]},
 {name:"Full integration",focus:"Count block, rounds and form in one session; the full eight-count pattern.",
  goals:["I completed a session with a count block, rounds and the form together.","I can hold the full eight-count pattern on the count, changing lead at the marks.","I kept the integration day at moderate effort, resting on the count."],
  days:[["Every family, one rhythm","Full count",["c9-hold","c9-count-full","c9-intent"],"The full count: every family in one eight-count rhythm."],
   ["Easy count","Easy review",["c9-count-base","c8-breath","c7-mobility"]],
   ["Count, rounds, form","Full integration",["c9-count-full","c9-intent","c9-form-tired"],"Everything together, 40 minutes, still at 'short sentences'."],
   ["Count and strength","Count & strength",["c9-count-hands","c7-cue-mixed","c6-strength-2","c6-strength-1"]],
   ["Integration day","Full integration",["c9-count-full","c9-intent","c9-form-tired"],"Test-style: the whole programme in one session."],
   ["Easy flow","Easy flow",["c7-mobility","c9-hold","c8-breath","c6-flow-hips"]]]},
 {name:"Taper",focus:"Less volume, more rest, crisp technique.",
  goals:["I kept this week lighter: fewer repetitions, more rest.","My crisp technique stayed exact with full rests between.","I let the lighter week feel easy without adding extra work."],
  days:[["Fewer, sharper","Taper",["c9-crisp","c9-count-base","c8-breath"],"A deliberately lighter week. Sharpen; don't add."],
   ["Easy review","Easy review",["c9-crisp","c7-smooth","c9-hold","c7-mobility"]],
   ["Crisp and calm","Taper",["c9-crisp","c9-count-hands","c7-form"],"Light volume, exact technique, full rests."],
   ["Light strength","Taper & strength",["c9-crisp","c7-cue-intercept","c6-flow-hips","c6-strength-1"]],
   ["Light intent","Taper self-check",["c9-crisp","c9-intent","c9-selfcheck","c8-breath"],"One round block with intent, then rest."],
   ["Easy flow","Easy flow",["c7-mobility","c9-crisp","c8-breath","c6-flow-upper"]]]},
 {name:"The strongest week",focus:"The programme's strongest week, still 30–40 minutes a session: the full count, long rounds with intent, the form when tired.",
  goals:["I completed the programme's strongest week within the time cap.","My form after long rounds came from memory.","I listened to readiness each day and used the gentle option when needed."],
  days:[["The strongest week","Full count & long rounds",["c9-hold","c9-count-full","c9-intent-d"],"The strongest week of the whole programme, inside the same time cap. Rest on the count whenever you need."],
   ["Easy count","Easy review",["c9-count-base","c9-crisp","c7-mobility"]],
   ["Everything, steady","Peak integration",["c9-count-full","c9-intent-d","c9-form-tired"],"Peak integration: the count, long rounds with intent, the form."],
   ["Strong and steady","Rounds & strength",["c9-intent-d","c7-cue-menu","c6-strength-1","c6-strength-2"]],
   ["The whole line","Peak integration",["c9-count-full","c9-intent-d","c9-form-tired"],"Test-style: the strongest session, done calmly."],
   ["Easy flow","Easy flow",["c7-mobility","c9-hold","c8-breath","c6-flow-hips"]]]},
 {name:"Recovery and trial · Steady Count",focus:"An intentionally light week, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Steady Count trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Recovery is training","Recovery",["c8-recovery","c9-hold","c7-smooth","c7-mobility"]],
   ["Easy count","Recovery",["c9-count-base","c8-recovery","c6-flow-hips"]],
   ["Light intent","Recovery",["c9-crisp","c9-intent","c8-breath"]],
   ["Calm before the trial","Recovery",["c8-recovery","c9-crisp","c7-cue-intro","c6-flow-upper"]],
   ["Trial: Steady Count","Chapter trial",["c9-trial-count","c9-trial-form","c9-trial-rounds"],"The chapter trial: the long count, the full form and two rounds with intent. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["c7-mobility","c8-recovery","c8-breath","c6-flow-hips"]]]},
]};
