import {makeDrills,type ChapterSpec} from "./build";
import type {CueCall} from "../training";

// Chapter 7 · The Lantern Form + timing. A four-section solo form with turns and elbows,
// and bell-cued reactions (randomised calls on the existing audio clock, shown on screen too).
// Written for a left-foot lead; on a right-foot lead mirror every left and right.
export const LANTERN_FORM = {
 tempo:48,
 sections:[
  {name:"Section 1 · opening and hands",counts:"1–20",moves:["bow","left foot out to hip width; open hands rise to chest height and close","rear foot back into stance","guard with a sharp breath out","jab","cross","lead hook","guard reset","step forward","rear horizontal elbow","lead upward elbow","rear uppercut","high cover","hold the cover","step back","jab","cross","rear-hand parry","jab","zanshin"]},
  {name:"Section 2 · turns",counts:"21–40",moves:["pivot left a quarter turn on the front foot","jab","cross","slip right","cross","pivot back to the front","pivot right a quarter turn","jab","cross","lead hook","pivot back to the front","step back","roll down","roll up","lead hook","cross","step left","step right","high cover","zanshin"]},
  {name:"Section 3 · low line",counts:"41–60",moves:["lead check","set down","cross","rear knee to chamber","low round kick","back to chamber","set down in stance","guard reset","rear foot steps up behind","lead knee chambers across","low side kick","re-chamber","set down in stance","jab","cross","slip right","cross","lead hook","step back","zanshin"]},
  {name:"Section 4 · the return",counts:"61–80",moves:["lead knee to chamber","low front push kick","re-chamber","set down forward in stance","jab","cross","lead hook","rear horizontal elbow","rear knee strike, hands pulling down","set down in stance","high cover","step back","jab","cross","rear knee to chamber","low round kick with a kiai","return and set down in stance","zanshin","front foot back to hip width, fists at the belt","feet together, bow"]},
 ],
} as const;
const counted = (i:number,from:number,to?:number) => LANTERN_FORM.sections[i].moves.slice(from,to).map((m,n)=>`${m} (${i*20+from+n+1})`).join(", ");
const call = (call:string,answer:string,tone:CueCall["tone"]):CueCall => ({call,answer,tone});
const TONES = "High ping, low knock and double ping are different calls; each also flashes on screen, so the drill works with sound off.";

const drills = makeDrills(7,{
 "c7-warm":{name:"Turns and pivots warm-up",family:"Preparation",timing:"warmup",cue:"Ankles that turn, hips that follow.",
  steps:["First 30 seconds: clear your space (about 2 × 2 metres, more if you have it), support within reach, and pick a point on each of three walls: front, left and right.","Next 2 minutes: march gently, then ankle circles and slow ankle rocks over the toes, holding your support. Breathing rises a little.","Next 90 seconds: slow hip circles, trunk turns, then 4 slow quarter-turn pivots on the front foot (left, back, right, back) and 5 half-range jabs per hand.","Final minute: feet together, a small bow to the front. Step into stance and raise the guard with one sharp breath out. One breath of stillness. Practice begins."],
  checks:["My ankles and hips turn freely.","My pivots kept the feet apart and never crossed."],
  supported:"Hold your support for the ankle work and make the pivots small.",
  seated:"Seated ankle circles, trunk turns and knee swivels, then a seated bow and guard.",
  avoid:"No fast spins, no bouncing. Stop with ankle, knee or hip pain.",sources:["aaos"]},
 "c7-cool":{name:"Ankles, hips and breath",family:"Finish",timing:"cooldown",cue:"Turn the volume down slowly.",
  steps:["First 2 minutes: walk slowly in a small circle one way, then the other, shaking out the arms.","Next 2 minutes: calf stretch on the wall, a gentle hip-flexor stretch, and a slow standing trunk rotation with hands on your support.","Final minute: breathe in for 4, out for 6. Name one section that flowed and one count to revisit.","Feet together, a small bow. Practice ends."],
  checks:["My breathing slowed before I finished.","I can name one section that flowed."],
  supported:"Use your support for every stretch.",
  seated:"Seated calf and hip stretches, seated trunk rotation, slow breathing and a seated bow.",
  avoid:"Mild stretch only.",sources:["nhs-flex"]},
 "c7-elbows":{name:"Elbows: horizontal and upward",family:"Elbows",cue:"Close range. Short path. Sharp end.",
  steps:["Rear horizontal elbow: from guard, turn the rear heel and hip as for the cross while the rear elbow lifts to shoulder height and sweeps across in front of you, forearm level, fist near your own ear. It travels no further than your centre line.","Lead upward elbow: soften the knees, then drive the lead elbow up in front of your face, forearm vertical, a short rise.","Every elbow ends with both hands back in guard. Elbows are close-range tools: compact, with no wind-up. Breathe out sharply on each.","Round 1: rear horizontal elbows, about 5. Round 2: lead upward elbows. Round 3: alternate them on the other lead."],
  checks:["Each elbow stays compact and ends with the guard home.","The hip turns with the horizontal elbow."],
  supported:"Feet planted beside your support, slow half-range elbows.",
  seated:"Seated horizontal and upward elbows with a small trunk turn.",
  avoid:"Never strike anything with an elbow. No wild swings, no shoulder pain."},
 "c7-pivots":{name:"Quarter-turn pivots",family:"Footwork",cue:"Turn the world, not your feet into a knot.",
  steps:["Pivot left: turn on the ball of the front foot and swing the rear foot a quarter-circle behind you until you face 90° left in a full stance. The feet never cross.","Pivot right: the same front-foot pivot with the rear foot swinging the other way, until you face 90° right.","After each pivot: guard up, eyes on the point of that wall, one breath. Then pivot back to the front.","Round 1: left pivots and back. Round 2: right. Round 3: left, back, right, back, with a jab at each new direction."],
  checks:["Every pivot ends in a full stance with the feet apart.","My eyes find the new point before I strike."],
  supported:"Hold your support and make each pivot an eighth of a turn.",
  seated:"Swivel the knees and trunk a quarter turn each way in the chair.",
  avoid:"No spinning, no fast turns, no turning on a planted heel.",sources:["boxing-club"]},
 "c7-sec1":{name:"Lantern Form · section 1",family:"Lantern Form",cue:"Light it slowly. Let every count land.",
  steps:[`Opening: ${counted(0,0,4)}.`,`Hands and elbows: ${counted(0,4,14)}.`,`Return: ${counted(0,14)}.`,"Round 1: walk through it slowly, saying the counts. Round 2: stop wherever you need to recall. Round 3: as smoothly as stays clean."],
  checks:["I perform counts 1–20 in order, pausing to recall if needed.","My elbows stay compact inside the form."],
  supported:"Replace the steps with weight shifts and keep your support near.",
  seated:"Seated section 1: every hand technique at chest height, foot taps on the step counts.",
  avoid:"No speed yet; elbows never strike anything.",sources:["kata-balance"]},
 "c7-sec2":{name:"Lantern Form · section 2",family:"Lantern Form",cue:"Turn, find them, answer.",
  steps:[`Left turn: ${counted(1,0,6)}.`,`Right turn: ${counted(1,6,11)}.`,`Roll and return: ${counted(1,11)}.`,"Rounds as in section 1. After every pivot, find the point on that wall before you strike. Pivots stay a quarter turn; the feet never cross."],
  checks:["My turns end in a full stance without crossing my feet.","The roll bends my knees with a long back."],
  supported:"Smaller pivots holding your support; the roll as a small knee bend.",
  seated:"Seated section 2 with knee-and-trunk swivels for the turns and a seated U for the roll.",
  avoid:"No fast turns or fast head movement. Stop if dizzy.",sources:["boxing-club","kata-balance"]},
 "c7-sec3":{name:"Lantern Form · section 3",family:"Lantern Form",cue:"The low line. Quiet, exact, balanced.",
  steps:[`Check and round kick: ${counted(2,0,8)}.`,`Side kick: ${counted(2,8,13)}.`,`Hands and exit: ${counted(2,13)}.`,"Rounds as before, with your support beside you for counts 41–53. Every kick stays at or below hip height and returns to chamber before it lands."],
  checks:["Every kick returns to chamber, then stance.","My balance holds through the check and both kicks, with support if needed."],
  supported:"Hand on your support for the whole kicking part; smaller kicks.",
  seated:"Seated section 3: knee lifts and extensions for the kicks, seated strikes.",
  avoid:"No kicks above the hip, no hopping, no locked knees.",sources:["kicks","kata-balance"]},
 "c7-sec4":{name:"Lantern Form · section 4",family:"Lantern Form",cue:"Bring everything home.",
  steps:[`Kick and hands: ${counted(3,0,8)}.`,`Knee and cover: ${counted(3,8,14)}.`,`The finish: ${counted(3,14)}.`,"Rounds as before, support beside you for the kicks and the knee. The kiai on count 76 can be a short shout or a silent sharp breath."],
  checks:["I perform counts 61–80 in order.","The form ends in stillness and a calm bow."],
  supported:"Hand on your support for counts 61–64 and 69–77.",
  seated:"Seated section 4 with seated knee lifts and extensions.",
  avoid:"No kicks above the hip, no jumping knees.",sources:["kicks","kata-balance"]},
 "c7-count-12":{name:"Sections 1–2 on the count",family:"Lantern Form",format:"E",tempo:48,cue:"The count carries you. You carry the form.",
  steps:["Slow run: sections 1 and 2 (counts 1–40) at your own pace, pausing to recall whenever needed.","Review: rebuild your stance and note where you paused.","Count-tempo run: the same 40 counts on the bell's steady count, one move per count. If you lose the count, hold your guard and rejoin at the next section.","The count can be slowed or quickened with the tempo control; start slower than you think."],
  checks:["I stayed on the count for most of both sections.","When I lost the count I held my guard and rejoined calmly."],
  supported:"Run one section per run, with your support near for the turns.",
  seated:"The seated sections on the count.",
  avoid:"The count is a guide, not a race.",sources:["kata-balance"]},
 "c7-count-123":{name:"Sections 1–3 on the count",family:"Lantern Form",format:"E",minutes:10,tempo:48,cue:"Three sections, one breath each.",
  steps:["Slow run: sections 1–3 (counts 1–60), pausing to recall whenever needed.","Review: rebuild your stance and name the count where you hesitated most.","Count-tempo run: counts 1–60 on the bell's count. Rebuild your stance at counts 20 and 40.","Keep your support near for section 3's kicks; using it is part of the form."],
  checks:["I connected three sections on the count.","My stance was rebuilt at each section end."],
  supported:"Run the sections with a pause between and support for the kicks.",
  seated:"The seated version of sections 1–3 on the count.",
  avoid:"No kicks above the hip. The count is a guide.",sources:["kata-balance"]},
 "c7-tempo":{name:"Tempo ladder for the form",family:"Lantern Form",format:"E",minutes:10,tempo:44,cue:"Slow shows the shape. The count shows the rhythm.",
  steps:["Slow run: sections 1–3 very slowly, almost a moving meditation, each move held for a breath.","Review: shake out and rebuild your stance.","Count-tempo run: sections 1–3 on a slightly slower count than usual. Smooth tempo (no stops, natural speed) is practised in its own block.","Every tempo keeps the same shapes: compact elbows, low kicks, full stances after turns."],
  checks:["The shapes stayed the same at both tempos.","My stance was full after every turn."],
  supported:"Sections one at a time with support near.",
  seated:"The seated form at both tempos.",
  avoid:"No speeding up past control.",sources:["kata-balance","focus"]},
 "c7-smooth":{name:"Smooth: the form without stops",family:"Lantern Form",format:"B",cue:"Water, not a list of instructions.",
  steps:["Smooth tempo: one section per round, flowing from move to move at a natural speed with no stops except the zanshin counts.","Round 1: section 1. Round 2: section 2. Round 3: section 3. Round 4: section 4, or section 1 again before you have learned section 4.","If you stall, go back to the start of that section rather than skipping ahead.","Smooth is not fast: every strike still stops short of a straight elbow, every kick returns to chamber."],
  checks:["Each section flowed without stopping to remember.","Smooth never became sloppy: shapes stayed exact."],
  supported:"Smooth sections with your support near for the kicks.",
  seated:"Smooth seated sections.",
  avoid:"No speed for its own sake.",sources:["kata-balance"]},
 "c7-form":{name:"The Lantern Form · whole",family:"Lantern Form",format:"E",minutes:10,tempo:48,cue:"Eighty counts. One lantern, lit from the first bow to the last.",
  steps:["Slow run: the whole form, counts 1–80, at your own pace. Pause to recall whenever needed; rebuild your stance at counts 20, 40 and 60.","Review: shake out, breathe, and name one count to sharpen.","Count-tempo run: the whole form on the bell's count. If you lose it, hold your guard and rejoin at the next section.","Kiai on count 76, or a silent breath. Support within reach for every kick."],
  checks:["I completed the whole form in order.","Turns kept my feet apart and elbows stayed compact."],
  supported:"Run the form section by section with a pause between and support for the kicks.",
  seated:"The seated Lantern Form: hands and elbows at chest height, foot taps for steps and turns, seated knee extensions for kicks.",
  avoid:"No kicks above the hip, no fast turns. The count is a guide.",sources:["kata-balance","focus"]},
 "c7-cue-intro":{name:"Answer the bell",family:"Cues",format:"F",cueGap:[4,7],cues:[call("1-2","Throw a 1-2","high"),call("Step back","Step back out, guard up","low")],cue:"Wait in stillness. Answer once. Come home.",
  steps:["Two calls this week. High ping: throw a 1-2. Low knock: step back out, guard up. "+TONES,"Between calls, wait in your stance, relaxed and still, eyes on your point. Do not guess: answer only the call you hear or see.","Every answer ends with your guard home. Then wait again. Calls come every 4–7 seconds.","Rounds 1 and 3 on your usual lead, 2 and 4 on the other. In the review, rate yourself: how many answers were the right technique, cleanly?"],
  checks:["I answered each call once with the right technique.","My guard came home before the next call."],
  supported:"Answer with the hands only, feet planted beside your support; a weight shift for 'step back'.",
  seated:"Seated answers: a seated 1-2, or drawing the feet back and lifting the guard.",
  avoid:"Accuracy before speed. No lunging at the call.",sources:["practice-order","jkd"]},
 "c7-cue-defense":{name:"Defensive answers",family:"Cues",format:"F",cueGap:[4,6],cues:[call("Parry-1","Parry, then jab","high"),call("Slip-2","Slip, then cross","low"),call("Roll","Roll under, rise in guard","double")],cue:"The bell attacks. You answer.",
  steps:["Three calls. High ping: parry, then jab. Low knock: slip, then cross. Double ping: roll under, rise in guard. "+TONES,"Wait relaxed in stance between calls. Picture the strike each call represents arriving at you.","Every answer returns to centre and guard. Head movement stays slow and small.","Rounds 1 and 3 usual lead, 2 and 4 other lead. Review: rate your accuracy honestly."],
  checks:["My defenses were small and returned to centre.","I answered the call I heard, not the one I expected."],
  supported:"Answer with small leans and parries beside your support.",
  seated:"Seated parries and leans with a seated counter.",
  avoid:"Slow head movement only. Stop if dizzy.",sources:["practice-order","boxing-club"]},
 "c7-cue-intercept":{name:"Intercept",family:"Cues",format:"F",cueGap:[4,6],cues:[call("Stop-hit","Jab from stillness","high"),call("Cover","High cover, then 1-2","low"),call("Stop-kick","Low side step-kick","double")],cue:"Hit the step before it lands.",
  steps:["The bell is your opponent stepping in. High ping: stop-hit, a jab from complete stillness with no wind-up. Double ping: stop-kick, a low side step-kick at knee height. Low knock: they got there first, so cover, then 1-2. "+TONES,"This is the heart of Jeet Kune Do: meet the attack as it starts. Stillness between calls makes the answer fast; relaxation, not force.","Every answer ends in guard. Support within reach for the stop-kick.","Rounds 1 and 3 usual lead, 2 and 4 other lead. Review: did any answer have a wind-up?"],
  checks:["My stop-hits started from stillness with no tell.","The stop-kick stayed low and came back to stance."],
  supported:"Answer the kick call with a supported chamber and low press; hands-only for the rest.",
  seated:"Seated jab from stillness, seated cover and a seated low heel press.",
  avoid:"No kicks above the hip, no lunging. Accuracy first.",sources:["jkd","practice-order"]},
 "c7-cue-mixed":{name:"Strike and kick answers",family:"Cues",format:"F",cueGap:[4,7],cues:[call("1-2","Throw a 1-2","high"),call("Check","Check, land, cross","low"),call("1-2-kick","1-2, low round kick","double")],cue:"Hands, shin, hands-and-kick. Choose nothing; just answer.",
  steps:["High ping: 1-2. Low knock: check, land, cross. Double ping: 1-2 into a low round kick. "+TONES,"Wait in your stance between calls. After a kick, rebuild your stance before the next call can catch you.","Rounds 1 and 3 usual lead, 2 and 4 other lead.","Support within reach. Review: rate your accuracy and your balance after kicks."],
  checks:["My balance was steady after every kick answer.","Each answer was the right one, cleanly done."],
  supported:"Kick answers with a hand on your support; or hands-only answers.",
  seated:"Seated answers with knee lifts for the check and the kick.",
  avoid:"No kicks above the hip, no hopping, no rushing.",sources:["practice-order","kicks"]},
 "c7-cue-menu":{name:"Cues with the combination menu",family:"Cues",format:"F",cueGap:[5,8],cues:[call("Hands","Any hand combination","high"),call("Defend","Any defense-counter pair","low"),call("Kick","Any punch-kick link","double")],cue:"The bell asks a question. Your answer is your own.",
  steps:["High ping: any hand combination from the menu. Low knock: any defense-counter pair. Double ping: any punch-kick link. "+TONES,"Choose your answer in the moment and vary it: the same call should not get the same answer twice in a row.","Every answer ends in guard and a breath. Calls come every 5–8 seconds.","Rounds 1 and 3 usual lead, 2 and 4 other lead. Review: did you vary your answers?"],
  checks:["I varied my answers instead of repeating one.","Every answer ended with my guard home."],
  supported:"Hands-only answers, or kicks with your support.",
  seated:"Seated answers from the seated menu.",
  avoid:"No kicks above the hip. Control before speed.",sources:["practice-order","imagery"]},
 "c7-mobility":{name:"Mobility for turns",family:"Mobility",cue:"Turns are made in the ankles and the upper back.",
  steps:["Round 1: ankle rocks over the toes and slow ankle circles, holding your support.","Round 2: seated or standing trunk rotations, then an open-book rotation at a wall.","Round 3: slow pivots, an eighth of a turn each way, feeling the ball of the foot turn.","Rest between rounds. Recovery, not a workout."],
  checks:["Every movement stayed easy.","My turns feel freer than at the start."],
  supported:"Hold your support for every round.",seated:"Seated ankle circles, seated rotations, knee swivels.",
  avoid:"No forced twists.",sources:["nhs-flex","nhs-sitting"]},
 "c7-selfcheck":{name:"Form and timing self-check",family:"Self-check",cue:"Where does the lantern flicker?",
  steps:["Round 1: this week's section or the whole form, slowly. Note where you paused to remember.","Round 2: that part three times.","Round 3: a short cue set or this week's elbow or pivot drill, checking its form points.","Review minute: one part that is yours and one to repeat. Self-recording is optional and stays on your device."],
  checks:["I found the count where I hesitate most.","I repeated that part instead of the whole form."],
  supported:"Check with support near.",seated:"Check the seated form.",
  avoid:"No extra rounds.",sources:["kata-balance"]},
 "c7-trial-turns":{name:"Trial · turns and elbows",family:"Chapter trial",format:"B",cue:"Turn clean. Strike close.",
  steps:["Round 1: section 2 at smooth tempo. Watch your feet on every pivot.","Round 2: section 1 at smooth tempo. Watch your elbows.","Round 3: four quarter-turn pivots with a 1-2 at each wall. Round 4: elbows, both sides, slowly.","Mark the checks honestly. A 'not yet' means repeat a week; it never blocks the story."],
  checks:["Turns happen without crossing my feet.","Elbows stay compact."],
  supported:"Smaller pivots with support; half-range elbows.",seated:"Seated swivels and elbows.",
  avoid:"No fast turns.",sources:["boxing-club"]},
 "c7-trial-form":{name:"Trial · the Lantern Form, two tempos",family:"Chapter trial",format:"E",minutes:10,tempo:48,cue:"From memory. Slow, then on the count.",
  steps:["Slow run: the whole Lantern Form from memory. If you forget, hold your guard, breathe and continue from the next count you remember.","Review: rebuild your stance.","Count-tempo run: the whole form on the bell's count.","Mark the checks honestly."],
  checks:["Sections connect without pausing to remember.","My stance is rebuilt at each section end."],
  supported:"Run it section by section with support for the kicks.",seated:"The seated form at both tempos.",
  avoid:"No kicks above the hip; the count is a guide.",sources:["kata-balance"]},
 "c7-trial-cues":{name:"Trial · cue-reaction set",family:"Chapter trial",format:"F",cueGap:[4,7],cues:[call("1-2","Throw a 1-2","high"),call("Slip-2","Slip, then cross","low"),call("Stop-kick","Low side step-kick","double")],cue:"Hear it, answer it, come home.",
  steps:["High ping: 1-2. Low knock: slip, then cross. Double ping: low side step-kick. "+TONES,"Answer each call once and return to guard. Count your clean answers in round 4.","Rounds 1 and 3 usual lead, 2 and 4 other lead.","Self-rate your accuracy: write the round 4 count in your note if you like. It is a record, not a score."],
  checks:["I rated my accuracy honestly.","Every answer returned to guard before the next call."],
  supported:"Hands-only answers or supported kicks.",seated:"Seated answers.",
  avoid:"Accuracy before speed.",sources:["practice-order"]},
});

export const CHAPTER_7:ChapterSpec = {chapter:7,warm:"c7-warm",cool:"c7-cool",drills,weeks:[
 {name:"Section 1 and the elbows",focus:"Compact horizontal and upward elbows; the Lantern Form's opening section.",
  goals:["I can throw compact horizontal and upward elbows with the guard returning.","I can perform Lantern Form section 1 (counts 1–20) in order, pausing to recall if needed.","I kept every elbow short and controlled, never a wild swing."],
  days:[["Light the lantern","Elbows & section 1",["c7-elbows","c7-sec1","c7-sec1","c7-elbows","c6-form"],"A new form begins, and the closest-range tools you have."],
   ["Easy review","Easy review",["c7-elbows","c6-form","c5-set","c7-mobility"]],
   ["Section 1 and rounds","Section 1 volume",["c7-sec1","c7-elbows","c7-sec1","c5-rounds"],"Main volume: the new section, then rounds that use the elbows."],
   ["Elbows and strength","Elbows & strength",["c7-sec1","c7-elbows","c5-punch-kick","c6-form","c6-strength-1"]],
   ["Check section 1","Form self-check",["c7-sec1","c6-form","c5-rounds","c7-selfcheck"],"Where does section 1 stutter?"],
   ["Easy flow","Easy flow",["c7-mobility","c7-sec1","c6-form","c6-flow-hips"]]]},
 {name:"Section 2 and the count",focus:"Quarter-turn pivots and the form's turning section; practising to the bell's steady count.",
  goals:["I can pivot a quarter turn left and right without crossing my feet.","I can perform sections 1 and 2 on the bell's steady count.","When I lost the count I held my guard and rejoined at the next section."],
  days:[["Turn the world","Pivots & section 2",["c7-pivots","c7-sec2","c7-sec2","c7-sec1"],"A calmer week: turns, and your form begins to face every wall."],
   ["Easy review","Easy review",["c7-pivots","c7-sec1","c6-form","c7-mobility"]],
   ["On the count","Sections 1–2",["c7-pivots","c7-sec2","c7-count-12","c5-rounds"],"The steady count joins the form: one move per count."],
   ["Count and strength","Count & strength",["c7-sec2","c7-count-12","c7-elbows","c6-strength-2"]],
   ["Check the turns","Form self-check",["c7-sec1","c7-sec2","c7-count-12","c7-count-12","c7-selfcheck"],"Turns clean, count steady."],
   ["Easy flow","Easy flow",["c7-mobility","c7-pivots","c7-sec1","c6-flow-upper"]]]},
 {name:"Answer the bell",focus:"Cue drills begin: the bell calls, you answer with the assigned technique and return to guard.",
  goals:["I can answer the bell's cues with the assigned technique and return to guard.","I kept accuracy ahead of speed: one clean answer per call.","I used the on-screen cue whenever sound was off or unclear."],
  days:[["The bell calls","Cue drills",["c7-count-12","c7-cue-intro","c7-cue-intro","c7-sec2","c7-pivots"],"Cue blocks begin: random calls on the bell, shown on screen too. Wait in stillness; answer once."],
   ["Easy review","Easy review",["c7-sec1","c7-sec2","c7-cue-intro","c7-mobility"]],
   ["Stillness and answer","Cue volume",["c7-count-12","c7-cue-intro","c5-rounds","c7-cue-intro"],"Main volume: cue rounds between form and shadow rounds."],
   ["Cues and strength","Cues & strength",["c7-cue-intro","c7-sec2","c7-elbows","c5-set","c6-strength-1"]],
   ["Check the answers","Cue self-check",["c7-count-12","c7-cue-intro","c5-rounds","c7-selfcheck"],"Rate your answers honestly."],
   ["Easy flow","Easy flow",["c7-mobility","c7-sec1","c7-sec2","c6-flow-hips"]]]},
 {name:"Section 3 and defensive answers",focus:"The form's low-line section; the bell calls defenses.",
  goals:["I can perform section 3 with the check and low kicks controlled, using support as needed.","I can answer defensive cues (parry-1, slip-2, roll) at an easy pace.","I kept head movement slow and stopped if dizzy."],
  days:[["The low line","Section 3",["c7-sec2","c7-sec3","c7-sec3","c7-cue-defense","c4-kick-build"],"Kicks join the form; the bell starts attacking."],
   ["Easy review","Easy review",["c7-count-12","c7-sec3","c7-cue-intro","c7-mobility"]],
   ["Three sections","Sections 1–3 & cues",["c7-sec3","c7-cue-defense","c7-count-123","c7-cue-defense"],"Main volume: three sections on the count and defensive answers."],
   ["Defense and strength","Cues & strength",["c7-sec3","c7-cue-defense","c5-defense-in","c4-check","c6-strength-2"]],
   ["Check the low line","Form & rounds",["c7-count-123","c7-cue-defense","c5-rounds"],"Test-style: the form on the count, cues, rounds."],
   ["Easy flow","Easy flow",["c7-mobility","c7-sec3","c7-sec1","c6-flow-hips"]]]},
 {name:"Tempo and the intercept",focus:"The form at slow and count tempos plus a smooth tempo; intercepting cues with stop-hits and stop-kicks.",
  goals:["I can perform sections 1–3 at slow and count tempos.","I can intercept a cue with a jab from stillness or a low stop-kick.","I let the smooth tempo stay controlled instead of fast."],
  days:[["Three speeds","Tempo ladder",["c7-tempo","c7-smooth","c7-cue-intercept","c7-sec3"],"Slow shows the shape, the count shows the rhythm, smooth shows the flow."],
   ["Easy review","Easy review",["c7-sec1","c7-sec2","c7-cue-defense","c7-mobility"]],
   ["Meet it early","Tempo & intercept",["c7-tempo","c7-cue-intercept","c5-rounds"],"Main volume: the form at two tempos, then the art of the intercept."],
   ["Smooth and strong","Smooth & strength",["c7-smooth","c7-cue-intercept","c7-sec3","c5-punch-kick","c6-strength-1"]],
   ["Check the timing","Timing self-check",["c7-tempo","c7-cue-defense","c7-cue-intercept","c7-selfcheck"],"Rate the intercepts: any wind-ups?"],
   ["Easy flow","Easy flow",["c7-mobility","c7-smooth","c7-sec2","c6-flow-upper"]]]},
 {name:"Section 4 and mixed cues",focus:"The form's final section and the whole form slowly; the bell calls strikes and kicks.",
  goals:["I can perform section 4 and walk through the whole form slowly.","I can answer mixed strike and kick cues with balance after each kick.","I used support for the kicks whenever balance asked for it."],
  days:[["Bring it home","Section 4",["c7-sec3","c7-sec4","c7-sec4","c7-cue-mixed","c7-elbows"],"The last section. After today, the form has an ending."],
   ["Easy review","Easy review",["c7-smooth","c7-sec4","c7-cue-intercept","c7-mobility"]],
   ["The whole lantern","Whole form & cues",["c7-sec4","c7-form","c7-cue-mixed","c5-rounds"],"The chapter's peak: the whole form for the first time, then cues and rounds."],
   ["Cues and strength","Cues & strength",["c7-sec4","c7-cue-mixed","c7-smooth","c6-strength-2","c6-strength-1"]],
   ["Check the whole","Form self-check",["c7-form","c7-cue-mixed","c7-selfcheck","c5-rounds"],"Test-style: the whole form, cues and rounds."],
   ["Easy flow","Easy flow",["c7-mobility","c7-sec4","c7-smooth","c6-flow-hips"]]]},
 {name:"The whole form on the count",focus:"The full form at count tempo; the bell asks and you answer with your own combinations.",
  goals:["I can perform the whole Lantern Form on the bell's count.","I can answer menu cues with combinations I choose in the moment.","I chose different answers for the same call instead of repeating one."],
  days:[["Eighty counts","Whole form & menu cues",["c7-form","c7-cue-menu","c7-cue-menu","c7-sec4"],"The whole form on the count, and the bell asks open questions."],
   ["Easy review","Easy review",["c7-smooth","c7-sec4","c7-cue-mixed","c7-mobility"]],
   ["Your own answers","Form & tempo rounds",["c7-form","c7-cue-menu","c5-rounds-tempo"],"Main volume: the whole form, open cues, tempo rounds."],
   ["Answers and strength","Cues & strength",["c7-cue-menu","c7-smooth","c7-cue-intercept","c6-strength-1","c6-strength-2"]],
   ["Check the form","Form self-check",["c7-form","c7-cue-menu","c7-selfcheck","c7-cue-mixed"],"The whole form on the count, honestly reviewed."],
   ["Easy flow","Easy flow",["c7-mobility","c7-smooth","c7-sec1","c6-flow-upper"]]]},
 {name:"Trial week · Form",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Form trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and how accurate my cue answers were.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the opening","Light review",["c7-sec1","c7-sec2","c7-cue-intro","c7-mobility"]],
   ["Review the ending","Light review",["c7-sec3","c7-sec4","c7-smooth","c7-mobility"]],
   ["Calm count","Light review",["c7-form","c7-cue-menu","c7-cue-defense"]],
   ["Calm before the trial","Light review",["c7-smooth","c7-cue-mixed","c7-elbows","c6-strength-1"]],
   ["Trial: Form","Chapter trial",["c7-trial-turns","c7-trial-form","c7-trial-cues","c7-smooth","c7-mobility"],"The chapter trial: the full form at two tempos and a cue-reaction set. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["c7-mobility","c7-smooth","c6-form","c6-flow-hips"]]]},
]};
