import {makeDrills,type ChapterSpec} from "./build";
import {COMBINATION_MENU} from "./chapter-05";

// Chapter 10 · Practice for life. Consolidation, self-review of every family, designing your
// own session inside guardrails, and a plan you can keep after the programme ends.
const menu = `Menu: ${COMBINATION_MENU.join(" · ")}.`;
export const MAINTENANCE_PLANS = [
 {days:3,plan:"Monday long (rounds and the form) · Wednesday skill and conditioning · Saturday count block and review"},
 {days:4,plan:"The three-day plan plus an easy flow day (mobility, a smooth form run, breathing)"},
 {days:6,plan:"The weekly rhythm you know: new skill, easy review, rest Wednesday, long, skill and conditioning, test-style, easy flow"},
] as const;
const GUARDRAILS = "Guardrails: the preparation and cool-down stay as bookends; 4–6 blocks between them; 30–40 minutes in total; never past 'short sentences'.";

const drills = makeDrills(10,{
 "c10-warm":{name:"Your own warm-up",family:"Preparation",timing:"warmup",cue:"You know how to begin now.",
  steps:["First 30 seconds: set up the way you've learned: clear floor, support within reach, water near, a point to look at.","Next 2 minutes: choose the warm-up that suits today from any chapter: shoulders for a hands day, hips and ankles for a kick day, the small-space version when room is tight, breath and rhythm before long rounds.","Next 90 seconds: finish it with 30 seconds of half-speed shadow work of today's main skill.","Final minute: feet together, a small bow. Step into stance, raise the guard with one sharp breath out, and hold one breath of stillness. Practice begins."],
  checks:["I chose a warm-up that matched today's practice.","I opened with the bow and the ready."],
  supported:"Choose the supported version of the warm-up you picked.",
  seated:"Choose a seated warm-up from any chapter and end with a seated bow.",
  avoid:"Never skip preparation to fit in more blocks.",sources:["aaos"]},
 "c10-cool":{name:"Close the session",family:"Finish",timing:"cooldown",cue:"End the way a practitioner ends.",
  steps:["First 2 minutes: walk slowly and let the breathing come down.","Next 2 minutes: the stretches your body asked for today: calves, hips, chest, forearms. Mild tension only.","Final minute: breathe in for 4, out for 6. Name one thing you did well and one to keep working on. One line in your note is optional.","Feet together, a small bow. Practice ends. Nothing to make up, ever."],
  checks:["My breathing settled before I finished.","I can name one thing done well today."],
  supported:"Stretch with your support.",
  seated:"Seated stretches, slow breathing and a seated bow.",
  avoid:"Mild stretch only.",sources:["nhs-flex"]},
 "c10-review-hands":{name:"Review: hands",family:"Review",format:"B",cue:"The first strike you learned is still the most important.",
  steps:["Round 1: jabs from stillness, smooth tempo.","Round 2: crosses with the heel and hip turning, balance checked after each.","Round 3: the 1-2 and the 1-1-2 with a step-back exit, usual lead.","Round 4: the same on the other lead. Check the Hands trial points: guard home, soft elbows, feet apart, both leads alike."],
  checks:["My guard returned after every strike.","Both leads looked alike."],
  supported:"Half range, feet planted beside your support.",
  seated:"Seated hands review.",
  avoid:"Smooth, not maximal.",sources:["boxing-beginner"]},
 "c10-review-defense":{name:"Review: guard and defense",family:"Review",format:"B",cue:"Defense that comes home, every time.",
  steps:["Round 1: cover and parry, slowly.","Round 2: slips and rolls, slowly, both directions.","Round 3: slip-2 and parry-1, slow tempo.","Round 4: hook and uppercut with the guard returning, other lead. Check the Guard trial points."],
  checks:["Slips and rolls returned to centre over my stance.","Curved strikes stayed compact."],
  supported:"Small leans and parries beside your support.",
  seated:"Seated cover, parry, slip lean and seated curves.",
  avoid:"Slow head movement only. Stop if dizzy.",sources:["boxing-club"]},
 "c10-review-kicks":{name:"Review: kicks and balance",family:"Review",format:"B",cue:"Low, balanced, both sides. Still.",
  steps:["Round 1: chamber holds and front push kicks, lead leg.","Round 2: low round kicks, rear leg.","Round 3: low side step-kicks and checks.","Round 4: the weaker side of everything. Check the Kicks trial points: two-count chamber, return without hopping, nothing above the hip."],
  checks:["Every kick returned to chamber, then stance.","No kick went above hip height."],
  supported:"Hand on your support throughout.",
  seated:"Seated knee lifts and extensions.",
  avoid:"No height chasing, no hopping.",sources:["kicks","nhs-balance"]},
 "c10-review-combos":{name:"Review: combinations and the set",family:"Review",format:"B",cue:"Sentences you can still say clearly.",
  steps:["Round 1: the set sequence, usual lead.","Round 2: the set sequence, other lead.","Round 3: punch-kick links with balance after each kick.","Round 4: three combinations of your choice from the menu, each with an angle."],
  checks:["Guard home between combinations.","Feet never crossed."],
  supported:"Half range with support for the kicks.",
  seated:"The seated set.",
  avoid:"Rhythm, not speed.",sources:["boxing-beginner","kicks"]},
 "c10-selfreview-1":{name:"Self-review: foundations and hands",family:"Self-review",cue:"Look at the base you built two seasons ago.",
  steps:["Round 1: Foundations. Rebuild your stance and guard three times, then a four-direction step cycle with full stops. Compare with the Foundations checks.","Round 2: Hands. Jab, cross, 1-2 on both leads. Compare with the Hands trial checks.","Round 3: whichever of the two needed the most help, slowly.","Review minute: for each family, one thing that is solid and one to keep working on. Self-recording is optional and stays on your device."],
  checks:["I reviewed each family against its own checks.","I named one solid point and one to work on for each."],
  supported:"Review with your support near.",
  seated:"Review the seated versions and judge posture, paths and guard.",
  avoid:"Honest, not harsh. No extra rounds.",sources:["boxing-beginner"]},
 "c10-selfreview-2":{name:"Self-review: defense and kicks",family:"Self-review",cue:"What still comes home on its own?",
  steps:["Round 1: Guard and defense. Cover, parry, slip, roll, a defense-counter pair. Compare with the Guard trial checks.","Round 2: Kicks and balance. Chamber, front, round and side kicks, the check, both sides. Compare with the Kicks trial checks.","Round 3: the weaker family, slowly.","Review minute: one solid point and one to keep working on for each family."],
  checks:["I reviewed each family against its own checks.","I named one solid point and one to work on for each."],
  supported:"Review with your support near.",
  seated:"Review the seated versions.",
  avoid:"Slow head movement; low kicks. No extra rounds.",sources:["boxing-club","kicks"]},
 "c10-selfreview-3":{name:"Self-review: combinations, forms and the count",family:"Self-review",cue:"The long arc of your training, in three rounds.",
  steps:["Round 1: Combinations. The set sequence and one minute of menu work with angles. Compare with the Combinations trial checks.","Round 2: Forms. Form One's section B and the Lantern Form's section 3. Compare with the Anywhere and Form trial checks.","Round 3: the count: thirty seconds of the base count with your inner rhythm, then breath work. Compare with the Endurance and Steady Count checks.","Review minute: one solid point and one to keep working on for each."],
  checks:["I reviewed each family against its own checks.","I named one solid point and one to work on for each."],
  supported:"Review with your support near.",
  seated:"Review the seated versions.",
  avoid:"No extra rounds.",sources:["kata-balance"]},
 "c10-design":{name:"Design a session",family:"Your practice",cue:"A good session has a shape.",
  steps:[GUARDRAILS,"Shape: the skill that needs you most goes first, while you are fresh; rounds or a count block in the middle; the form, a cue set or conditioning near the end; easy movement last.","Round 1: practise the first block you'd choose for your own session. Round 2: a minute of the middle (a short round). Round 3: the section of a form you'd end with.","Review minute: say your session aloud or jot it in your note: warm-up, 4–6 blocks with their order and reason, cool-down. Today's 'your choice' blocks are where you'll run it."],
  checks:["I can describe a session that follows the guardrails.","I can give a reason for each block's place."],
  supported:"Design around the supported versions you use.",
  seated:"Design a seated session from the seated versions.",
  avoid:"A designed session never exceeds 40 minutes or 'short sentences'.",sources:["practice-order"]},
 "c10-choice-skill":{name:"Your choice: skill block",family:"Your practice",format:"B",cue:"Choose what needs you most.",
  steps:["Choose any technique from your library: the one that needs you most today. Open it in Techniques if you want its steps and checks.","Round 1 slow. Round 2 smooth. Round 3 crisp or on the other lead. Round 4 the weaker side.","Check its two form points in every round.","Next time you get this block, choose differently unless the same skill still needs you most."],
  checks:["I chose a skill for a reason.","I checked its form points every round."],
  supported:"Choose the supported version of the skill.",
  seated:"Choose the seated version of the skill.",
  avoid:"Choose from what you've learned; no new techniques without the programme's progression.",sources:["practice-order","focus"]},
 "c10-choice-round":{name:"Your choice: rounds",family:"Your practice",format:"C",cue:"Your intent. Your menu. Your rounds.",
  steps:["Three 2-minute rounds. Before each one, choose an intent: jab first, defend then answer, finish low, angles after everything, or one of your own.",menu,"Effort at 'short sentences'. Rests: walk, breathe out long.","In the last rest: did the rounds do what you designed them to do?"],
  checks:["Each round served the intent I chose.","Effort stayed at 'short sentences'."],
  supported:"Hands-only intents, kicks with your support.",
  seated:"Seated rounds.",
  avoid:"Stop for dizziness, chest discomfort or unusual breathlessness.",sources:["imagery","talk-test"]},
 "c10-choice-strength":{name:"Your choice: conditioning",family:"Your practice",format:"S",cue:"Strength you keep is strength you use.",exercises:["Lower body","Upper body","Core","Calves or balance"],
  steps:["Lower body: squat to chair, split squat or bridge, whichever you need.","Upper body: incline push-up at the incline you trained, or wall slides.","Core: dead bug, bird dog or side plank.","Calves or balance: calf raises or a supported single-leg hold. Stop every exercise 2–3 reps before it gets hard."],
  checks:["I chose one exercise for each slot.","Every exercise stopped 2–3 reps before it got hard."],
  supported:"Choose the supported versions you trained.",
  seated:"Choose the seated versions you trained.",
  avoid:"No failure sets, no maximal tests.",sources:["nhs-strength","rir","who"]},
 "c10-maintain":{name:"Maintenance plans",family:"Your practice",cue:"The best plan is the one you'll still be doing next year.",
  steps:[`Three ways to keep practising after this chapter. ${MAINTENANCE_PLANS.map(p=>`${p.days} days: ${p.plan}.`).join(" ")}`,"Every plan keeps a lighter review week every 6–8 weeks and the same guardrails: 30–40 minutes, never past 'short sentences', rest when something hurts.","Rounds 1–3: practise one block from the plan you are most likely to keep: a skill block, a short round, or a form section.","Review minute: choose your plan and the days it lives on. It can change any time; there is no penalty for a different week."],
  checks:["I chose a plan that fits my week.","I know where the lighter review weeks go."],
  supported:"Plans built from supported versions are equally valid.",
  seated:"A seated maintenance plan is equally valid.",
  avoid:"No plan should ask for more than 40 minutes a session.",sources:["who"]},
 "c10-teach":{name:"Teach it back",family:"Your practice",cue:"If you can explain it, you own it.",
  steps:["Choose one technique. Perform it very slowly while explaining it aloud, as if to a beginner: what it is for, how it starts, its two form checks, its supported version.","Round 2: a different technique from another family.","Round 3: the technique you find hardest to explain.","This is optional and equally rewarded if you'd rather practise silently. Your explanation is yours; the app never hears it."],
  checks:["I could explain why each step matters.","I explained the supported version as well as the standing one."],
  supported:"Explain while practising the supported version.",
  seated:"Explain while practising the seated version.",
  avoid:"Speak and move slowly. No speed.",sources:["focus"]},
 "c10-polish":{name:"Polish a favourite section",family:"Your practice",format:"B",cue:"Make one part of a form unmistakably yours.",
  steps:["Choose one section of Form One or the Lantern Form that you love.","Round 1: very slowly, every move held for a breath. Round 2: on your inner count. Round 3: smooth. Round 4: mirrored, on the other lead.","Polish one detail per round: the eyes, the breath, the stillness after a strike, the bow.","Self-recording is optional and stays on your device."],
  checks:["The section's shapes are exact at every tempo.","I polished one specific detail each round."],
  supported:"Polish with your support near for kicks.",
  seated:"Polish the seated version.",
  avoid:"Polish, not speed.",sources:["kata-balance"]},
 "c10-trial-design":{name:"Final trial · your designed session",family:"Chapter trial",format:"B",cue:"Your session. Your reasons.",
  steps:["Today's session is the one you designed: this block is its first skill block, the rounds and form follow.","Round 1 slow, round 2 smooth, round 3 the other lead, round 4 the weaker side of the skill you chose.",GUARDRAILS,"Mark the checks honestly. A written reflection is optional and counts exactly the same as no reflection."],
  checks:["My session followed the guardrails: preparation, 4–6 blocks, cool-down, 30–40 minutes.","I chose each block for a reason."],
  supported:"Your designed session from supported versions is equally valid.",
  seated:"Your designed seated session is equally valid.",
  avoid:"No extra rounds to prove anything.",sources:["practice-order"]},
 "c10-trial-form":{name:"Final trial · the full form",family:"Chapter trial",format:"E",minutes:10,tempo:48,cue:"From the first bow to the last.",
  steps:["Slow run: the whole Lantern Form from memory.","Review: rebuild your stance; three long breaths.","Count-tempo run on the bell's count.","If you forget a count, hold your guard and continue from the next one you remember. Mark the checks honestly."],
  checks:["The full form came from memory at both tempos.","Stance rebuilt at section ends, kicks low, elbows compact."],
  supported:"Section by section with support for the kicks.",
  seated:"The seated Lantern Form.",
  avoid:"No kicks above the hip. The count is a guide.",sources:["kata-balance"]},
});

export const CHAPTER_10:ChapterSpec = {chapter:10,warm:"c10-warm",cool:"c10-cool",drills,weeks:[
 {name:"Recovery and review",focus:"An intentionally easy week of light review of every family.",
  goals:["I reviewed every family lightly: hands, defense, kicks and combinations.","Everything stayed easy and familiar this week.","I noticed which family I have missed most."],
  days:[["Welcome back","Light review",["c10-review-hands","c10-review-defense","c7-smooth","c7-mobility"],"The last chapter starts easy. Everything familiar, nothing to prove."],
   ["Light kicks","Light review",["c10-review-kicks","c9-hold","c8-breath","c6-flow-hips"]],
   ["Light count","Light review",["c10-review-combos","c9-count-base","c8-recovery"]],
   ["Light hands and form","Light review",["c10-review-hands","c10-review-kicks","c6-form","c6-flow-upper"]],
   ["Light form","Light review",["c10-review-defense","c7-form","c8-breath"]],
   ["Easy flow","Easy flow",["c7-mobility","c8-recovery","c7-smooth","c6-flow-hips"]]]},
 {name:"Self-review",focus:"Review each family against its own checks and name what is solid and what needs work.",
  goals:["I reviewed each family against its own checks, honestly.","I can name my strongest family and the one that needs the most practice.","I recorded what I actually did, including the supported or seated versions."],
  days:[["The base you built","Self-review",["c10-selfreview-1","c10-review-hands","c10-selfreview-1","c7-mobility"],"Look back at your foundations and your hands with honest eyes."],
   ["Easy review","Easy review",["c10-review-defense","c10-review-kicks","c8-breath","c6-flow-hips"]],
   ["Defense and kicks","Self-review",["c10-selfreview-2","c10-review-defense","c10-selfreview-2","c10-review-kicks","c8-breath"],"What still comes home on its own?"],
   ["Combinations and strength","Self-review & strength",["c10-selfreview-3","c10-review-combos","c6-strength-1","c6-flow-upper"]],
   ["The long arc","Self-review",["c10-selfreview-3","c7-form","c5-rounds"],"Combinations, forms and the count: the long arc in one session."],
   ["Easy flow","Easy flow",["c7-mobility","c10-review-hands","c7-smooth","c6-flow-hips"]]]},
 {name:"Your own session",focus:"Design your own sessions inside guardrails: preparation, 4–6 blocks, cool-down, 30–40 minutes.",
  goals:["I followed the guardrails for a designed session: preparation, 4–6 blocks, cool-down, 30–40 minutes.","I chose my blocks for a reason: the skill that needs me first, rounds in the middle, form or conditioning last.","I kept my designed sessions at the same effort as the app's."],
  days:[["A session has a shape","Design",["c10-design","c10-choice-skill","c10-choice-skill","c10-choice-round"],"Learn the shape of a good session, then run the first one you design."],
   ["Easy choice","Easy review",["c10-choice-skill","c10-review-combos","c8-breath","c7-mobility"]],
   ["Your long day","Your session",["c10-choice-skill","c10-choice-round","c10-choice-skill","c10-choice-strength"],"Your long day, your choices, the app's guardrails."],
   ["Your skills and strength","Your session",["c10-choice-skill","c10-choice-skill","c7-cue-menu","c10-choice-strength","c6-flow-hips"]],
   ["Your test day","Your session",["c10-design","c10-choice-round","c7-form"],"Design, rounds, the form: a whole session you shaped."],
   ["Easy flow","Easy flow",["c7-mobility","c10-choice-skill","c7-smooth","c6-flow-upper"]]]},
 {name:"Maintenance plans",focus:"Templates for 3, 4 and 6 days a week, each with a lighter week every 6–8 weeks.",
  goals:["I chose a maintenance plan (3, 4 or 6 days a week) that fits my life.","I know which days of my plan are long, easy and rest.","I planned a lighter review week every 6–8 weeks."],
  days:[["A plan you'll keep","Maintenance",["c10-maintain","c10-choice-skill","c10-choice-skill","c7-mobility"],"The best plan is the one you will still be doing next year."],
   ["Easy review","Easy review",["c10-review-hands","c10-review-kicks","c8-breath","c6-flow-hips"]],
   ["A long day from your plan","Maintenance",["c10-maintain","c10-choice-round","c10-choice-skill","c10-choice-strength"],"Run the long day of the plan you chose."],
   ["Plan and strength","Maintenance & strength",["c10-maintain","c10-review-combos","c6-strength-2","c6-flow-upper"]],
   ["The count in your plan","Maintenance",["c10-design","c9-count-hands","c7-form"],"A count block and the form, the way your plan would place them."],
   ["Easy flow","Easy flow",["c7-mobility","c10-review-defense","c7-smooth","c6-flow-hips"]]]},
 {name:"Teach it back and polish",focus:"An optional teach-back reflection, and polishing a favourite form section until it is yours.",
  goals:["I explained one technique aloud in my own words, or chose to practise silently; both count the same.","I polished one favourite form section until it felt like mine.","I practised because I wanted to, not to earn anything."],
  days:[["If you can explain it","Teach & polish",["c10-teach","c10-polish","c10-polish","c7-mobility"],"Explain one technique aloud (optional) and polish a section of a form you love."],
   ["Easy review","Easy review",["c10-teach","c10-review-hands","c8-breath","c6-flow-hips"]],
   ["Polish and rounds","Polish",["c10-polish","c10-choice-round","c10-teach","c10-choice-skill"],"Polish, rounds, and another explanation if you want one."],
   ["Polish and strength","Polish & strength",["c10-polish","c10-choice-skill","c10-choice-strength","c6-flow-upper"]],
   ["Your form, your rounds","Polish",["c10-teach","c7-form","c10-choice-round"],"The whole form, then rounds of your own design."],
   ["Easy flow","Easy flow",["c7-mobility","c10-polish","c7-smooth","c6-flow-hips"]]]},
 {name:"Final trial · Lifelong",focus:"A lighter week, the final trial on Saturday (your own designed session plus the full form), then easy flow.",
  goals:["I completed the final trial at my level: my own designed session plus the full form.","I recorded honestly which checks I met; a reflection is optional and counts the same.","I chose how to keep practising: a maintenance plan, continuing practice, or replaying a chapter."],
  days:[["Review the beginning","Light review",["c10-review-hands","c10-review-defense","c10-polish","c7-mobility"]],
   ["Review the middle","Light review",["c10-review-kicks","c10-review-combos","c8-breath","c6-flow-hips"]],
   ["Design the trial","Light review",["c10-design","c10-choice-round","c10-polish"]],
   ["Calm before the trial","Light review",["c10-choice-skill","c10-teach","c10-choice-strength","c6-flow-upper"]],
   ["Final trial","Chapter trial",["c10-trial-design","c10-choice-round","c10-trial-form","c10-choice-strength"],"The final trial: your own designed session plus the full form. A written reflection is optional and counts the same."],
   ["Practice for life","Easy flow",["c7-mobility","c8-recovery","c7-smooth","c6-flow-hips"]]]},
]};
