import {makeDrills,type ChapterSpec} from "./build";

// Chapter 6 · Practice anywhere + Form One. Small, quiet and unfamiliar spaces; bodyweight
// strength; the first complete solo form, built only from Chapters 1–5.
// Form One is written for a left-foot lead; on a right-foot lead mirror every left and right.
export const FORM_ONE = {
 tempo:40,
 sections:[
  {name:"Section A · the straight line",counts:"1–18",moves:["bow","left foot out to hip width, fists at the belt","rear foot back into stance","guard rises with one sharp breath out","jab","cross","step forward","jab","jab","cross","rear-hand parry","jab","step back","step left","jab","cross","step right, back to centre","zanshin: guard, eyes forward, one breath"]},
  {name:"Section B · the curve and the kick",counts:"19–36",moves:["slip right","cross","lead hook","guard reset","rear knee rises to chamber","hold the chamber","set it down in stance","lead knee to chamber","low front push kick","re-chamber","set down in stance","high cover","jab","cross with a kiai (or a silent sharp breath)","zanshin","front foot draws back to hip width, fists at the belt","feet together, hands by your sides","bow"]},
 ],
} as const;

const drills = makeDrills(6,{
 "c6-warm":{name:"Small-space warm-up",family:"Preparation",timing:"warmup",cue:"One square metre. No noise. Fully warm.",
  steps:["First 30 seconds: find about 1 × 1 metre of non-slip floor (a corridor, a corner, beside a bed) and something stable within reach: a chair, a wall or a doorframe. Find your point.","Next 2 minutes: march in place on soft feet, rolling through the foot so it makes no sound. Add arm swings and shoulder circles. Breathing rises a little.","Next 90 seconds: ankle circles, hip circles, slow trunk turns, 6 quarter-squats with a hand on your support, then 5 silent half-range jabs per hand.","Final minute: feet together, a small bow. Step into stance and raise the guard with one breath out through the nose, silent. One breath of stillness. Practice begins."],
  checks:["I warmed up fully inside a small space without noise.","I opened with the bow and the ready."],
  supported:"Keep a hand on the wall or chair for everything below the waist.",
  seated:"Seated marches on soft feet, arm swings, trunk turns and a seated bow.",
  avoid:"No jumping, stamping or bouncing. Check the floor isn't slippery.",sources:["aaos"]},
 "c6-cool":{name:"Mobility flow down",family:"Finish",timing:"cooldown",cue:"Flow down the way you flowed up.",
  steps:["First 2 minutes: walk slowly or march softly in place; let the arms hang and the breathing slow.","Next 2 minutes: one slow flow, repeated: hip circles, a gentle split-stance hip-flexor stretch each side, a calf stretch on the wall, shoulder rolls, wrist circles.","Final minute: breathe in for 4, out for 6. Name one part of the form or one exercise that felt solid, and one to repeat.","Feet together, a small bow. Practice ends. Nothing to make up."],
  checks:["My breathing slowed before I finished.","Every stretch stayed at mild tension."],
  supported:"Use the wall or chair throughout.",
  seated:"A seated flow: ankle circles, seated knee hugs, shoulder rolls, wrist circles, slow breathing, a seated bow.",
  avoid:"No forced stretches.",sources:["nhs-flex"]},
 "c6-quiet":{name:"Quiet feet, small space",family:"Anywhere",cue:"A whole fight fits in one square metre.",
  steps:["Mark out about 1 × 1 metre and stay inside it for the whole block: stance, guard, small pivots in place, weight shifts instead of long steps.","Quiet feet: move by rolling through the foot and sliding, never stamping. Quiet breath: breathe out silently through the nose instead of a 'tss'.","Round 1: 1-2s, slips and rolls inside the square. Round 2: knee raises and low front kicks with your support, landing silently. Round 3: one run of the set sequence, compact.","If you touch the edge, reset to the centre. Small space is a skill: shorter steps, compact strikes."],
  checks:["I stayed inside my square with quiet feet.","Strikes and kicks stayed compact and controlled."],
  supported:"Keep a hand on the wall or chair and use weight shifts only.",
  seated:"Seated 1-2s, leans and knee lifts, all silent.",
  avoid:"No stamping, no strikes near walls or furniture (keep more than arm's length), no kicks near objects.",sources:["boxing-beginner"]},
 "c6-form-a":{name:"Form One · section A",family:"Form One",cue:"Every count lands. Every pause is alive.",
  steps:["Opening, counts 1–4: feet together, hands by your sides, eyes forward, bow (1). Left foot steps out to hip width, loose fists at the belt (2). Rear foot steps back into stance (3). Guard rises with one sharp breath out (4).","The straight line, counts 5–13: jab (5), cross (6), step forward (7), jab (8), jab (9), cross (10), rear-hand parry (11), jab (12), step back (13).","Sideways and home, counts 14–18: step left (14), jab (15), cross (16), step right back to centre (17), zanshin: guard up, eyes forward, one breath (18).","Round 1: walk through it slowly, saying the counts. Round 2: stop wherever you need to recall. Round 3: as smoothly as stays clean. On a right-foot lead, mirror every left and right."],
  checks:["I perform counts 1–18 in order, pausing to recall if needed.","Each step pair rebuilds my stance before the next strike."],
  supported:"Replace the steps with weight shifts and keep a hand near your support.",
  seated:"Seated section A: the bow, the guard and every strike at chest height; foot taps on the step counts.",
  avoid:"No speed yet. Strikes stay short of a straight elbow.",sources:["kata-balance","boxing-beginner"]},
 "c6-form-b":{name:"Form One · section B",family:"Form One",cue:"The curve, the knee, the kick, the bow.",
  steps:["The curve and the knee, counts 19–25: slip right (19), cross (20), lead hook (21), guard reset (22), rear knee rises to chamber (23), hold the chamber (24), set it down in stance (25).","The kick, counts 26–29: lead knee to chamber (26), low front push kick (27), re-chamber (28), set down in stance (29).","The finish, counts 30–36: high cover (30), jab (31), cross with a kiai: a short shout, or a silent sharp breath (32), zanshin (33), front foot draws back to hip width, fists at the belt (34), feet together, hands by your sides (35), bow (36).","Rounds as in section A. Keep your support beside you for counts 23–29; using it is part of the form, not a failure."],
  checks:["I perform counts 19–36 in order.","My balance holds through the knee and the kick, with support if needed."],
  supported:"Hand on the support for counts 23–29 and smaller knee lifts.",
  seated:"Seated section B: slip lean, strikes, seated knee lifts and a seated extension for the kick, then the bow.",
  avoid:"No kick above the hip, no hopping, no locked knee.",sources:["kata-balance","kicks"]},
 "c6-form":{name:"Form One · whole",family:"Form One",format:"E",tempo:40,cue:"Thirty-six counts. One unbroken story.",
  steps:["Stand at your mark facing your point. Slow run: all 36 counts at your own pace, pausing between counts as long as you need to recall the next move. Rebuild your stance at counts 18 and 33.","Review: shake out, rebuild your stance, and name the count where you hesitated.","Count-tempo run: the bell's steady count sets the pace, one move per count, holds and stillness included. If you lose the count, hold your guard and rejoin at the next section.","Every move lands and stops. Kiai on count 32, or a silent breath if you need quiet. Keep your support within reach for counts 23–29."],
  checks:["I completed Form One in order (pauses to recall are fine in the slow run).","My stance is rebuilt between sections and my balance holds through the kick."],
  supported:"Run the form section by section with a pause between, and your support beside you for the kick.",
  seated:"The seated form: upper-body moves at chest height with foot taps on the step counts and a seated knee extension for the kick.",
  avoid:"The count is a guide, not a race. No kicks above the hip.",sources:["kata-balance","focus"]},
 "c6-form-mirror":{name:"Form One · both sides",family:"Form One",format:"E",minutes:10,tempo:40,cue:"The weaker side is just the side you've visited less.",
  steps:["Slow run: Form One on your usual lead, then after a breath on the other lead, mirroring every left and right. Pause to recall whenever you need.","Review: which side hesitated, and at which count? Rebuild your stance.","Count-tempo run: once on each lead, on the bell's count.","If the mirrored side is unclear, run only section A mirrored this week. Support for the kick on both sides."],
  checks:["I can perform Form One on both leads in order.","My stance is rebuilt between sections on both sides."],
  supported:"Mirrored sections one at a time with the support beside you.",
  seated:"The seated form on both sides.",
  avoid:"No rushing the mirrored side. No kicks above the hip.",sources:["kata-balance"]},
 "c6-small-rounds":{name:"Small-space shadow rounds",family:"Anywhere",format:"C",cue:"Small square, big intent.",
  steps:["Rounds inside your 1 × 1 metre square: picture your opponent just outside it.","Use the combination menu with pivots and shifts instead of long steps. Quiet feet, silent exhales.","Round 1 hands and defense; round 2 add low kicks with your support near; round 3 your choice on the other lead.","Effort at 'short sentences'. Walk slowly around the square in the rests."],
  checks:["I stayed inside the square with quiet feet.","Guard home between combinations."],
  supported:"Work the first minute of each round, then walk with your guard up; kicks with support.",
  seated:"Seated rounds: strikes, leans and knee lifts on your own rhythm.",
  avoid:"No strikes near walls or furniture, no stamping, no high kicks.",sources:["imagery","talk-test"]},
 "c6-strength-1":{name:"Strength I",family:"Strength",format:"S",cue:"Strong enough to train for years.",exercises:["Squat to chair","Incline push-up","Glute bridge","Plank"],
  steps:["Squat to chair: sit back to touch the seat lightly and stand, chest up, knees following the toes. 8–12 slow reps.","Incline push-up: hands on a wall or a sturdy table, body straight; lower the chest toward the edge and press back. 6–12 reps.","Glute bridge: 10–12 reps with a 2-second squeeze at the top.","Plank: forearms on the floor, or hands on a table for an incline plank, body in one straight line, 15–30 seconds. Stop every exercise 2–3 reps before it gets hard. Progress by adding reps over the weeks, then by lowering the incline."],
  checks:["My form stayed the same from the first rep to the last.","I stopped each exercise with 2–3 good reps in reserve."],
  supported:"Higher seat for the squat, wall push-ups, standing hip extension at the chair, a standing wall plank.",
  seated:"Sit-to-stand with hand help, seated chest press against a wall, seated tall holds with the abdominals braced.",
  avoid:"No sets to failure, no breath-holding, no joint pain.",sources:["nhs-strength","who","rir"]},
 "c6-strength-2":{name:"Strength II",family:"Strength",format:"S",cue:"One leg at a time. Steady wins.",exercises:["Split squat · left forward","Split squat · right forward","Side plank","Calf raise"],
  steps:["Chair-supported split squat, left foot forward: hand on the chair, lower the back knee a short way straight down and rise. 6–10 reps.","The same with the right foot forward.","Side plank: knees bent or legs long, 15–25 seconds each side, switching halfway.","Calf raise: 12–15 slow raises holding the chair; single-leg if two legs are easy. Stop every exercise 2–3 reps before it gets hard."],
  checks:["The front knee follows the toes and the trunk stays upright.","I stopped each exercise with 2–3 good reps in reserve."],
  supported:"A shorter split stance and a smaller range, both hands on the chair; side plank as a wall lean.",
  seated:"Seated single-leg presses into the floor, seated side bends, seated heel raises.",
  avoid:"No deep lunges, no knee pain, no failure sets.",sources:["nhs-strength","rir"]},
 "c6-flow-hips":{name:"Mobility flow: hips and ankles",family:"Mobility",cue:"One movement melting into the next.",
  steps:["Flow, slowly, without stopping: ankle rocks forward and back, hip circles each direction, a small side-to-side weight shift in a wide stance.","Then a gentle split-stance hip-flexor stretch on each side and two knee hugs per leg, holding your support.","Repeat the flow in each round, a little smoother each time. Breathe out on every stretch.","Use it as a warm-up or cool-down anywhere: no mat, no equipment."],
  checks:["The flow stayed smooth and pain-free.","My hips and ankles feel freer afterwards."],
  supported:"The whole flow holding a chair, wall or doorframe.",
  seated:"Seated ankle circles, seated hip circles and seated knee hugs.",
  avoid:"No forcing range, no bouncing.",sources:["nhs-flex"]},
 "c6-flow-upper":{name:"Mobility flow: spine and wrists",family:"Mobility",cue:"Free spine, quiet wrists, loose shoulders.",
  steps:["Flow, slowly: cat-cow on hands and knees (or hands on a table), then 'thread the needle' (one arm slides under the body, turning the upper back), each side.","Wrist circles, then gentle wrist stretches with the palm on the floor or table, fingers forward and then back.","Shoulder rolls and an open-book rotation lying on your side or standing at a wall.","Repeat the flow each round. A useful warm-up or cool-down anywhere."],
  checks:["The flow stayed smooth and pain-free.","My spine and wrists feel freer afterwards."],
  supported:"Do every part standing with hands on a table or wall.",
  seated:"Seated arch-and-round, seated rotations, wrist circles and shoulder rolls.",
  avoid:"No weight on painful wrists; use fists or forearms instead. No forced twists.",sources:["nhs-flex"]},
 "c6-travel":{name:"Travel template: wall or doorframe",family:"Anywhere",format:"B",cue:"No chair? A wall is enough.",
  steps:["This is your template for hotel rooms, corridors and other people's homes: a wall or doorframe replaces the chair. Stand side-on to it with fingertips on the frame for balance.","Round 1: chamber holds and low front kicks with a hand on the doorframe. Round 2: incline push-ups against the wall.","Round 3: silent 1-2s, slips and rolls facing away from the wall, more than arm's length from anything. Round 4: Form One section A in place with small steps.","A travel day: small-space warm-up · this block · a small-space round · Form One · cool-down. No equipment, no noise, 30 minutes."],
  checks:["I used the wall or doorframe as safely as the chair.","Every strike and kick stayed well away from walls and objects."],
  supported:"Both hands on the doorframe for the kicks; wall push-ups with feet closer to the wall.",
  seated:"A seated travel version: seated strikes, seated knee lifts and seated Form One.",
  avoid:"Never strike or kick toward the wall. Check the doorframe is solid and the floor isn't slippery.",sources:["nhs-balance"]},
 "c6-selfcheck":{name:"Form self-check",family:"Self-check",cue:"Where does the story stutter?",
  steps:["Round 1: Form One (or this week's section) on your usual lead, slowly. Note any count where you paused to remember.","Round 2: only the part around that count, three times.","Round 3: this week's strength exercise or travel skill, checking its two form points.","Review minute: one part that is yours, one to repeat. Self-recording is optional and stays on your device."],
  checks:["I found the count where I hesitate most.","I repeated that part instead of the whole form."],
  supported:"Check with support beside you.",seated:"Check the seated form.",
  avoid:"No extra rounds.",sources:["kata-balance"]},
 "c6-trial-form":{name:"Trial · Form One from memory",family:"Chapter trial",format:"E",minutes:10,tempo:40,cue:"From memory. Two tempos. One bow.",
  steps:["Slow run: Form One from memory on your usual lead. If you forget, hold your guard, breathe, and continue from the next count you remember.","Review: rebuild your stance; note any count you skipped.","Count-tempo run: Form One on the bell's count.","Mark the checks honestly. A 'not yet' means repeat a week, without penalty, and never blocks the story."],
  checks:["Form One from memory at slow and count tempo.","My stance is rebuilt between sections and my balance holds through the kick."],
  supported:"Run the form with your support beside you for the kick counts.",seated:"Run the seated form at both tempos.",
  avoid:"No kicks above the hip. The count is a guide, not a race.",sources:["kata-balance"]},
 "c6-trial-strength":{name:"Trial · the strength block",family:"Chapter trial",format:"S",cue:"Consistent, not maximal.",exercises:["Squat to chair","Incline push-up","Glute bridge","Plank"],
  steps:["Squat to chair: 8–12 slow reps, the same depth every rep.","Incline push-up: 6–12 reps at the incline you trained, body straight.","Glute bridge: 10–12 reps with the squeeze at the top.","Plank: 15–30 seconds. This trial records consistent form, never a maximum: stop 2–3 reps before it gets hard."],
  checks:["The strength block was completed with consistent form.","Every exercise stopped 2–3 reps before failure."],
  supported:"Use the supported versions you trained.",seated:"Use the seated versions you trained.",
  avoid:"No maximal tests, no failure sets.",sources:["nhs-strength","rir"]},
});

export const CHAPTER_6:ChapterSpec = {chapter:6,warm:"c6-warm",cool:"c6-cool",drills,weeks:[
 {name:"Small space and section A",focus:"Train inside one square metre with quiet feet; learn Form One's opening and straight line.",
  goals:["I can practise inside a 1 × 1 metre square with quiet feet and compact strikes.","I can perform Form One section A (counts 1–18) in order, pausing to recall if needed.","I kept my practice quiet enough for a shared space."],
  days:[["One square metre","Small space & Form One A",["c6-quiet","c6-form-a","c6-form-a","c5-grammar"],"Practice anywhere begins: a small square, quiet feet, and the first section of your first form."],
   ["Easy review","Easy review",["c6-quiet","c5-set","c4-chamber","c5-mobility"]],
   ["The straight line","Form A & small rounds",["c6-quiet","c6-form-a","c6-small-rounds","c6-form-a"],"Rounds inside the square, then the form's opening again."],
   ["Quiet and strong","Form A & strength",["c6-form-a","c6-quiet","c5-defense-in","c5-strength"]],
   ["Check section A","Form self-check",["c6-quiet","c6-form-a","c6-small-rounds","c6-selfcheck"],"Find the count where you hesitate."],
   ["Easy flow","Easy flow",["f2-shift","c6-form-a","c6-quiet","c5-mobility"]]]},
 {name:"Section B and Strength I",focus:"Learn Form One's curve, knee and kick; the first bodyweight strength block.",
  goals:["I can perform Form One section B (counts 19–36), with support near for the kick.","I completed the Strength I block with steady form, stopping 2–3 reps short of hard.","I connected sections A and B at least once, slowly."],
  days:[["The curve and the kick","Form One B & strength",["c6-form-a","c6-form-b","c6-form-b","c6-quiet","c6-strength-1"],"The second half of the form, and strength to train for years."],
   ["Easy review","Easy review",["c6-quiet","c6-form-a","c5-set","c5-mobility"]],
   ["Both halves","Form & small rounds",["c6-form-a","c6-form-b","c6-small-rounds","c6-form-b"],"Main volume: both sections, with rounds in the middle."],
   ["Form and strength","Form & strength",["c6-form-b","c6-quiet","c5-punch-kick","c6-form-a","c6-strength-1"]],
   ["Check section B","Form self-check",["c6-form-a","c6-form-b","c6-small-rounds","c6-selfcheck"],"Where does the second half stutter?"],
   ["Easy flow","Easy flow",["f2-shift","c6-form-b","c6-form-a","c5-mobility"]]]},
 {name:"Form One whole and Strength II",focus:"Form One from bow to bow, slowly; single-leg strength with support.",
  goals:["I can perform Form One as a whole, slowly, from start to finish.","I completed Strength II with steady form on both legs.","I rebuilt my stance at the section ends instead of rushing."],
  days:[["Bow to bow","Form One whole",["c6-form-a","c6-form-b","c6-form","c6-form","c6-strength-2"],"Form blocks begin: a slow run, a review, then a run on the bell's count."],
   ["Easy review","Easy review",["c6-quiet","c6-form","c5-set","c5-mobility"]],
   ["One unbroken story","Form volume",["c6-form-a","c6-form-b","c6-form","c6-small-rounds","c6-form"],"The chapter's fullest days: the whole form, rounds, the whole form again."],
   ["Strength day","Form & strength",["c6-form","c6-quiet","c5-punch-kick","c6-strength-1","c6-strength-2"]],
   ["Check the whole","Form self-check",["c6-form","c6-small-rounds","c6-form","c6-selfcheck","c6-strength-2"],"Test-style: the whole form twice and an honest look."],
   ["Easy flow","Easy flow",["f2-shift","c6-form","c6-quiet","c5-mobility"]]]},
 {name:"Mobility flows and the count",focus:"Mobility flows as warm-up and cool-down; Form One on the bell's steady count.",
  goals:["I can perform Form One on the bell's steady count.","I used the mobility flows and they stayed easy.","When I lost the count I held my guard and rejoined instead of rushing."],
  days:[["Flow and count","Flows & Form One",["c6-flow-hips","c6-form","c6-form","c6-flow-upper","c6-strength-1"],"Mobility flows you can do anywhere, and the form on the count."],
   ["Easy flows","Easy review",["c6-flow-hips","c6-form","c6-quiet","c6-flow-upper"]],
   ["On the count","Form volume",["c6-flow-hips","c6-form","c6-small-rounds","c6-form","c6-strength-2"],"Main volume: rounds and the form on the count."],
   ["Flows and strength","Form & strength",["c6-form","c6-flow-upper","c5-set","c6-strength-1","c6-strength-2"]],
   ["Check the count","Form self-check",["c6-flow-hips","c6-form","c6-small-rounds","c6-form","c6-selfcheck"],"Does the form survive the count?"],
   ["Easy flows","Easy flow",["c6-flow-hips","c6-form","c6-flow-upper","c6-quiet"]]]},
 {name:"Travel and the mirror",focus:"A practice template that needs only a wall or doorframe; Form One mirrored on the other lead.",
  goals:["I can perform Form One mirrored on the other lead, slowly.","I can run a practice with a wall or doorframe instead of a chair.","I planned one place outside my usual space where I could practise."],
  days:[["No chair needed","Travel & mirror",["c6-travel","c6-form-mirror","c6-flow-hips"],"A calmer week: practise like you're away from home, and meet your form's other side."],
   ["Easy review","Easy review",["c6-travel","c6-form","c6-flow-upper","c6-quiet"]],
   ["Both sides","Mirror & small rounds",["c6-travel","c6-form-mirror","c6-small-rounds"],"Both leads of the form, then rounds in the square."],
   ["Travel strength","Travel & strength",["c6-travel","c6-form","c6-flow-hips","c6-strength-2"]],
   ["Check both sides","Form self-check",["c6-travel","c6-form-mirror","c6-selfcheck","c6-strength-1"],"Which side of the form needs more visits?"],
   ["Easy flows","Easy flow",["c6-flow-hips","c6-form","c6-travel","c6-flow-upper"]]]},
 {name:"Trial week · Anywhere",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Anywhere trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the square","Light review",["c6-quiet","c6-form","c6-flow-hips","c6-flow-upper"]],
   ["Review the travel day","Light review",["c6-travel","c6-form","c6-quiet","c6-flow-upper"]],
   ["Calm rounds","Light review",["c6-form-mirror","c6-small-rounds"]],
   ["Calm before the trial","Light review",["c6-form","c6-flow-hips","c6-strength-1","c6-strength-2"]],
   ["Trial: Anywhere","Chapter trial",["c6-quiet","c6-trial-form","c6-trial-strength","c6-small-rounds"],"The chapter trial: Form One from memory and a small-space session. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["c6-flow-hips","c6-form","c6-flow-upper","c6-quiet"]]]},
]};
