import {makeDrills,type ChapterSpec} from "./build";

// Chapter 5 · Combinations and rounds. Hands, defense, kicks and footwork linked into
// combinations; the first timed shadow rounds against an imagined opponent.
export const COMBINATION_MENU = ["1-2","1-1-2","1-2-hook","2-hook-2","uppercut-hook","slip-2","parry-1-2","cover-1-2","roll-hook","1-2-low kick","jab-front kick","check-2","step back","pivot out"] as const;
const menu = `Menu: ${COMBINATION_MENU.join(" · ")}.`;

const drills = makeDrills(5,{
 "c5-warm":{name:"Full-body flow",family:"Preparation",timing:"warmup",cue:"Wake everything a little. Nothing a lot.",
  steps:["First 30 seconds: clear your space, chair within reach, find your point. Picture where your imagined opponent will stand.","Next 2 minutes: march or walk in place, then add arm swings, trunk turns and small leg swings holding the chair. Breathing rises a little.","Next 90 seconds: 30 seconds of slow shadow movement (half-speed jabs, a slip, a step), then calf raises and hip circles, then 30 more seconds of slow shadow work.","Final minute: feet together, a small bow toward your point. Step into stance and raise your guard with one sharp breath out. One breath of stillness. Practice begins."],
  checks:["I feel warm everywhere but not tired.","I opened with the bow and the ready."],
  supported:"Keep a hand on the chair for the leg work and slow the shadow movement.",
  seated:"Seated marches, arm swings and trunk turns, seated half-speed strikes, then a seated bow and guard.",
  avoid:"No jumping or sprinting to warm up. Stop if dizzy or with joint pain.",sources:["aaos"]},
 "c5-cool":{name:"Walk it down",family:"Finish",timing:"cooldown",cue:"The round is over. Let the body know it.",
  steps:["First 2 minutes: walk slowly around your space, shaking out the arms and letting the breathing slow.","Next 2 minutes: calf stretch against the wall, a gentle standing hip-flexor stretch and a light chest stretch in a doorway, 15–20 seconds each.","Final minute: breathe in for 4 counts and out for 6. Name one combination that felt like yours today and one to clean up.","Feet together, a small bow. Practice ends. No extra rounds."],
  checks:["My breathing slowed before I finished.","I can name one combination that felt like mine."],
  supported:"Hold the chair while walking slowly and for each stretch.",
  seated:"Sit, breathe slowly, and do seated calf, hip and chest stretches; a seated bow.",
  avoid:"Mild stretch only. Stop with sharp pain or dizziness.",sources:["nhs-flex"]},
 "c5-grammar":{name:"Combination grammar",family:"Combinations",cue:"Every combination is a sentence. Start clean, end with the guard.",
  steps:["Two new sentences: 1-2-hook (jab, cross, lead hook) and 1-1-2. Say the numbers quietly as you throw them if it helps.","Every combination ends the same way: hands home, eyes on your point, one count of stillness. That pause is part of the sentence.","Round 1: 1-2-hook, 4–5 times, slow. Round 2: 1-1-2 on the other lead. Round 3: alternate the two, smooth.","If the third strike drags the guard down or swings wide, go back to the 1-2 for a round."],
  checks:["Every combination ends with both hands home and one still count.","The third strike is as clean as the first."],
  supported:"Throw every combination at half range with feet planted beside the chair.",
  seated:"Seated combinations at chest height with small trunk turns.",
  avoid:"No speed before the sentence is clean. No locked elbows.",sources:["boxing-beginner","boxing-club"]},
 "c5-ladder":{name:"Combination tempo ladder",family:"Combinations",format:"B",cue:"Slow is smooth. Smooth becomes crisp.",
  steps:["Pick one combination for the whole block: 1-2-hook or 1-1-2.","Round 1 slow, with a pause between strikes. Round 2 smooth, no pauses inside the combination. Round 3 crisp: fast out, faster back, still short of a straight elbow.","Round 4: smooth on the other lead. Breathe out on every strike.","If anything changes when you speed up, go back a rung on the ladder next round."],
  checks:["My crisp round looks like my slow round, only faster.","Elbows stay soft and the guard comes home at every tempo."],
  supported:"Climb the ladder with feet planted and half-range strikes.",
  seated:"Climb the ladder seated.",
  avoid:"Crisp is quick, not hard. No maximal speed.",sources:["boxing-beginner","jkd"]},
 "c5-defense-in":{name:"Defense inside combinations",family:"Combinations",format:"B",cue:"Strike, defend, strike. The middle matters most.",
  steps:["1-2-slip-2: jab, cross, slip outside an imagined counter-jab, cross again.","Parry-1-2: catch an imagined jab with the rear hand, then jab and cross.","Rounds 1 and 3: one sequence, 4–5 times. Rounds 2 and 4: the other, on the other lead.","The defense is a full part of the combination: finish it, eyes on your point, before the next strike."],
  checks:["Each defense is complete before the next strike.","Slips stay small and come back to centre."],
  supported:"Feet planted beside the chair, half range, small slip leans.",
  seated:"Seated strikes with a seated slip lean or parry in the middle.",
  avoid:"Slow head movement only. Stop if dizzy.",sources:["boxing-beginner","boxing-club"]},
 "c5-angles":{name:"Angles: pivot out or step off",family:"Footwork",cue:"Strike from here. Be somewhere else when they answer.",
  steps:["After a 1-2, pivot out: turn on the ball of the front foot and swing the rear foot a short arc so you face your point from a new angle.","Or step off: a small step to the side, nearest foot first, then turn to face your point again.","Round 1: 1-2 then pivot. Round 2: 1-2 then step off to either side. Round 3: choose, on the other lead.","Feet never cross. After every angle, stop and check that you face your point in stance."],
  checks:["My feet never cross during a pivot or step-off.","I finish every angle facing my point with the guard up."],
  supported:"Use small pivots with a hand on the chair, or replace the step-off with a weight shift.",
  seated:"Turn the knees and trunk a little to one side after a seated 1-2.",
  avoid:"No spins, no fast turns on a planted knee, no long lateral lunges.",sources:["boxing-club"]},
 "c5-angles-build":{name:"Combination, then angle",family:"Footwork",format:"B",cue:"Hit, move, see them again.",
  steps:["Choose any combination from this chapter and finish it with a pivot or a step-off.","Find your point again, guard up, one breath. Then the next combination from the new angle.","4–5 cycles per round. Rounds 1 and 3 on your usual lead, 2 and 4 on the other.","Vary the combinations and the exits; that variety helps the skills stick."],
  checks:["Every combination ends in an angle change.","My stance is rebuilt facing my point after each angle."],
  supported:"Half-range combinations and small supported pivots.",
  seated:"Seated combinations with a small turn of the knees at the end.",
  avoid:"No spinning or crossing feet.",sources:["boxing-club","practice-order"]},
 "c5-punch-kick":{name:"Punch-kick links",family:"Combinations",format:"B",cue:"Hands high, kick low, home again.",
  steps:["1-2-low kick: jab, cross, rear low round kick, set down in stance.","Front kick-1-2: lead low push kick, set the foot down forward, jab, cross.","Rounds 1 and 3: the first link. Rounds 2 and 4: the second, on the other lead.","Check your balance after every kick before the next strike. The chair stays within reach."],
  checks:["My balance is steady after every kick.","Every kick stays at or below hip height."],
  supported:"Hands at half range, then the kick with a hand on the chair.",
  seated:"Seated 1-2 then a seated knee lift and extension.",
  avoid:"No hopping, no high kicks, no speed until each link is clean.",sources:["kicks","jkd"]},
 "c5-set":{name:"The set sequence",family:"Combinations",format:"B",cue:"Strike. Stillness. Breath. Next.",
  steps:["Four combinations, always in this order: (1) 1-2-hook, step back; (2) slip-2-hook; (3) parry-1-2, pivot out; (4) 1-2-low round kick, set down, guard.","Between combinations: guard home, eyes on your point, one breath. The rhythm is strike, still, breathe, next.","Round 1: slowly, pausing whenever you need to remember. Round 2: the other lead. Rounds 3–4: with rhythm, like a short performance with a clear beginning and end.","Optional: film one round on your own phone to compare your leads. The video stays with you."],
  checks:["I perform the four combinations in order without stopping to remember.","Guard home and one breath between each combination."],
  supported:"Run the set at half range with a hand near the chair for the kick.",
  seated:"Seated version: the hands of each combination at chest height, a knee lift for the kick.",
  avoid:"Rhythm, not speed. No hopping on the kick.",sources:["boxing-beginner","kicks"]},
 "c5-rounds":{name:"Shadow rounds from the menu",family:"Rounds",format:"C",cue:"See them. Answer them. Breathe.",
  steps:["Before the first bell, picture your opponent at your point: their height, their guard, how they step. In the rounds you move and strike as if they are there; imagery joined to real movement is more effective than either alone.",`${menu} Choose freely; after every combination bring the guard home and move your feet with a small step or pivot.`,"Round 1 on your usual lead, round 2 on the other, round 3 your choice. Effort: you can still speak in short sentences. Between combinations keep moving gently with small steps, never hopping.","In each rest, walk slowly and breathe out long. If form slips, slow down or use only the hands."],
  checks:["Guard home and feet moving between combinations.","Effort stayed at 'short sentences'."],
  supported:"Shorten each round in your own head: work for the first minute, then walk with your guard up; keep the chair near for kicks.",
  seated:"Seated rounds: strikes, leans and knee lifts on your own rhythm.",
  avoid:"No sprinting pace, no high kicks, no jumping. Stop with dizziness or unusual breathlessness.",sources:["imagery","talk-test","practice-order"]},
 "c5-rounds-tempo":{name:"Rounds with tempo changes",family:"Rounds",format:"C",cue:"Change the speed, keep the shape.",
  steps:["Each 2-minute round changes tempo at the clock: until 1:30 left slow and precise, until 1:00 smooth, until 0:30 crisp, then slow again to finish.","After every combination, exit: a step back or a pivot out, guard up.",`${menu} Mix hands, defense and kicks.`,"Round 1 usual lead, round 2 other lead, round 3 your choice. Breathe out long in every rest."],
  checks:["My form held at every tempo.","I exited after combinations instead of standing still."],
  supported:"Keep the tempo changes but use the hands-only part of the menu, kicks with the chair.",
  seated:"Seated rounds with the same tempo changes.",
  avoid:"Crisp is never maximal. Stop if form breaks badly or you feel unwell.",sources:["practice-order","talk-test"]},
 "c5-mobility":{name:"Calves, hips and shoulders",family:"Mobility",cue:"Recovery is part of the round.",
  steps:["Round 1: calf stretch against the wall and ankle circles.","Round 2: hip circles and a gentle standing hip-flexor stretch in a split stance.","Round 3: shoulder circles and a light doorway chest stretch.","Rest between rounds. Easy and pain-free."],
  checks:["Every movement stayed easy.","I feel looser than when I started."],
  supported:"Hold the chair for every round.",seated:"Do every round seated.",
  avoid:"No bouncing, no forced range.",sources:["nhs-flex","nhs-sitting"]},
 "c5-strength":{name:"Feet and core for rounds",family:"Strength",format:"S",cue:"Light feet, quiet middle.",exercises:["Lateral shuffle","Calf raise","Bird dog hold","Side plank"],
  steps:["Lateral shuffle: in a slightly lowered stance, take small quiet steps sideways (two each way) with the feet never touching and no hop. Easy pace.","Calf raise: holding the chair, 10–15 slow raises, the last few with a 2-second hold at the top.","Bird dog hold: reach the opposite arm and leg and hold 5 seconds without letting the hips turn; switch. 4–5 per side. This trains the trunk to resist rotation.","Side plank: knees bent or legs long, 15–20 seconds each side. Stop every exercise 2–3 reps before it gets hard."],
  checks:["The shuffle stayed quiet with feet never touching.","My hips stayed level in the bird dog and side plank."],
  supported:"Shuffle with a hand trailing along a wall; standing bird dog at the chair; side plank as a forearm lean on a wall.",
  seated:"Seated side-to-side foot taps, seated heel raises, seated opposite arm and knee lifts.",
  avoid:"No jumping shuffles, no breath-holding, no back pain.",sources:["nhs-strength","rir"]},
 "c5-selfcheck":{name:"Combinations self-check",family:"Self-check",cue:"Can you say it cleanly in both languages?",
  steps:["Round 1, usual lead: this week's combination three times, slowly. Watch its two form checks.","Round 2, other lead: the same.","Round 3: the side or the part of the combination that needed the most help.","Review minute: one combination that is yours and one correction for next week. Self-recording is optional and stays on your device."],
  checks:["I can name the stronger and weaker side for this combination.","I chose one correction instead of adding speed."],
  supported:"Check at half range with the chair near.",seated:"Check the seated version.",
  avoid:"No extra rounds.",sources:["boxing-beginner"]},
 "c5-trial-set":{name:"Trial · the set sequence",family:"Chapter trial",format:"B",cue:"Four sentences, one story.",
  steps:["Round 1: the set sequence slowly on your usual lead.","Round 2: the set sequence slowly on the other lead.","Rounds 3–4: the set with rhythm, one round on each lead.","Mark the checks honestly. 'Not yet' means repeat a week; it never blocks the story."],
  checks:["Guard home between combinations.","Feet never cross."],
  supported:"The set at half range with the chair near for the kick.",seated:"The seated set.",
  avoid:"Rhythm, not speed.",sources:["boxing-beginner","kicks"]},
 "c5-trial-rounds":{name:"Trial · three structured rounds",family:"Chapter trial",format:"C",cue:"Three rounds. One calm fighter.",
  steps:["Round 1, hands and defense only: combinations from the menu with a step or pivot after each.","Round 2, add the kicks: punch-kick links and checks, balance after every kick.","Round 3, everything, your choice, on the other lead. Effort stays at 'short sentences'.",`Rests: walk and breathe out long. ${menu}`],
  checks:["Balance after every kick.","Breathing steady through all three rounds."],
  supported:"Work the first minute of each round, then walk with your guard up; kicks with the chair.",seated:"Seated rounds on your own rhythm.",
  avoid:"No sprinting, no high kicks. Stop if unwell.",sources:["imagery","talk-test"]},
});

export const CHAPTER_5:ChapterSpec = {chapter:5,warm:"c5-warm",cool:"c5-cool",drills,weeks:[
 {name:"Combination grammar",focus:"1-2-hook and 1-1-2: every combination ends with both hands home and one count of stillness.",
  goals:["I can throw 1-2-hook and 1-1-2 with both hands home and one still count after each.","My third strike stays as clean as the first, on both leads.","I went back to the 1-2 whenever a longer combination broke down."],
  days:[["Sentences, not words","Combination grammar",["c2-onetwo","c5-grammar","c5-grammar","c3-hook"],"A calmer week to learn how combinations begin, flow and end."],
   ["Easy review","Easy review",["c2-onetwo","c3-slip","c4-teep","c5-mobility"]],
   ["Say it cleanly","Combination volume",["c5-grammar","c2-double","c5-grammar","c3-curves","c4-links"],"Main volume: three-strike combinations that end in stillness."],
   ["Combinations and strength","Combinations & strength",["c5-grammar","c3-counters","c4-kick-build","c5-strength"]],
   ["Check the sentences","Combination self-check",["c5-grammar","c4-links","c3-flow","c5-grammar","c5-selfcheck"],"Both leads, clean endings."],
   ["Easy flow","Easy flow",["f2-shift","c5-grammar","c4-chamber","c5-mobility"]]]},
 {name:"Defense inside combinations",focus:"1-2-slip-2 and parry-1-2: the defense is a full part of the combination. A tempo ladder for combinations.",
  goals:["I can complete a defense inside a combination (1-2-slip-2, parry-1-2) before the next strike.","On the tempo ladder my crisp combinations look like my slow ones.","I kept the defense small and my eyes on my point."],
  days:[["Strike, defend, strike","Defense inside",["c5-grammar","c5-defense-in","c5-defense-in","c5-ladder","c3-slip"],"The middle of the combination is now a defense."],
   ["Easy review","Easy review",["c5-grammar","c3-parry","c4-teep","c5-mobility"]],
   ["The middle matters","Defense-inside volume",["c5-ladder","c5-defense-in","c5-grammar","c5-defense-in","c4-kick-build"],"Main volume at an easy effort; defenses complete before strikes."],
   ["Tempo and strength","Ladder & strength",["c5-defense-in","c5-ladder","c3-roll","c4-check","c5-strength"]],
   ["Check the middle","Defense-inside self-check",["c5-grammar","c5-defense-in","c5-ladder","c4-links","c5-selfcheck"],"Watch the slip and the parry inside the combination."],
   ["Easy flow","Easy flow",["f2-shift","c5-grammar","c3-slip","c5-mobility"]]]},
 {name:"Angles",focus:"Pivot out or step off after a combination, then find your point again.",
  goals:["I can pivot out or step off after a combination without crossing my feet.","After each angle change I face my point in stance with the guard up.","I kept pivots small and controlled."],
  days:[["Be somewhere else","Angles",["c5-grammar","c5-angles","c5-angles","c5-defense-in","c3-exits"],"Strike from one place, finish from another."],
   ["Easy review","Easy review",["c5-grammar","c3-exits","c4-round","c5-mobility"]],
   ["Hit and move","Angles volume",["c5-angles","c5-angles-build","c5-defense-in","c5-angles-build","c5-ladder"],"Main volume: every combination ends with an angle."],
   ["Angles and strength","Angles & strength",["c5-angles-build","c5-defense-in","c4-kick-build","c3-curves","c5-strength"]],
   ["Check the angles","Angles self-check",["c5-ladder","c5-angles-build","c5-defense-in","c5-angles-build","c5-selfcheck"],"Feet never cross; you always find your point again."],
   ["Easy flow","Easy flow",["f2-shift","c5-angles","c4-chamber","c5-mobility"]]]},
 {name:"Punch-kick links",focus:"1-2-low kick and front kick-1-2 with balance checked after every kick.",
  goals:["I can link punches and low kicks (1-2-low kick, front kick-1-2) with balance after the kick.","My kicks in combinations stay at or below hip height.","I used the chair or the hands-only version whenever my balance after a kick slipped."],
  days:[["Hands high, kick low","Punch-kick links",["c4-links","c5-punch-kick","c5-punch-kick","c5-angles-build","c4-check"],"The chapter's fullest stretch begins: hands and kicks as one."],
   ["Easy review","Easy review",["c5-grammar","c4-teep","c4-round","c5-mobility"]],
   ["Kick and come home","Links volume",["c5-ladder","c5-punch-kick","c5-defense-in","c5-punch-kick","c5-angles-build","c4-kick-build"],"Forty minutes of linked work, still at 'short sentences'."],
   ["Links and strength","Links & strength",["c5-punch-kick","c5-angles-build","c5-defense-in","c4-chamber-hold","c5-strength"]],
   ["Check the links","Links self-check",["c5-grammar","c5-punch-kick","c5-defense-in","c5-angles-build","c5-punch-kick","c5-selfcheck"],"Balance after every kick, on both leads."],
   ["Easy flow","Easy flow",["f2-shift","c5-grammar","c4-links","c5-mobility"]]]},
 {name:"The set sequence",focus:"Four combinations in a fixed order performed with rhythm: strike, stillness, breath, next.",
  goals:["I can perform the four-combination set sequence in order on my usual lead.","I keep a rhythm of strike, stillness, breath, next, or the supported/seated version.","I practised the set on the other lead too, at whatever tempo was clean."],
  days:[["Four sentences","Set sequence",["c5-ladder","c5-set","c5-set","c5-punch-kick","c5-defense-in"],"Learn the set in order. Pause to remember; the rhythm comes later."],
   ["Easy review","Easy review",["c5-grammar","c5-angles","c4-teep","c5-mobility"]],
   ["Find the rhythm","Set volume",["c5-set","c5-punch-kick","c5-set","c5-angles-build","c5-defense-in","c5-set"],"Main volume: the set, again and again, until it has a rhythm."],
   ["Set and strength","Set & strength",["c5-set","c5-ladder","c5-punch-kick","c4-check","c5-strength"]],
   ["Perform the set","Set self-check",["c5-ladder","c5-set","c5-defense-in","c5-punch-kick","c5-set","c5-selfcheck"],"Perform the set on both leads; film one if you like."],
   ["Easy flow","Easy flow",["f2-shift","c5-set","c4-chamber","c5-mobility"]]]},
 {name:"Shadow rounds",focus:"Timed 2-minute rounds against an imagined opponent, chosen from a printed combination menu.",
  goals:["I completed three 2-minute shadow rounds from the menu with my guard home between combinations.","My effort stayed at 'short sentences' and I walked and breathed out in every rest.","I pictured an opponent and moved my feet between combinations."],
  days:[["The first rounds","Shadow rounds",["c5-set","c5-rounds","c5-punch-kick","c5-defense-in"],"Round blocks begin: three 2-minute rounds. See your opponent; answer them."],
   ["Easy review","Easy review",["c5-grammar","c5-set","c4-teep","c5-mobility"]],
   ["Two sets of rounds","Rounds volume",["c5-ladder","c5-rounds","c5-set","c5-rounds"],"Six rounds in all, every rest a walk and a long exhale."],
   ["Rounds and strength","Rounds & strength",["c5-rounds","c5-angles-build","c5-punch-kick","c5-strength"]],
   ["Rounds with a check","Rounds self-check",["c5-set","c5-rounds","c5-punch-kick","c5-selfcheck","c5-angles-build"],"Test-style: rounds, then an honest look at one combination."],
   ["Easy flow","Easy flow",["f2-shift","c5-grammar","c5-set","c5-mobility"]]]},
 {name:"Tempo and exits",focus:"Change tempo inside a round and exit after every combination.",
  goals:["I can change tempo within a round without losing form.","I exit with a step back or pivot after combinations.","I slowed down when form slipped late in a round."],
  days:[["Change the speed","Tempo rounds",["c5-ladder","c5-rounds-tempo","c5-angles-build","c5-set"],"Slow, smooth, crisp, slow: one round, four speeds."],
   ["Easy review","Easy review",["c5-grammar","c5-defense-in","c4-teep","c5-mobility"]],
   ["Rounds that breathe","Rounds volume",["c5-set","c5-rounds-tempo","c5-rounds"],"Main volume: two round blocks with every rest a long exhale."],
   ["Exits and strength","Rounds & strength",["c5-rounds-tempo","c5-punch-kick","c4-check","c5-strength"]],
   ["Check the tempo","Rounds self-check",["c5-set","c5-rounds-tempo","c5-selfcheck","c5-angles-build"],"Does your form hold at every speed?"],
   ["Easy flow","Easy flow",["f2-shift","c5-set","c5-grammar","c5-mobility"]]]},
 {name:"Trial week · Combinations",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Combinations trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the sentences","Light review",["c5-grammar","c5-defense-in","c5-punch-kick","c5-mobility"]],
   ["Review the set","Light review",["c5-set","c5-angles-build","c4-teep","c5-mobility"]],
   ["Calm rounds","Light review",["c5-ladder","c5-rounds","c5-set"]],
   ["Calm before the trial","Light review",["c5-set","c5-punch-kick","c4-check","c5-strength"]],
   ["Trial: Combinations","Chapter trial",["c5-ladder","c5-set","c5-trial-set","c5-trial-rounds","c5-mobility"],"The chapter trial: the set sequence and three structured rounds. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["f2-shift","c5-grammar","c5-set","c5-mobility"]]]},
]};
