import {makeDrills,type ChapterSpec} from "./build";

// Chapter 2 · Hands. Straight strikes in the air from stance, home to guard every time, both leads.
const drills = makeDrills(2,{
 "c2-warm":{name:"Wake the shoulders",family:"Preparation",timing:"warmup",cue:"Warm hands are fast hands. Start slow.",
  steps:["First 30 seconds: clear about 2 × 2 metres of non-slip floor, put a sturdy chair against a wall within reach, and choose your point: a mark at about chin height on a wall at least 2 metres away. It is a target for your eyes only.","Next 2 minutes: walk or march gently in place. Add easy arm swings across your chest and small shoulder circles in both directions. Let your breathing rise a little; you should still speak in full sentences.","Next 90 seconds: wrist circles, open and close your hands, then slow 'goalposts' in the air (elbows at shoulder height, raise and lower the forearms). Finish with 5 slow half-range jabs per hand, no snap.","Final minute: stand with feet together, eyes on your point, and give a small bow. Step back into your stance and raise your guard with one sharp breath out through the nose. Hold one breath of stillness. Practice begins."],
  checks:["My shoulders and wrists feel warm and loose, not tired.","I chose my point and opened with the bow and the ready."],
  supported:"Keep one hand on the chair while marching and do the arm work one side at a time.",
  seated:"Sit tall at the front of the chair, march the feet gently and do the shoulder, wrist and goalpost work seated; finish with a seated bow and guard.",
  avoid:"No jumping jacks or bouncing. Stop if you feel dizzy, short of breath or have joint pain.",sources:["aaos"]},
 "c2-cool":{name:"Unwind the arms",family:"Finish",timing:"cooldown",cue:"Let the hands drop. Let the breath lengthen.",
  steps:["First 2 minutes: lower your hands and walk slowly, shaking out the arms. Let the movement get smaller as your breathing settles.","Next 2 minutes: gentle forearm stretch (palm flat on the wall, fingers down, 15–20 seconds each side), a light chest stretch with a forearm on a door frame, and slow shoulder rolls. Mild tension only.","Final minute: breathe in through the nose for 4 counts and out for 6. Name one strike that felt clean today and one thing to fix next time. A note is optional.","Close as you opened: feet together, a small bow. Practice ends here; never add extra rounds to make up for a missed day. If your shoulders ache tomorrow, choose the gentle option."],
  checks:["My breathing settled before I finished.","I can name one clean strike and one correction."],
  supported:"Use the chair back for balance while walking slowly and for the forearm stretch.",
  seated:"Sit, rest the hands on the thighs, roll the shoulders and stretch the forearms seated; finish with the breathing and a seated bow.",
  avoid:"No forced stretches or bouncing. Stop if you feel tingling, numbness or sharp pain.",sources:["nhs-flex"]},
 "c2-fist":{name:"Fist, path and return",family:"Hands",cue:"Make the fist late. Keep the wrist straight. Come home on the same rail.",
  steps:["Make a fist: fold the fingers into the palm and lay the thumb across the middle of the first two fingers, outside the fist and never tucked inside. Keep it loose. The knuckles and the back of the forearm make one flat line.","From your stance and guard, slowly slide the lead hand forward toward your point at chin height, as if along a rail. The elbow stays down behind the fist and the shoulder stays relaxed.","Stop with the elbow still softly bent. Turn the palm toward the floor only in the last third of the path. Pause one count, then return along the same rail to your cheek.","About 5 slow paths per round: lead hand in round 1, rear hand in round 2, either hand on the other lead in round 3. Say 'rail, turn, home' quietly if it helps. No speed yet."],
  checks:["The wrist stays straight from knuckles to forearm.","Each hand returns to the same place by the cheek."],
  supported:"Rest one hand on the chair back and practise the path with the free hand; switch hands each round.",
  seated:"Sit tall, feet planted, and rehearse the fist, the rail and the return at chest height.",
  avoid:"No fast or hard punches, no locked elbows, no hitting walls, bags or furniture. Stop if a wrist, elbow or shoulder hurts.",sources:["boxing-beginner","focus"]},
 "c2-jab":{name:"Lead straight · the jab",family:"Hands",cue:"Out like a whip. Home before they blink.",
  steps:["Stance and guard, eyes on your point. Keep the lead hand relaxed. The jab starts from the hand itself, with no shoulder hitch or dip first.","Send the lead fist along its rail toward the point with a slight turn of the lead hip and shoulder. Breathe out sharply ('tss') as it travels and turn the palm down in the last third.","Stop just short of straight, elbow soft. Bring it home along the same line at least as fast as it went out. The rear hand stays by your cheek the whole time.","Slow first: one jab every 3–4 seconds, about 6–8 per round. Round 1 usual lead, round 2 the other lead, round 3 usual lead. If the rear hand drops, slow down."],
  checks:["The rear hand stays by the cheek while the jab is out.","The jab comes home on the same line instead of swinging low."],
  supported:"Rest the rear hand lightly on the chair back and jab with the lead hand only, feet still.",
  seated:"Sit tall in guard and jab at chest height with an exhale; return to the cheek each time.",
  avoid:"Never snap the elbow straight or throw at full power into the air. No wind-up, no dropped rear hand. Stop with joint pain.",sources:["boxing-beginner","jkd"]},
 "c2-cross":{name:"Rear straight · the cross",family:"Hands",cue:"The back foot turns the hip. The hip throws the hand.",
  steps:["From stance and guard, rise slightly onto the ball of the rear foot. Practise the pivot alone: rear heel turns out, rear knee and hip turn toward your point, then turn back. Three slow pivots.","Add the hand: as the heel and hip turn, the rear fist travels straight to the point at chin height. Breathe out sharply. The lead hand comes home to guard the cheek.","Stop with the elbow soft. The weight shifts only a little forward: your head stays behind the front knee. Bring the hand home, turn the heel back and check your balance for one count.","About 5 slow crosses per round with a balance check after each. Round 2 on the other lead, round 3 back on the usual lead. Smooth before fast."],
  checks:["The rear heel and hip turn with the strike.","After each cross my head is still behind the front knee and I am balanced."],
  supported:"Hold the chair with the lead hand, practise the rear-foot pivot and hip turn slowly, then add the rear hand at half range.",
  seated:"Sit tall and turn the trunk toward your point as the rear hand travels at chest height; return to centre each time.",
  avoid:"No lunging past the front knee, no twisting on a planted heel, no locked elbow. Stop with knee, back or shoulder pain.",sources:["boxing-beginner"]},
 "c2-onetwo":{name:"The 1-2",family:"Hands",cue:"One, two, and the guard is already home.",
  steps:["1 is the jab and 2 is the cross. From stance, eyes on your point, throw a slow jab and bring it home.","As the jab returns, the rear heel turns and the cross goes out. Breathe out on each strike: 'tss, tss'. The lead hand guards your cheek during the 2.","Bring the cross home and hold your guard for one count. This is zanshin: staying ready after you strike. Then relax the shoulders without dropping the hands.","Slow this week: 1-2, then a full pause; 5–6 per round. When three in a row feel clean, make it smooth with no gap between 1 and 2, still pausing after. Alternate the lead each round."],
  checks:["Both hands come home after every 1-2.","My feet stay apart and planted; only the rear heel turns."],
  supported:"Keep a hand near the chair between combinations; strike at half range with the feet still.",
  seated:"Sit tall: jab and cross at chest height with a small trunk turn and an exhale on each.",
  avoid:"No rushing into speed, no locked elbows, no dropping the hands between strikes.",sources:["boxing-beginner"]},
 "c2-still":{name:"Still, then snap",family:"Hands",format:"B",cue:"Stillness first. Then the hand is simply gone.",
  steps:["Stand in guard, completely still, eyes on your point. Notice anything that moves before a jab: a shoulder hitch, a breath in, a dip of the hand, a blink. Each one would tell an opponent what is coming.","Throw a jab where the fist moves first and nothing else announces it. Stay relaxed until the last moment, breathe out short, come home. Wait in stillness for 2–4 seconds, varying the wait so it never becomes a rhythm.","Each 40-second round: 6–8 jabs from stillness. Rounds 1 and 3 on your usual lead, rounds 2 and 4 on the other lead.","If you have a mirror or your own phone, watch one round side-on: does the shoulder or chin move before the fist? Fix only one thing per round."],
  checks:["The fist starts first, with no hitch or dip before it.","The rear hand stays home and my body is still between jabs."],
  supported:"Rest the rear hand on the chair and practise the still start and the quiet jab at half range.",
  seated:"Sit tall in guard and practise the still start with the lead hand at chest height.",
  avoid:"Speed comes from relaxation, not force: no locked elbows and no full-power snaps into the air.",sources:["jkd","boxing-beginner"]},
 "c2-stepjab":{name:"Step-and-strike",family:"Hands",cue:"The foot and the fist arrive together.",
  steps:["Revise the Chapter 1 forward step: front foot first, rear foot follows the same small distance. Two slow steps with full stops.","Now jab as the front foot slides forward, so the fist and the front foot land at the same moment. The rear foot then follows to rebuild your stance. Breathe out on the jab.","Step back out: rear foot first, then front foot, hands home. Stop and check your spacing. That is one cycle.","3–4 slow cycles per round; round 2 on the other lead. If the feet come together or cross, shorten the step."],
  checks:["The jab and the front foot land together.","The stance is rebuilt after the step in and after the step out."],
  supported:"Keep the chair by your rear hand and replace the step with a planted forward weight shift, then shift back.",
  seated:"Sit tall and tap the lead foot forward as the jab goes out; return foot and hand together.",
  avoid:"No long lunges, no hopping, no stepping toward furniture. Stay inside your cleared space.",sources:["boxing-beginner"]},
 "c2-stepjab-build":{name:"Strike, then step out",family:"Hands",format:"B",cue:"In with the jab. Out before they answer.",
  steps:["Step in with a jab (foot and fist land together), then throw the cross from where you land.","Immediately step back out: rear foot first, then front foot, guard home. Stop for one count with your eyes on your point.","Each 40-second round: 4–6 cycles at a smooth tempo. Rounds 1 and 3 on your usual lead, rounds 2 and 4 on the other lead.","Use the 20-second rests to breathe out slowly. If balance wobbles on the way out, pause a full count between the cross and the step next round."],
  checks:["The step out begins with the rear foot and the guard is home.","The cross never pulls my head past the front knee."],
  supported:"Replace the steps with forward and backward weight shifts beside the chair; keep the strikes at half range.",
  seated:"Tap the lead foot in with the jab, cross at chest height, then draw both feet back under you.",
  avoid:"No backward hopping, no crossing feet, no looking down while you step back.",sources:["boxing-beginner"]},
 "c2-double":{name:"Double jab · 1-1-2",family:"Hands",format:"B",cue:"The first jab finds the range. The second makes it yours.",
  steps:["Two jabs, then the cross. The first jab comes only halfway home before the second goes out. Breathe out on every strike.","Keep both jabs straight and small. The second may slide the front foot a few centimetres forward, with the rear foot following.","After the 2, hold your guard and your eyes for one count. About 5–6 combinations per 40-second round.","Rounds 1 and 3 on your usual lead, 2 and 4 on the other. If the second jab drops the shoulder or flares the elbow, slow both jabs down."],
  checks:["Both jabs travel on the same line and come home.","The rear hand stays at the cheek until the 2."],
  supported:"Keep the feet planted beside the chair and throw the 1-1-2 at half range.",
  seated:"Sit tall and throw the 1-1-2 at chest height with an exhale on each strike.",
  avoid:"No flailing for speed, no locked elbows, no leaning forward to reach.",sources:["boxing-beginner"]},
 "c2-exit":{name:"1-2 and step-back exit",family:"Hands",format:"B",cue:"Strike, then leave on your own terms.",
  steps:["Throw a smooth 1-2 from your stance.","Immediately step back: rear foot first, then front foot. Guard high, chin slightly down, eyes on your point.","Hold for one count. Then step back in to your starting place: front foot first, rear foot follows.","4–6 cycles per round, alternating the lead by round. The exit is part of the combination, not a rest."],
  checks:["I step out straight after the 2, rear foot first.","My guard is up and my eyes stay forward during the exit."],
  supported:"Use a backward weight shift beside the chair instead of the step.",
  seated:"After the seated 1-2, draw the feet back under the chair and lift the guard.",
  avoid:"No backpedalling quickly, no crossing feet, no turning your back.",sources:["boxing-beginner"]},
 "c2-tempo":{name:"Tempo ladder: slow, smooth, crisp",family:"Hands",format:"B",cue:"Complexity, then speed. Never speed instead of form.",
  steps:["Round 1, slow: the 1-2 with a full pause between the strikes. Check the rail, the wrist and the guard.","Round 2, smooth: no pause between the strikes, a pause after. Round 3, crisp: fast out, faster back, still short of a straight elbow.","Round 4: back to smooth on the other lead. Breathe out on every strike. Crisp means quick, not hard.","If anything changes at a faster tempo (the guard drops, the feet move, the elbow snaps), go back one step on the ladder next round."],
  checks:["The crisp round looks like the slow round, only faster.","Elbows stay soft at every tempo."],
  supported:"Climb the same ladder with the feet planted beside the chair.",
  seated:"Climb the ladder seated at chest height.",
  avoid:"No maximal speed or power, no locked elbows, no holding your breath.",sources:["boxing-beginner","jkd"]},
 "c2-mobility":{name:"Shoulders and wrists, easy",family:"Mobility",cue:"Loose shoulders make fast hands.",
  steps:["Round 1: slow shoulder circles forwards and backwards, then small, easy arm swings across the chest.","Round 2: wrist circles, open and close the hands, then a gentle forearm stretch with the palm on a wall, 15 seconds each side.","Round 3: goalposts. Elbows at shoulder height, raise and lower the forearms slowly without forcing the range.","Rest with the hands down between rounds. This is recovery, not a workout."],
  checks:["Every movement stays pain-free and easy.","My shoulders feel looser at the end than at the start."],
  supported:"Hold the chair with one hand and work one arm at a time.",
  seated:"Do every round seated with the back supported.",
  avoid:"No forced range, no bouncing stretches, no pain.",sources:["nhs-flex","nhs-sitting"]},
 "c2-core":{name:"Core basics",family:"Strength",format:"S",cue:"A strong middle keeps the hands honest.",exercises:["Dead bug","Bird dog","Glute bridge","Wall slides"],
  steps:["Dead bug: lie on your back, knees bent above the hips, arms up. Slowly lower one arm and the opposite foot toward the floor while your lower back stays gently down; return and switch. 4–6 slow reps per side.","Bird dog: on hands and knees, slide one arm forward and the opposite leg back until level, hips square. Pause two counts, return, switch. 4–6 per side.","Glute bridge: on your back, knees bent, feet flat. Press through the heels and lift until knees, hips and shoulders line up; lower slowly. 8–10 reps.","Wall slides: back against a wall, elbows bent like goalposts; slide the arms up and down within an easy range, 6–8 slow reps. Stop every exercise 2–3 reps before it gets hard."],
  checks:["My lower back stays neutral; I never arch to finish a rep.","I stopped each exercise with 2–3 good reps left."],
  supported:"Bird dog standing with both hands on the chair back, reaching one leg back; standing hip extension holding the chair instead of the bridge; dead bug with only the legs moving.",
  seated:"Seated marches with the opposite arm reaching forward, tall seated holds and shoulder-blade squeezes.",
  avoid:"No sit-ups, no breath-holding, no back or neck pain. Use a mat on hard floors.",sources:["nhs-strength","rir","who"]},
 "c2-selfcheck":{name:"Hands self-check",family:"Self-check",cue:"Look honestly. Fix one thing.",
  steps:["Round 1, usual lead: 3 jabs and 3 crosses at slow tempo, or this week's combination. Watch the two form checks of the week's skill.","Round 2, other lead: the same. Notice which side is cleaner.","Round 3: repeat whichever technique or side needed the most help, slowly.","Review minute: name one thing that is repeatable and one correction for next week. If you film yourself on your phone, the video stays with you; the app never sees it."],
  checks:["I can name my cleaner side and the side that needs practice.","I chose one correction instead of simply adding speed."],
  supported:"Do the check with the feet planted beside the chair.",seated:"Do the check seated at chest height and judge the arm path and guard.",
  avoid:"This is a check, not a test of effort. No extra rounds.",sources:["boxing-beginner"]},
 "c2-trial-1":{name:"Trial · the 1-2, both leads",family:"Chapter trial",format:"B",cue:"Show the 1-2 you have built.",
  steps:["Round 1, usual lead: a slow 1-2 with a full pause after each, 4–5 combinations. Watch the guard.","Round 2, other lead: the same.","Rounds 3–4: smooth 1-2s, one round on each lead. Elbows stay soft; hands come home.","In the review, mark each check honestly. 'Not yet' is useful information: the week can be repeated with no penalty, and story episodes never wait on the result."],
  checks:["My guard returns to the same place after every strike.","My elbows never snap straight."],
  supported:"Take the trial with the feet planted beside the chair.",seated:"Take the trial seated, judging the arm path, the guard and the elbows.",
  avoid:"The trial is controlled, not maximal. Stop with any joint pain.",sources:["boxing-beginner"]},
 "c2-trial-2":{name:"Trial · step, strike, return",family:"Chapter trial",format:"B",cue:"Feet, hands and balance as one.",
  steps:["Round 1: step in with the jab, cross, step back out. 3–4 cycles on your usual lead.","Round 2: the same on the other lead.","Round 3: the double jab and cross (1-1-2) with a step-back exit, usual lead. Round 4: the same on the other lead.","Review: compare the two leads honestly. Self-recording is optional and stays on your device."],
  checks:["My feet stay apart and I never lean past the front knee.","The quality is the same on both leads."],
  supported:"Use forward and backward weight shifts beside the chair instead of steps.",seated:"Tap the feet in and out seated while striking at chest height.",
  avoid:"No hopping, no crossing feet, no speed beyond control.",sources:["boxing-beginner"]},
});

export const CHAPTER_2:ChapterSpec = {chapter:2,warm:"c2-warm",cool:"c2-cool",drills,weeks:[
 {name:"The lead straight",focus:"Make a safe fist and learn the jab: a straight path from guard, short of a straight elbow, home on the same line.",
  goals:["I can make a fist with the thumb outside and a straight wrist, and return my hand to the same place by the cheek.","I can throw 6–8 slow jabs per round with the rear hand staying home, or rehearse them supported or seated.","I kept every jab short of a straight elbow and stopped when my shoulders tired."],
  days:[["The first strike","Fist & jab",["f2-moving-guard","c2-fist","c2-jab","c2-jab","f2-four"],"Your first punch. Learn the fist and the rail before anything else; slow, quiet jabs only."],
   ["Hands on the rail","Easy jab review",["f2-stance","f2-guard","c2-fist","c2-mobility"]],
   ["Home on the same line","Jab volume",["f2-moving-guard","c2-fist","c2-jab","f2-distance","c2-jab"],"The week's main volume: many slow, clean jabs. Count the returns, not the punches."],
   ["Jab and a strong middle","Jab & core",["c2-fist","c2-jab","f2-four","c2-jab","c2-core"]],
   ["Jab from both leads","Jab self-check",["f2-moving-guard","c2-jab","f2-choice","c2-jab","c2-selfcheck"],"Test-style: jab on both leads and check yourself honestly."],
   ["Loose and easy","Easy flow",["f2-shift","f2-guard","c2-jab","c2-mobility"]]]},
 {name:"The rear straight",focus:"Add the cross: rear-foot pivot and hip turn drive the hand; check your balance after every one.",
  goals:["I can turn the rear heel and hip with the cross and keep my head behind the front knee.","I can throw slow crosses on both leads with a balance check after each, or the supported/seated version.","I noticed one difference between my two leads and practised the weaker one without forcing it."],
  days:[["The hip throws the hand","Cross",["c2-jab","c2-cross","c2-cross","f2-stop"],"Learn the pivot alone, then let the hand ride on it."],
   ["Two hands, easy","Easy review",["f2-stance","c2-fist","c2-jab","c2-mobility"]],
   ["Turn, strike, check","Cross volume",["c2-jab","c2-cross","f2-moving-guard","c2-cross","c2-jab"],"Long day, gentle week: the cross with a balance check after every one."],
   ["Pivot and core","Cross & core",["c2-jab","c2-cross","c2-cross","c2-core"]],
   ["Balance after every strike","Cross self-check",["f2-four","c2-jab","c2-cross","c2-cross","c2-selfcheck"],"Check both leads: heel, hip and balance."],
   ["Easy hands","Easy flow",["f2-shift","c2-jab","c2-cross","c2-mobility"]]]},
 {name:"The 1-2",focus:"Join the jab and cross: slow with a pause, then smooth. Hold the guard for one count after every combination.",
  goals:["I can throw a slow 1-2 with both hands coming home, on both leads, or seated/supported.","I can make the 1-2 smooth (no gap between strikes) without the guard dropping.","I paused in my guard for one count after each 1-2 instead of rushing the next."],
  days:[["One, two","The 1-2",["c2-jab","c2-cross","c2-onetwo","c2-onetwo","f2-moving-guard"],"The most famous combination in striking. Slow first; the guard is part of it."],
   ["Two strikes, one rhythm","Easy review",["f2-guard","c2-jab","c2-cross","c2-mobility"]],
   ["Slow, then smooth","1-2 volume",["c2-jab","c2-cross","c2-onetwo","f2-distance","c2-onetwo"],"Build from slow to smooth only when three in a row are clean."],
   ["Smooth hands, strong middle","1-2 & core",["c2-cross","c2-onetwo","f2-four","c2-onetwo","c2-core"]],
   ["The 1-2 on both leads","1-2 self-check",["f2-moving-guard","c2-onetwo","c2-onetwo","f2-choice","c2-selfcheck"],"Same quality on both sides is the target."],
   ["Easy one-two","Easy flow",["f2-shift","c2-jab","c2-onetwo","c2-mobility"]]]},
 {name:"Step and strike",focus:"Strike as you step: the front foot and the jab land together, then step back out. Build blocks begin.",
  goals:["I can step in with a jab so the foot and fist land together, then rebuild my stance.","I can step out rear foot first after a 1-2 without crossing my feet, or use the supported weight shift.","I practised starting a jab from stillness, without a shoulder hitch."],
  days:[["Foot and fist together","Step-and-strike",["f2-forward","c2-onetwo","c2-stepjab","c2-stepjab","f2-stop"],"Chapter 1's footwork meets your hands."],
   ["Steps and hands, easy","Easy review",["f2-moving-guard","c2-jab","c2-onetwo","c2-mobility"]],
   ["In and out","Step-and-strike volume",["c2-onetwo","c2-stepjab","c2-stepjab-build","f2-distance","c2-still"],"Build blocks start today: four rounds of 40 seconds, quality held to the last."],
   ["Still, then snap","Stillness & core",["c2-stepjab","c2-onetwo","c2-still","c2-stepjab-build","c2-core"]],
   ["Enter, strike, leave","Step self-check",["f2-four","c2-stepjab-build","c2-onetwo","c2-stepjab-build","c2-selfcheck"],"Test-style: in, strike, out, on both leads."],
   ["Light feet","Easy flow",["f2-shift","c2-jab","c2-stepjab","c2-mobility"]]]},
 {name:"Double jab and the exit",focus:"The 1-1-2 and the 1-2 with a step-back exit, both leads, then a tempo ladder from slow to crisp.",
  goals:["I can throw a 1-1-2 with both jabs on the same line and the rear hand home, on both leads.","I can step back out after a 1-2 with my guard up and eyes forward, or the supported version.","On the tempo ladder I went back a step whenever form changed instead of forcing speed."],
  days:[["One, one, two","Double jab",["c2-onetwo","c2-double","c2-double","c2-stepjab-build","c2-still"],"The chapter's fullest week begins. More combinations, same calm quality."],
   ["Easy hands","Easy review",["f2-moving-guard","c2-jab","c2-onetwo","c2-mobility"]],
   ["Strike and leave","Exit volume",["c2-onetwo","c2-double","c2-exit","c2-stepjab-build","c2-exit","c2-tempo"],"Longest session of the chapter: still 40 minutes, still easy-to-moderate effort."],
   ["Crisp, not hard","Tempo & core",["c2-double","c2-exit","c2-tempo","c2-still","c2-core"]],
   ["Everything on both leads","Combination self-check",["f2-four","c2-double","c2-exit","c2-tempo","c2-stepjab-build","c2-selfcheck"],"Test-style: all the chapter's combinations, both leads."],
   ["Let it settle","Easy flow",["f2-shift","c2-onetwo","c2-double","c2-mobility"]]]},
 {name:"Trial week · Hands",focus:"A lighter week of review, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Hands trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Review the straights","Light review",["c2-jab","c2-cross","c2-onetwo","c2-mobility"]],
   ["Review the steps","Light review",["f2-moving-guard","c2-onetwo","c2-stepjab","c2-mobility"]],
   ["Crisp and calm","Light review",["c2-onetwo","c2-double","c2-exit","c2-tempo"]],
   ["Stillness before the trial","Light review",["c2-still","c2-onetwo","c2-exit","c2-core"]],
   ["Trial: Hands","Chapter trial",["c2-onetwo","c2-stepjab-build","c2-trial-1","c2-trial-2","c2-exit","c2-mobility"],"The chapter trial: a clean 1-2 with guard return on both leads. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["f2-shift","c2-jab","c2-onetwo","c2-mobility"]]]},
]};
