import {makeDrills,type ChapterSpec} from "./build";
import {COMBINATION_MENU} from "./chapter-05";

// Chapter 8 · Endurance and composure. Technique held over longer work periods inside the
// time cap; breathing as a skill; slowing down when form breaks is the thing being trained.
const menu = `Menu: ${COMBINATION_MENU.join(" · ")}.`;
const STOP = "Stop for dizziness, chest discomfort or unusual breathlessness and seek medical advice. Keep water near and go easier in heat.";

const drills = makeDrills(8,{
 "c8-warm":{name:"Breath and rhythm warm-up",family:"Preparation",timing:"warmup",cue:"Find the breath first. The rhythm follows.",
  steps:["First 30 seconds: clear your space, water within reach, and check the room: if it is warm, open a window or use a fan and plan an easier session. Find your point.","Next 2 minutes: march, gradually a little brisker. If comfortable, breathe in through the nose for 3 steps and out for 4.","Next 90 seconds: arm swings and hip circles, then 60 seconds of light shadow work at half pace, still breathing calmly.","Final minute: feet together, a small bow. Step into stance, raise the guard with one sharp breath out, and hold one breath of stillness. Practice begins."],
  checks:["My breathing rose gently and stayed calm.","I checked the room temperature and have water near."],
  supported:"March holding your support and shadow with feet planted.",
  seated:"Seated marching, arm swings, seated shadow and a seated bow.",
  avoid:STOP,sources:["heat","aaos"]},
 "c8-cool":{name:"Long-exhale cool-down",family:"Finish",timing:"cooldown",cue:"The exhale is the way home.",
  steps:["First 2 minutes: walk slowly, letting each lap be a little slower than the one before.","Next minute: calf, hip-flexor and chest stretches, 15–20 seconds each, mild tension.","Next 90 seconds: breathe in through the nose for 4 and out through the mouth for 6–8. Or cyclic sighs: two gentle inhales through the nose, one long exhale through the mouth.","Final 30 seconds: feet together, a small bow, then drink some water. If your breathing or heart rate hasn't settled within a few minutes, or you feel unwell, seek advice."],
  checks:["My breathing settled to normal before I finished.","I drank water and feel steady."],
  supported:"Walk with a hand near your support; stretch holding it.",
  seated:"Sit and do the breathing and seated stretches; a seated bow.",
  avoid:STOP,sources:["breath","nhs-flex"]},
 "c8-breath":{name:"Breathing skills",family:"Breath",cue:"The exhale is the brake. Learn where it is.",
  steps:["Work: 30 seconds of easy shadow work, 1-2s and steps at a relaxed pace, breathing out on each strike.","Rest: practise one pattern. Extended exhale: in through the nose for 4, out through the mouth for 6–8. Box breath: in 4, hold 4, out 4, hold 4.","Round 1 rest: extended exhale. Round 2 rest: box breath. Round 3 rest: whichever settled you faster.","Notice how quickly your breathing slows in each rest. That is the skill you will use in every long round."],
  checks:["My breath settled during each rest.","I breathed out on every strike instead of holding my breath."],
  supported:"Shadow with feet planted beside your support; sit for the rests.",
  seated:"Seated shadow work and seated breathing.",
  avoid:"Never hold your breath during effort. Skip the holds in box breathing if they make you light-headed.",sources:["breath"]},
 "c8-rhythm":{name:"Easy rhythmic shadow work",family:"Endurance",format:"B",cue:"Steady as rain.",
  steps:["Choose a simple loop: jab, cross, step back, step in. Repeat it at an easy, regular rhythm for the whole round, like a drum pattern.","Breathe out on each strike and in on the steps. Effort: you could talk in short sentences.","Round 2: a different loop (slip-2, step back, 1-2). Round 3: the first loop on the other lead. Round 4: your choice.","Keep the rhythm, not the speed. If you notice yourself speeding up, slow back down on purpose."],
  checks:["My rhythm stayed regular through each round.","Effort stayed easy enough to talk."],
  supported:"Loops with the feet planted and weight shifts for the steps.",
  seated:"Seated loops at an easy rhythm.",
  avoid:STOP,sources:["talk-test"]},
 "c8-steady":{name:"Steady continuous shadow",family:"Endurance",format:"D",cue:"Not fast. Not stopped. Steady.",
  steps:["Two 3-minute rounds of continuous shadow work at an easy-to-moderate pace: keep moving the whole time with strikes, defenses and steps, at a pace you could keep up for much longer.",`${menu} Every combination ends with your guard home; between combinations, small steps or pivots.`,"In the 1-minute rests, walk slowly and breathe out long.","Effort guide: round 1 about 3 out of 10, round 2 about 4. A short sentence is always possible."],
  checks:["I kept moving through the whole round without speeding up.","My breath settled within each rest."],
  supported:"Half-range strikes with weight shifts for the steps; walk with your guard up whenever you need.",
  seated:"Continuous seated shadow work at an easy rhythm.",
  avoid:STOP,sources:["talk-test","heat"]},
 "c8-long":{name:"Long rounds with an effort guide",family:"Endurance",format:"D",cue:"Pace it like a long road.",
  steps:["Two 3-minute rounds from the menu with an effort plan: first minute about 3 out of 10, second minute 4, third minute 4–5, never past 'short sentences'.",menu,"In the rests, walk, breathe out long, and ask: could I speak a short sentence right now? If not, make the next round easier.","The aim is the same quality in minute three as in minute one."],
  checks:["Effort never went past 'short sentences'.","My technique in the last minute matched the first."],
  supported:"Use the hands-only part of the menu and walk whenever you need.",
  seated:"Seated rounds with the same effort plan.",
  avoid:STOP,sources:["talk-test","heat"]},
 "c8-composure":{name:"Composure reset",family:"Composure",format:"B",cue:"Tired is information, not an emergency.",
  steps:["Late in a session, a little tired, run a short reset: a 1-2, then three slow breaths with a long exhale, then a stance check (feet apart, knees soft, guard home, eyes on your point).","Then a defensive answer, slip-2 or cover-1-2, done as precisely as you can.","Four resets per round; rounds alternate leads.","If anything is ragged, slow everything down. Calm and precise beats fast and messy."],
  checks:["I slowed my breathing before the next technique.","Each stance check found and fixed one thing."],
  supported:"Resets with the feet planted beside your support.",
  seated:"Seated resets: strike, breathe, posture check, seated defense.",
  avoid:STOP,sources:["breath"]},
 "c8-quality":{name:"If form breaks, slow down",family:"Composure",format:"B",cue:"Slower is not weaker. Slower is honest.",
  steps:["Each round starts at a crisp tempo on one combination of your choice.","The moment any part of the form slips (guard drops, feet cross, elbow snaps, balance goes), drop one tempo: crisp, then smooth, then slow.","Finish every round at the tempo where form is clean. Rounds alternate leads and combinations.","Noticing the slip and slowing down is the skill being trained."],
  checks:["I noticed when form slipped and slowed down.","I finished each round with clean form."],
  supported:"Half-range combinations with feet planted.",
  seated:"Seated combinations with the same tempo rule.",
  avoid:"Crisp is never maximal. "+STOP,sources:["focus"]},
 "c8-recovery":{name:"Recovery skills",family:"Recovery",cue:"Recovery is training you can't see.",
  steps:["Round 1: slow walking with long exhales.","Round 2: easy mobility: ankle circles, hip circles and shoulder rolls.","Round 3: sit or lie comfortably and do cyclic sighs: two gentle inhales through the nose, one long exhale through the mouth, for the whole round.","In the rests, drink water. In the review, think about tonight's sleep and tomorrow's practice: lighter if you are still tired."],
  checks:["I felt calmer after the block than before it.","I planned an easier day if tiredness carries over."],
  supported:"Walk with your support near; mobility holding it.",
  seated:"The whole block seated.",
  avoid:"Stop any breathing pattern that makes you light-headed.",sources:["breath","nhs-sitting"]},
 "c8-engine":{name:"Low-impact engine",family:"Conditioning",format:"S",cue:"An engine that runs quietly for years.",exercises:["Guard march","Step-back to stance","Shadow 1-2s","Calf raise"],
  steps:["Guard march: march in place with your guard up, knees lifting to a comfortable height, at a steady pace.","Step-back to stance: from feet together, step back into your stance and return, alternating legs, in a steady rhythm. A shallow, controlled step, not a deep lunge.","Shadow 1-2s: continuous relaxed 1-2s at a steady pace, breathing out on each.","Calf raise: steady raises holding your support. Across the block aim for about 4 out of 10 effort: short sentences possible."],
  checks:["I kept a steady pace without rushing.","My breathing stayed at 'short sentences'."],
  supported:"March and step holding your support; 1-2s with feet planted.",
  seated:"Seated marching with the guard, seated 1-2s and seated heel raises.",
  avoid:"No jumping or sprinting. "+STOP,sources:["who","talk-test"]},
 "c8-selfcheck":{name:"Composure self-check",family:"Self-check",cue:"How does your form look when you're tired?",
  steps:["Round 1: a short burst of this week's work at its normal effort.","Round 2: one combination slowly, checking the guard, feet and elbows.","Round 3: a composure reset: 1-2, three long breaths, stance check.","Review minute: does your form change when you're tired? Name the first thing that slips; that is next week's focus."],
  checks:["I can name the first thing that slips when I'm tired.","My breathing settled in the review minute."],
  supported:"Check with feet planted.",seated:"Check seated.",
  avoid:STOP,sources:["breath"]},
 "c8-trial-rounds":{name:"Trial · steady rounds",family:"Chapter trial",format:"D",cue:"Six minutes of the same calm fighter.",
  steps:["Two 3-minute rounds from the menu at easy-to-moderate effort, the same effort plan you trained.",menu,"In the rests, walk and breathe out long.","Mark the checks honestly. 'Not yet' means repeat a week; it never blocks the story."],
  checks:["Rounds completed with form intact.","Effort never past 'short sentences'."],
  supported:"Hands-only menu and walking breaks inside the round.",seated:"Seated rounds.",
  avoid:STOP,sources:["talk-test"]},
 "c8-trial-composure":{name:"Trial · composure finish",family:"Chapter trial",format:"B",cue:"Tired, and still precise.",
  steps:["Straight after the rounds: a composure reset in each round (1-2, three long breaths, stance check, a defensive answer).","Round 2: the same on the other lead.","Rounds 3–4: one combination starting crisp, dropping a tempo the moment form slips.","Review: was your breath settled by the end of each rest?"],
  checks:["My breath settled within each rest.","I slowed down when form slipped."],
  supported:"Feet planted, half range.",seated:"Seated resets.",
  avoid:STOP,sources:["breath"]},
});

export const CHAPTER_8:ChapterSpec = {chapter:8,warm:"c8-warm",cool:"c8-cool",drills,weeks:[
 {name:"Breath and rhythm",focus:"Breathing skills for rests, easy rhythmic shadow work, and the first long-round blocks.",
  goals:["I can use an extended exhale or box breath to settle my breathing in a rest.","I breathed out on every strike instead of holding my breath.","I kept the rhythmic shadow work at an easy, talkable pace."],
  days:[["The brake","Breathing & rhythm",["c8-breath","c8-rhythm","c8-steady","c8-breath"],"Long-round blocks begin. First, learn where the brake is: the exhale."],
   ["Easy review","Easy review",["c8-breath","c7-smooth","c5-set","c7-mobility"]],
   ["Steady as rain","Rhythm & form",["c8-rhythm","c8-steady","c7-form"],"Main volume: steady rounds, then the whole form."],
   ["Rhythm and strength","Rhythm & strength",["c8-rhythm","c8-breath","c7-cue-mixed","c8-engine","c6-strength-1"]],
   ["Check the breath","Composure self-check",["c8-steady","c8-rhythm","c8-selfcheck","c8-breath"],"How quickly does your breath settle?"],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c7-smooth","c6-flow-hips"]]]},
 {name:"Steady and continuous",focus:"Four to six minutes of continuous, easy-to-moderate shadow work without speeding up.",
  goals:["I can keep moving through a 3-minute steady round without speeding up.","My breath settled within each 1-minute rest.","I kept water near and made the session easier when it was warm."],
  days:[["Not fast, not stopped","Steady rounds",["c8-breath","c8-steady","c8-rhythm","c7-cue-menu"],"The chapter's fullest stretch begins, all inside the time cap."],
   ["Easy review","Easy review",["c8-breath","c8-rhythm","c7-smooth","c7-mobility"]],
   ["The long steady","Steady volume",["c8-rhythm","c8-steady","c7-form","c8-breath"],"Steady rounds, then the form, then the brake."],
   ["Engine day","Steady & strength",["c8-steady","c7-cue-mixed","c8-engine","c6-strength-2"]],
   ["Check the steady","Composure self-check",["c8-rhythm","c8-steady","c7-form","c8-selfcheck"],"Does your form hold through the steady rounds?"],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c6-form","c6-flow-upper"]]]},
 {name:"Long rounds",focus:"Three-minute rounds from the menu with an effort guide that never passes 'short sentences'.",
  goals:["I can follow an effort guide through a long round, never past 'short sentences'.","My technique in the third minute matched the first.","I made the next round easier whenever I couldn't speak a short sentence in the rest."],
  days:[["A long road","Long rounds",["c8-rhythm","c8-long","c8-breath","c7-cue-menu"],"Pace the round like a long road: minute three as clean as minute one."],
   ["Easy review","Easy review",["c8-breath","c8-rhythm","c7-smooth","c7-mobility"]],
   ["Long and steady","Long-round volume",["c8-long","c8-steady","c7-form"],"Main volume: long rounds, steady rounds, the form."],
   ["Rounds and strength","Long rounds & strength",["c8-long","c8-rhythm","c8-engine","c6-strength-1"]],
   ["Check minute three","Composure self-check",["c8-rhythm","c8-long","c7-cue-mixed","c8-selfcheck","c8-breath"],"What slips first when you're tired?"],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c7-smooth","c6-flow-hips"]]]},
 {name:"Composure",focus:"The form and cue drills late in a session at easy intensity; the composure reset.",
  goals:["I can perform the form and cue drills late in a session at easy intensity.","I can run a composure reset: 1-2, three breaths, stance check.","I treated tiredness as information and slowed down."],
  days:[["Tired is information","Composure",["c8-rhythm","c8-long","c8-composure","c7-cue-intercept"],"Skills done late, done calm."],
   ["Easy review","Easy review",["c8-breath","c8-composure","c7-smooth","c7-mobility"]],
   ["The form, late","Composure volume",["c8-long","c8-composure","c7-cue-mixed","c7-form"],"The form comes last today, when you're a little tired. Calm and precise."],
   ["Composure and strength","Composure & strength",["c8-steady","c8-composure","c8-engine","c6-strength-2"]],
   ["Check the calm","Composure self-check",["c8-rhythm","c8-long","c7-form","c8-selfcheck"],"The form after long rounds: how does it look?"],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c8-composure","c6-flow-upper"]]]},
 {name:"The fullest week",focus:"The chapter's fullest sessions, still inside the time cap. Quality rule: if form breaks, slow down or stop.",
  goals:["I completed the chapter's fullest week within the time cap.","I noticed when form slipped and dropped a tempo.","I finished each session with clean form rather than more volume."],
  days:[["Slower is honest","Quality rule",["c8-quality","c8-long","c8-composure","c7-cue-menu"],"The fullest week of the chapter, with one rule above all: when form breaks, slow down."],
   ["Easy review","Easy review",["c8-breath","c8-quality","c7-smooth","c7-mobility"]],
   ["The full session","Peak volume",["c8-long","c8-steady","c8-quality","c7-cue-mixed"],"The longest work of the chapter. Walk in every rest."],
   ["Quality and strength","Quality & strength",["c8-long","c8-quality","c8-engine","c6-strength-1"]],
   ["Check the quality","Composure self-check",["c8-long","c7-form","c8-quality","c8-selfcheck"],"Did you slow down when it mattered?"],
   ["Easy flow","Easy flow",["c7-mobility","c8-breath","c7-smooth","c6-flow-hips"]]]},
 {name:"Recovery and trial · Endurance",focus:"An intentionally light week of recovery skills, the chapter trial on Saturday, then easy flow.",
  goals:["I completed the Endurance trial at my level: standing, supported or seated.","I recorded honestly which trial checks I met and which need more practice.","I chose my next step, repeating a week of this chapter or moving on, and both are fine."],
  days:[["Recovery is training","Recovery",["c8-recovery","c8-breath","c7-smooth","c7-mobility"]],
   ["Light rhythm","Recovery",["c8-recovery","c8-rhythm","c6-form","c6-flow-hips"]],
   ["One easy steady","Recovery",["c8-steady","c8-breath","c8-recovery"]],
   ["Calm before the trial","Recovery",["c8-rhythm","c8-recovery","c7-cue-intro","c6-flow-upper"]],
   ["Trial: Endurance","Chapter trial",["c8-rhythm","c8-trial-rounds","c8-trial-composure","c8-recovery","c8-breath"],"The chapter trial: a steady composure session with form intact. Record honestly; it never blocks the story."],
   ["After the trial","Easy flow",["c7-mobility","c8-recovery","c8-breath","c6-flow-hips"]]]},
]};
