import type {RecordEntry} from "./training";
export const WEEKS=[
 {name:"Find your starting point",focus:"Easy supported mobility and a tall natural stance.",goals:["I found comfortable versions of the warm-up, hinge, and calf movement.","I can use a tall stance and breathe normally for 20–30 seconds.","I kept movement easy and respected rest or pain signals."]},
 {name:"Build a steady base",focus:"Gentle weight shifts, relaxed guard, and controlled breathing.",goals:["I can shift weight slowly with chair support as needed.","I can repeat 3 × 30 seconds of tall guard with equal rests, comfortably.","I can tell when my body needs the gentler recovery option."]},
 {name:"Take the first steps",focus:"Small forward and backward steps without crossing your feet.",goals:["I understand which foot moves first when stepping forward and backward.","I can repeat 3 × 30 seconds of small steps with rests and no loss of balance.","I can keep a tall comfortable stance while stepping."]},
 {name:"Make balance repeatable",focus:"Repeat stance and footwork without chasing speed.",goals:["I can restore my stance after each slow step.","I can hold a tall guard for up to 60 seconds with normal breathing, or repeat week 3 if needed.","I keep my shoulders relaxed and knees comfortable throughout practice."]},
 {name:"Return to your guard",focus:"Raise and reset your hands while maintaining posture.",goals:["I can bring relaxed hands to guard and lower them without shoulder strain.","I can reset my guard after a small weight shift.","I use a smaller range if my shoulders are tired from upper day."]},
 {name:"Move with your guard",focus:"Coordinate a small step with a relaxed guard reset.",goals:["I can take a small step, pause, and restore my guard without rushing.","I can repeat 3 × 60 seconds of comfortable footwork with equal rests.","I have checked my practice journal for recurring discomfort or fatigue."]},
 {name:"Connect the basics",focus:"Slow stance-to-step sequences, with generous rests.",goals:["I can connect a guard reset, forward step, and backward step with pauses.","I stay balanced through short sequences on both leads.","I stop a sequence when control deteriorates instead of pushing harder."]},
 {name:"Review, don’t rush",focus:"Revisit your baseline and prepare for an instructor review.",goals:["I recorded my comfortable mobility again without forcing a test.","I can describe which movements improved and which still need support.","I understand that punches, kicks, partner practice, and level advancement need instructor assessment."]},
];
export type WeekCheck={week:number;goals:boolean[]};
export function beginnerProgress(records:RecordEntry[],checks:WeekCheck[],today:string){const completed=records.filter(r=>r.kind==="training");const first=completed.map(r=>r.date).sort()[0];const days=first&&today?Math.max(0,Math.floor((Date.parse(today+"T12:00:00Z")-Date.parse(first+"T12:00:00Z"))/86400000)):0;let week=1;while(week<8&&completed.length>=week*6&&days>=week*7&&checks.some(c=>c.week===week&&c.goals.length===3&&c.goals.every(Boolean)))week++;const complete=week===8&&completed.length>=48&&days>=56&&checks.some(c=>c.week===8&&c.goals.every(Boolean));return {week,days,sessions:completed.length,complete};}
