import type {RecordEntry} from "./training";
// Self-reports describe the preparation actually used, not graded technique.
export const WEEKS=[
 {name:"Find your martial arts base",focus:"Learn stance, guard, balance, and the order of small steps. All practices are 30 minutes including rests.",goals:["I can rebuild my stance and reset my guard 3 times with easy breathing, or explain my supported/seated preparation.","I can name which foot moves first forward, backward, left, and right, and rehearse it at my own level.","I used 30-second practice/rest rounds without forcing repetitions, and chose rest when movement hurt."]},
 {name:"Stop in a steady base",focus:"Keep the same spacing and pause in balance after each movement. Repeat week one whenever useful.",goals:["I can repeat 3 small shifts and stop in the middle, using support or seated preparation as needed.","I can finish a tiny step pair and pause for two counts, or do the supported shift-and-stop version.","I can identify and correct one issue such as feet together, leaning, or tense shoulders."]},
 {name:"Move in four directions",focus:"Practise forward, backward, left, and right with the same lead and a full stop after each pair.",goals:["I can say the first foot for all four directions before moving.","I can complete one slow four-direction cycle without crossing my feet, or rehearse the order seated with taps.","I restore my starting spacing after each pair, or describe the support I still need."]},
 {name:"Keep your guard while moving",focus:"Coordinate relaxed hands with short steps. No longer holds or speed targets.",goals:["I can reset my guard 3 times without shrugging or blocking my view.","I can combine one step pair with an easy guard, or use a supported shift/seated heel tap with a guard reset.","I lower tired arms and repeat separate hand and foot practice if coordination breaks down."]},
 {name:"Control a little distance",focus:"Move out and return without leaning or stretching your stance. Use single steps until repeatable.",goals:["I can take one forward and backward pair while staying upright, or rehearse them with support/seated taps.","I can describe how footwork changes distance and how leaning differs from moving my base.","I can return to my starting space with small steps, or explain which part needs a simpler version."]},
 {name:"Change direction calmly",focus:"Connect a backward step and a side step with a full stop between them. Keep facing ahead.",goals:["I can name the first foot in a back-left-right-forward sequence and its right-side version.","I can rehearse one sequence with a pause between directions, using supported shifts or seated taps when needed.","I keep knees comfortable and return to separate directions when a corner feels rushed."]},
 {name:"Choose and connect",focus:"Choose a direction, move, and settle. Practise recall and control rather than reaction speed.",goals:["I can choose a direction and name the correct first foot before moving.","I can make 2–3 calm choices in a practice round, using standing, supported, or seated rehearsal.","I can check one form point and use it to improve the next round, with full rests between rounds."]},
 {name:"Review your foundations",focus:"Revisit stance, guard, foot order, and coordination. Identify what is repeatable and what needs instruction.",goals:["I reviewed stance, guard, and four-direction movement at my actual level, with the support I need.","I can name one improvement and one specific skill to repeat or ask an instructor to observe.","I understand that self-checks and story rewards do not certify skill; strikes, kicks, contact, and later levels need qualified instruction and assessment."]},
];
export type WeekCheck={week:number;goals:boolean[]};
export function beginnerProgress(records:RecordEntry[],checks:WeekCheck[],today:string){const completed=records.filter(r=>r.kind==="training");const first=completed.map(r=>r.date).sort()[0];const days=first&&today?Math.max(0,Math.floor((Date.parse(today+"T12:00:00Z")-Date.parse(first+"T12:00:00Z"))/86400000)):0;let week=1;while(week<8&&completed.length>=week*6&&days>=week*7&&checks.some(c=>c.week===week&&c.goals.length===3&&c.goals.every(Boolean)))week++;const complete=week===8&&completed.length>=48&&days>=56&&checks.some(c=>c.week===8&&c.goals.every(Boolean));return {week,days,sessions:completed.length,complete};}
