import type {Drill} from "./training";
import {WEEK_ONE_DRILLS} from "./week-one";

// Versioned IDs: an already-started session retains its original lesson and dose.
export const MAX_PRACTICE_MINUTES = 45;
export type PracticeDay = {load:string;title:string;focus:string;minutes:number;reason:string;blocks:readonly (readonly [string,number])[]};
const base = (id:string,changes:Partial<Drill>):Drill => ({...WEEK_ONE_DRILLS[`w1-${id}`],...changes});
const lesson = (name:string,category:string,cue:string,steps:string[],checkpoints:string[],easier:string,avoid:string):Drill => ({name,category,cue,steps,checkpoints,easier,avoid,timedRounds:true,dose:"30 sec practice / 30 sec rest · 3 rounds in 5 min"});

export const FOUNDATION_DRILLS:Record<string,Drill> = {
 "f2-warm":base("warm",{
  category:"Preparation",timedRounds:false,timing:"warmup",cue:"Start easy; gradually feel warmer without getting out of breath.",dose:"5 min gradual warm-up · rests welcome",
  steps:["Use the first 30 seconds to clear a non-slip space for one small step in each direction. Put a sturdy, non-wheeled chair against a wall if you need support. Wear secure footwear; avoid slippery socks.","For the next 2 minutes, walk gently in place or around your clear space. Start slowly and gradually make the movement a little more comfortable and regular.","For 1 minute, continue easy steps while opening and closing your hands and making small shoulder circles. Keep your shoulders loose.","For the final 90 seconds, alternate easy walking with small weight shifts and gentle ankle movement. Speak a full sentence: if that is difficult, slow down or rest. Do not skip preparation to fit in more drills."],
  easier:"Hold the chair and march gently, or sit with feet supported and alternate comfortable heel lifts and easy arm movements. Take rests whenever needed. If still cold or stiff, keep the next block as easy preparation instead of adding harder movement."
 }),
 "f2-stance":base("stance",{category:"Foundation · Stance",steps:["Stand with feet about hip-width apart. The lead foot is the one in front; the rear foot is behind. Choose either comfortable lead and keep it for the whole round.","Move the rear foot a small step back, about half your foot length to start. Keep each foot on its own track, with space between them. Let toes point comfortably forward; do not force an angle.","Soften your knees so they follow the direction of your toes. Keep your head over your hips, eyes ahead, and weight comfortable across both feet.","Take two easy breaths, relax back to hip-width feet, and rebuild. Repeat slowly, about 3 times per practice round. If you wobble, shorten the stance and use chair support. Change lead only between rounds."],checkpoints:["I can rebuild the same spacing 3 times without feet crossing.","I can breathe and stop comfortably with soft knees, using support if needed."]}),
 "f2-guard":base("guard",{category:"Foundation · Guard",steps:[...WEEK_ONE_DRILLS["w1-guard"].steps.slice(0,3),"Repeat about 3 slow raise-and-lower cycles in each 30-second practice round; rest for 30 seconds with hands down. Keep fingers relaxed and wrists straight. Guard here means a repeatable hand position, not proven protection from a strike."],checkpoints:["Hands return to the same place 3 times without shrugging.","I can see ahead and breathe without holding tired arms up."]}),
 "f2-shift":base("shift",{category:"Foundation · Balance",steps:[...WEEK_ONE_DRILLS["w1-shift"].steps.slice(0,3),"Repeat about 3 small forward-and-back cycles per practice round. Pause in the middle after each. If your torso tips or a heel lifts, reduce the shift and add chair support; rest with both feet settled." ]}),
 "f2-forward":base("forward",{category:"Foundation · Forward and backward",steps:[...WEEK_ONE_DRILLS["w1-forward"].steps.slice(0,3),"One pair means the first foot moves, then the other follows. Do 2–3 forward-and-back cycles per round, with a two-count pause after each pair. Keep the same lead; lower hands if needed. If you lose spacing, stop and rebuild before repeating." ]}),
 "f2-side":base("side",{category:"Foundation · Left and right",steps:[...WEEK_ONE_DRILLS["w1-side"].steps.slice(0,3),"One pair means both feet have moved once. Do 2–3 left-and-right cycles per round, pausing for two counts after each pair. If the feet touch or cross, stop and restart with a smaller step or use the supported alternative." ]}),
 "f2-flow":base("flow",{category:"Foundation · Combine",steps:[...WEEK_ONE_DRILLS["w1-flow"].steps.slice(0,3),"One cycle is forward, back, left, then right, each followed by a full stop. Do only 1–2 cycles per 30-second practice round, then lower hands for the rest. If one direction is unsteady, rehearse only that direction with support." ]}),
 "f2-stop":lesson("Step, stop, check","Week 2 · Control","Finish the step before starting another.",[
  "Build your short stance. Choose forward or backward for this round. Keep a chair within reach, not in your walking path.",
  "Move the foot nearest that direction a few centimetres, then the other foot the same distance. Stop completely and count one, two while breathing.",
  "Check that your feet are still apart and knees soft. Return with the foot nearest the return direction first. Stop again.",
  "Repeat 2–3 times in the practice round. During the rest, notice one issue: feet together, leaning, or rushing. Make only that correction next round; use a smaller step if you cannot stop steadily."
 ],["I can pause for two counts without an extra balancing step.","The following foot restores my original spacing."],"Hold a stable chair and do tiny planted weight shifts followed by a stop. Seated: move one heel a little forward, return, and pause with both feet supported.","Never reach for a support that is moving or too far away. No sudden stops from fast movement."),
 "f2-four":lesson("Choose one of four directions","Week 3 · Footwork","Say the direction. Move the nearest foot first.",[
  "Start in your short stance, facing one fixed point ahead. Keep the same lead throughout the round. Imagine two parallel tracks under your feet.",
  "Say forward: front foot moves first, rear foot follows the same distance. Stop; then say back: rear foot first, front foot follows. Stop again.",
  "Say left: left foot first, right follows. Say right: right foot first, left follows. Keep facing ahead and stop after each pair; do not turn on a planted knee.",
  "Repeat the four directions once or twice per round. Stay in your clear space. If the order becomes confusing, repeat one direction and its return rather than adding speed."
 ],["I can name the first foot before moving in all four directions.","Each stop leaves my feet apart with the original lead in front."],"Use chair-supported forward/back and side weight shifts with feet planted. Seated: name the first foot and rehearse a small tap, returning it before the next direction.","Do not look down while moving, cross feet, hop, or add rapid pivots."),
 "f2-moving-guard":lesson("Keep your guard as you step","Week 4 · Coordination","Feet move; hands stay comfortably near home.",[
  "Start in your short stance. Bring relaxed hands beside your cheeks, elbows near ribs and eyes clear. Keep shoulders down.",
  "Take one tiny forward pair: front foot then rear foot. Try to keep hands near their starting place throughout. Stop for two counts and breathe.",
  "Return with rear foot then front foot, stop, and lower hands. If controlled, use left-then-right pairs in the next round, keeping your torso facing ahead.",
  "Repeat 2–3 cycles per round. If hands drift or shoulders tense, stop, lower hands, and reset. Rehearse feet and guard separately until they feel comfortable together."
 ],["I can keep my view clear and shoulders loose while stepping.","I can stop in balance before relaxing my hands."],"Keep one hand on a stable chair and practise the other hand's position during a planted shift. Seated: maintain an easy chest-height guard during one heel tap, then lower hands.","Do not force a continuous 30-second guard hold. Lower tired arms; this is coordination, not defense against contact."),
 "f2-distance":lesson("Take space, return to your base","Week 5 · Distance","Small steps change distance without a long reach.",[
  "Face an imaginary point well beyond arm's reach in your clear space. Begin in your short stance and comfortable guard; no person or object is a target to hit.",
  "Take one tiny forward pair, front foot then rear foot. Pause for two counts, staying upright instead of leaning toward the point.",
  "Take one backward pair, rear foot then front foot. Pause. If balance is steady, try two separate tiny backward pairs and two forward pairs to return; pause after every pair.",
  "Repeat slowly for the practice round; hands may lower between cycles. Use the same small step size and stay within the cleared area. If you lean, shorten the step and repeat just one pair out and back."
 ],["My head stays over my base rather than reaching toward the imaginary point.","I can return using the same short steps without crossing feet."],"Use chair-supported forward-and-back weight shifts while keeping feet planted. Seated: rehearse the foot order with small heel taps and an upright torso.","Do not step toward furniture, lean back to evade an imagined hit, or practise with an attacking partner."),
 "f2-corner":lesson("Back, then sideways","Week 6 · Change direction","Stop between directions. Keep facing ahead.",[
  "Check you have clear space behind and beside you before starting. Set your short stance and comfortable guard, facing one point ahead.",
  "Take one tiny backward pair: rear foot then front foot. Stop, breathe, and check your feet are apart.",
  "Take one left pair: left foot then right. Stop. Return right foot then left, stop, then forward foot then rear to your starting place.",
  "In the next round use the right side instead: back, right, left, forward. Do 1–2 cycles per round. If you rush a corner, practise the two directions separately with full stops."
 ],["I stop before changing direction and keep the same lead.","I can explain which foot moves first on either side."],"Hold a stable chair for a tiny backward weight shift, return to centre, then a side shift. Seated: name each direction and do one small heel or side tap at a time.","No spinning, twisting on a planted knee, crossing feet, or claims that this solo pattern tests escape from an attack."),
 "f2-choice":lesson("Choose, move, settle","Week 7 · Recall","Think first; move only when your space is clear.",[
  "Set your short stance. Choose one of forward, back, left, or right and say it before moving. Choose freely; this is not a reaction-speed challenge.",
  "Move the nearest foot first, then the other to restore spacing. Keep an easy guard if comfortable; stop and count one, two.",
  "Return to your starting space using the opposite direction, then choose a different direction. Keep facing ahead and retain the same lead.",
  "Do 2–3 choices per round. In the rest, check one thing: foot order, spacing, or relaxed hands. If you hesitate about foot order, return to the fixed forward/back/left/right sequence."
 ],["I can choose the correct first foot without rushing.","I reset in balance before choosing again."],"Use a supported planted weight shift in your chosen direction and return to centre. Seated: say the first foot, tap it gently, then settle both feet.","Do not add random alarms, blindfolds, speed targets, partner attacks, or obstacles."),
 "f2-review":lesson("Your foundation self-check","Week 8 · Review","Find what is repeatable and what needs help.",[
  "In round 1, rebuild your short stance 3 times. Then raise and lower your guard 3 times, or do fewer repetitions without rushing. Notice breathing, spacing, and shoulder comfort.",
  "In round 2, take one forward-and-back cycle and one left-and-right cycle with two-count stops. Keep the correct first foot and restore your spacing. Use your usual support or seated preparation.",
  "In round 3, try one back-then-side cycle if comfortable, or repeat the single direction that needs practice. Choose precision over extra repetitions.",
  "In the final review minute, name one repeatable skill and one thing to repeat or ask an instructor to check. Compare control with week one, not speed or depth. This self-check records practice; it does not certify fighting ability."
 ],["I can describe the foot order and the support I actually used.","I can identify one specific correction instead of simply logging time."],"Use supported shifts or seated posture, guard resets, and foot-order rehearsal for all three rounds. Describe those skills honestly; seated rehearsal is not a standing-balance test.","No maximum holds, forced mobility tests, strikes, kicks, or contact. An instructor needs to observe martial arts technique before broader progression."),
 "f2-cool":base("cool",{
  category:"Finish",timedRounds:false,timing:"cooldown",dose:"5 min gradual cool-down and review",
  steps:["For the first 2 minutes, lower your hands and walk very slowly, or sit and gently move your ankles. Let movement gradually become smaller.","For the next 2 minutes, relax your shoulders and hands. If comfortable, do small ankle movements or a gentle calf stretch with wall support, 15–20 seconds each side. Skip stretches you do not know or that cause discomfort.","Use the final minute to rest and let breathing settle. Name one thing that felt controlled and one thing to repeat next time; notes are optional.","Finish here. Do not add extra rounds to make up missed practice. If fatigue carries into tomorrow, choose the gentle option or rest." ]
 })
};

const rest:PracticeDay = {load:"Full rest",title:"Rest is your mission",focus:"Full rest",minutes:0,reason:"Wednesday has no practice or required check-in. Missed days never need making up.",blocks:[]};
function day(title:string,focus:string,skills:string[],reason:string):PracticeDay {
 const blocks:PracticeDay["blocks"] = [["f2-warm",5],...skills.map(id=>[`f2-${id}`,5] as const),["f2-cool",5]];
 return {title,focus,load:focus,reason,blocks,minutes:blocks.reduce((sum,[,min])=>sum+min,0)};
}
const learn = "Go slowly. Each technique block includes a minute to read, three 30-second practice / 30-second rest rounds, and a minute to review.";
const easy = "Easy review day: use the supported or seated preparation if tired. Repeat familiar movement; no extra rounds or make-up work.";

// Four to six short skill blocks, plus five minutes each to warm up and finish.
// Keep the normal plan below the ceiling so transitions need not be rushed.
export const FOUNDATION_SCHEDULES:readonly (readonly PracticeDay[])[] = [
 [day("Find your base","Stance & guard",["stance","stance","guard","guard"],learn),day("Keep your balance","Small weight shifts",["stance","shift","shift","guard"],learn),rest,day("Take your first steps","Forward & backward",["stance","guard","forward","forward"],learn),day("Make room to move","Left & right",["stance","shift","side","side"],learn),day("Connect one movement","Move & reset",["forward","side","guard","flow"],learn),day("Repeat the first skills","Easy review",["stance","guard","shift","flow"],easy)],
 [day("Rebuild the same base","Repeatable stance",["stance","guard","shift","stop"],learn),day("Find the middle","Easy balance review",["stance","shift","guard","stop"],easy),rest,day("Finish each step","Stop in balance",["forward","stop","side","stop"],learn),day("Keep your spacing","Short side steps",["side","stop","guard","flow"],learn),day("Make control repeatable","Move & settle",["forward","side","stop","flow"],learn),day("Review without rushing","Easy review",["stance","guard","stop","flow"],easy)],
 [day("Name the first foot","Four directions",["forward","side","four","stop"],learn),day("Keep a comfortable base","Easy familiar practice",["stance","shift","guard","four"],easy),rest,day("Move in four directions","Direction & spacing",["forward","side","four","stop","four"],learn),day("Check each return","Control on return",["side","four","stop","flow"],learn),day("Recall the foot order","Four-direction review",["stance","four","stop","guard","flow"],learn),day("Repeat a clear pattern","Easy review",["shift","guard","four","stop"],easy)],
 [day("Hands stay near home","Guard while moving",["guard","forward","moving-guard","stop"],learn),day("Release shoulder tension","Easy coordination",["stance","shift","guard","moving-guard"],easy),rest,day("Move with a loose guard","Hands & feet together",["guard","four","moving-guard","stop","moving-guard"],learn),day("Keep your view clear","Guard & side steps",["side","guard","moving-guard","flow"],learn),day("Connect without tension","Coordinated review",["four","moving-guard","stop","guard","flow"],learn),day("Keep it comfortable","Easy review",["stance","guard","shift","moving-guard"],easy)],
 [day("Explore a little distance","Move out & return",["forward","stop","distance","moving-guard"],learn),day("Repeat the short step","Easy distance review",["shift","guard","forward","distance"],easy),rest,day("Stay over your base","Distance & posture",["forward","stop","distance","moving-guard","side","distance"],learn),day("Return without leaning","Balanced returns",["distance","side","stop","moving-guard"],learn),day("Keep your steps small","Distance & direction",["four","distance","moving-guard","stop","flow"],learn),day("Choose comfortable range","Easy review",["stance","shift","guard","distance"],easy)],
 [day("One direction at a time","Back then sideways",["four","stop","corner","guard"],learn),day("Keep each part familiar","Easy direction review",["shift","side","guard","corner"],easy),rest,day("Make a calm corner","Change direction",["forward","side","corner","stop","moving-guard","corner"],learn),day("Try the other side","Left & right sequences",["side","corner","stop","distance"],learn),day("Connect with full stops","Direction & guard",["four","corner","moving-guard","stop","flow"],learn),day("Review the separate parts","Easy review",["stance","guard","four","corner"],easy)],
 [day("Choose your next step","Recall & control",["four","stop","choice","moving-guard"],learn),day("Think before moving","Easy recall",["shift","guard","four","choice"],easy),rest,day("Choose without rushing","Independent footwork",["four","choice","moving-guard","stop","corner","choice"],learn),day("Notice one correction","Specific form feedback",["choice","distance","stop","guard"],learn),day("Put the basics together","Controlled combinations",["four","corner","choice","moving-guard","flow"],learn),day("Return to easy movement","Easy review",["stance","shift","guard","choice"],easy)],
 [day("Revisit your base","Stance & guard review",["stance","guard","shift","review"],learn),day("Revisit the foot order","Easy footwork review",["forward","side","stop","review"],easy),rest,day("Check hands and feet","Coordination review",["four","moving-guard","distance","review"],learn),day("Choose a clear direction","Combination review",["corner","choice","stop","review"],learn),day("Describe what you learned","Foundation self-check",["stance","moving-guard","choice","review"],learn),day("Plan your next practice","Easy review & next steps",["shift","guard","flow","review"],"Keep it gentle. Identify one skill to repeat and one question for a qualified instructor. Time completed never awards a higher martial arts level.")]
];

export function foundationSchedule(week:number){return FOUNDATION_SCHEDULES[Math.max(0,Math.min(7,Math.floor(week)-1))]??FOUNDATION_SCHEDULES[0];}
export function foundationLibrary(week:number){
 const ids = new Set(FOUNDATION_SCHEDULES.slice(0,Math.max(1,Math.min(8,week))).flatMap(days=>days.flatMap(d=>d.blocks.map(([id])=>id))));
 return Object.fromEntries([...ids].map(id=>[id,FOUNDATION_DRILLS[id]]));
}
