import {WEEK_ONE_DRILLS,WEEK_ONE_SCHEDULE} from "./week-one";
export type Drill = {name:string;category:string;cue:string;steps:string[];easier:string;avoid:string;dose:string;visual?:string;checkpoints?:string[]};
export const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
export const SCHEDULE = [
 {load:"Stance",title:"Find your footing",focus:"Stance & mobility",minutes:30,reason:"Keep movement easy. Build a comfortable base before increasing speed.",blocks:[["warm",5],["ankle",6],["stance",7],["step",7],["cool",5]]},
 {load:"Control",title:"Move a little better",focus:"Mobility & control",minutes:30,reason:"Use a comfortable range and stable support to build control.",blocks:[["warm",5],["ankle",7],["hinge",6],["stance",5],["cool",7]]},
 {load:"Full rest",title:"Rest is your mission",focus:"Recovery",minutes:0,reason:"No practice or check-in is required. A full day off is part of discipline.",blocks:[]},
 {load:"Footwork",title:"Build the basics",focus:"Guard & footwork",minutes:45,reason:"Practice at an easy talking pace. Short steps; no jumps or hard pivots.",blocks:[["warm",5],["ankle",8],["stance",10],["step",12],["cool",10]]},
 {load:"Technique",title:"Control before power",focus:"Balance & technique",minutes:40,reason:"Explore an easy guard and balanced movement without chasing speed.",blocks:[["warm",5],["hinge",8],["stance",10],["step",10],["cool",7]]},
 {load:"Control",title:"Move a little better",focus:"Mobility & control",minutes:30,reason:"Use a comfortable range and stable support to build control.",blocks:[["warm",5],["ankle",7],["hinge",6],["stance",5],["cool",7]]},
 {load:"Review",title:"Keep it gentle",focus:"Easy recovery",minutes:30,reason:"Review comfortable movement with seated options and generous rests.",blocks:[["warm",5],["hinge",8],["ankle",7],["cool",10]]},
] as const;
export const DRILLS: Record<string,Drill> = {
 warm:{name:"Easy movement warm-up",category:"Warm-up",cue:"Start small. Let your body catch up.",steps:["Clear a non-slip space and keep a stable chair nearby.","Walk in place gently for 1–2 minutes. No bouncing or jumping.","Make small shoulder circles, open and close your hands, then add slow comfortable weight shifts.","Repeat gently for the block. Rest whenever needed; you should be able to talk easily."],easier:"Sit upright and gently move your arms and ankles if standing is tiring.",avoid:"Stop if you feel dizzy or experience sharp pain.",dose:"Easy talking pace"},
 ankle:{name:"Supported ankle mobility",category:"Mobility",cue:"A smaller range, done well, is progress.",steps:["Face a wall, hands resting on it. Put one foot a short distance behind you.","Keep the back heel grounded and toes pointing forward. Gently lean until you feel a mild calf stretch.","Hold 15–20 seconds. Release, switch sides, and repeat 2–3 times.","For the remaining time, make slow seated ankle circles with short rests."],easier:"Move your back foot closer to the wall to reduce the stretch.",avoid:"Never bounce, force the heel down, or push into ankle or knee pain.",dose:"2–3 easy holds per side"},
 hinge:{name:"Chair-supported hip hinge",category:"Mobility",cue:"You do not need to touch your toes.",steps:["Stand hip-width apart, facing a stable chair with both hands on its back.","Soften your knees. Send your hips backward while keeping your back comfortably long.","Stop at a mild stretch and return slowly. Start with 5 repetitions, then rest 30 seconds.","Repeat only while comfortable. This is gentle movement, not a strength workout."],easier:"Stay more upright and use a much smaller range. No floor reach or deep squat required.",avoid:"Do not round down to chase your toes or lock your knees.",dose:"5 slow repetitions, then rest"},
 stance:{name:"Natural stance & guard",category:"Taijutsu basics",cue:"Tall, relaxed, and balanced.",steps:["Stand hip-width apart. Slide one foot a small step back, keeping a comfortably upright stance.","Keep knees softly bent, not in a deep squat. Rest fingertips on a chair if needed.","Bring relaxed hands near cheek height, elbows easy, chin neutral. Breathe for 20–30 seconds.","Lower your hands, rest 20–30 seconds, then repeat with the other foot forward."],easier:"Use a narrower stance, stay taller, and lower your hands if shoulders are tired.",avoid:"Avoid low horse stances, holding your breath, or forcing knee angles.",dose:"20–30 sec practice / equal rest"},
 step:{name:"Step, settle, reset",category:"Footwork",cue:"Quiet feet. Small steps. Stay in control.",steps:["Begin in a tall natural stance. Imagine two parallel tracks under your feet.","Take a small step forward with your front foot, then bring the back foot along to restore your stance.","Return with the back foot first. Keep feet apart and avoid crossing them.","Practice slowly for 30 seconds, then rest 30 seconds. Alternate the leading foot."],easier:"Use a chair for balance and practice weight shifts without taking a step.",avoid:"No hopping, fast pivots, sliding on socks, or dropping into a low stance.",dose:"30 sec practice / 30 sec rest"},
 cool:{name:"Easy stretch & reset",category:"Cool-down",cue:"Finish feeling better than you started.",steps:["Walk slowly or sit comfortably for a minute and let breathing settle.","With hands against a wall, gently stretch one calf for 15–20 seconds; switch sides.","Sit tall and slowly turn your head left and right within a comfortable range. Do not pull on your neck.","Finish with slow comfortable breathing. Rest or repeat gently for the remaining time."],easier:"Stay seated, use small ankle movements, and focus on easy breathing.",avoid:"Stretch only to mild tension; stop with sharp pain, tingling, or numbness.",dose:"Gentle holds; no bouncing"},
};
export type RecordEntry = {date:string;kind:"training"|"rest"|"partial";minutes:number;day:number;readiness:string;note:string};
export type Assessment = {squat:string;reach:string;comfort:boolean};
Object.assign(DRILLS,{
 shift:{name:"Supported weight shifts",category:"Weeks 1–2 · Balance",cue:"Find your balance before moving your feet.",steps:["Stand upright with feet about hip-width apart and fingertips on a stable chair.","Slowly shift a little weight from one foot to the other, keeping both feet on the floor.","Keep knees soft and make the shift small enough that you remain comfortable and balanced.","Practice 20–30 seconds, then rest for the same time. Repeat gently for the block."],easier:"Sit tall and gently shift your upper body left and right without reaching far.",avoid:"No deep bends, one-leg holds, or pushing through knee pain.",dose:"20–30 sec movement / equal rest"},
 guard:{name:"Relaxed guard reset",category:"Weeks 5–6 · Coordination",cue:"Return to a comfortable, repeatable position.",steps:["Stand in your tall natural stance with relaxed shoulders and soft knees.","Raise relaxed hands toward cheek height, pause for two easy breaths, then lower them.","Add a small comfortable weight shift before returning to the same guard position. There is no punch in this drill.","Practice 30 seconds, rest 30–60 seconds, and repeat only while your shoulders feel comfortable."],easier:"Keep hands at chest height or practice seated if your shoulders feel tired.",avoid:"Do not clench your shoulders, hold your breath, or force tired arms to stay up.",dose:"30 sec reset practice / equal rest"},
 sequence:{name:"Guard, step, return",category:"Weeks 7–8 · Movement",cue:"A calm sequence beats a rushed one.",steps:["Begin in a tall natural stance and relaxed guard. Choose the lead that feels comfortable.","Take one small step forward, restore your stance, and pause to check balance.","Step back with the rear foot first, restore your stance, then relax your hands.","Repeat slowly for 30–60 seconds, followed by an equal rest. Switch lead when comfortable."],easier:"Use a chair and keep a full pause between each part, or return to supported weight shifts.",avoid:"No kicks, punches, hopping, rapid pivots, or crossing your feet. Keep the sequence controlled.",dose:"30–60 sec sequence / equal rest"}
});
export const DEFAULT_ASSESSMENT:Assessment = {squat:"shallow",reach:"shins",comfort:false};
Object.assign(DRILLS,WEEK_ONE_DRILLS);
export function scheduleForWeek(week:number){return week===1?WEEK_ONE_SCHEDULE:SCHEDULE;}
export function dateKey(date=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Indianapolis",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);}
export function dayIndex(date=new Date()){return DAYS.indexOf(new Intl.DateTimeFormat("en-US",{timeZone:"America/Indianapolis",weekday:"long"}).format(date));}
export function weekDates(key:string){const d=new Date(key+"T12:00:00Z");d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return DAYS.map((_,i)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+i);return x.toISOString().slice(0,10);});}
export function makePlan(day:number,readiness:string,week=1){
 const p=scheduleForWeek(week)[day];const light=readiness==="tired";
 let blocks:{id:string;seconds:number}[]=readiness==="pain"?[]:p.blocks.map(([id,min])=>({id,seconds:min*60}));
 if(week!==1){
  if(day===0||day===3||day===4)blocks=blocks.map(b=>({...b,id:b.id==="step"&&week<=2?"shift":b.id==="step"&&week>=7?"sequence":b.id==="stance"&&week>=5?"guard":b.id}));
  if(light)blocks=blocks.map(b=>({...b,id:b.id==="step"||b.id==="sequence"?"shift":b.id==="guard"?"stance":b.id}));
 }
 return {...p,blocks,minutes:Math.ceil(blocks.reduce((n,b)=>n+b.seconds,0)/60)};
}
