import {lines,reply,type StoryScene} from "./types";
const quests:[string,string,string,number,string,string,string][]=[
 ["riku","The repair with his name","courtyard",8,"Riku has been asked to hide the repair board because it makes the hall look unfinished. He asks whether the completed work should become invisible the moment people can use it.\n\nriku|I want them to see the care, not applaud every nail. If the hall can name a fighter's demonstration, it can name the person who checked the floor.\n\nYou help him arrange a clear record of completed and pending work. The guild mark is small but readable. A visitor asks him about another doorway. Riku writes the address down. His craft has led to a new job, not simply an increase in somebody else's reputation.","What belongs on the repair board?","Name the craft and the remaining work clearly."],
 ["mika","A visit she can finish","hall",14,"Mika is trying to leave for village work. People keep adding one last question. She answers two, then asks you to keep the doorway clear while she packs.\n\nmika|An appointment with an ending is not evidence that I care less. It means the next village can believe the time I gave them.\n\nYou point late arrivals to the next available time without inventing medical answers. Daichi helps carry the bag she actually wants carried. Mika leaves on time and sends a message later confirming the other appointment happened. The useful thing you did was make an ending possible.","What should the last-arrival sign say?","Show the next appointment and the proper urgent-care contact."],
 ["haru","A question without comparison","courtyard",20,"Haru asks whether Ren enjoys living here. He realizes the question could sound like an evaluation and starts again.\n\nharu|I want to know what he likes. I have spent years asking what he achieved. Those questions don't always reach the same part of someone.\n\nYou suggest he ask Ren directly and name that distinction. Haru practices one plain sentence, then leaves you out of their private conversation. Later Ren says they talked about bread and the river, not which school was better. He seems pleased by the absence of a contest.","How can you help without speaking for Ren?","Encourage Haru to ask Ren directly, and let them talk privately."],
 ["emi","The column marked mine","hall",26,"Emi has accepted a clerkship interview and booked another hall visit. She worries both choices will look less serious beside each other.\n\nemi|I want security. I also want one part of the week that doesn't have to justify itself as a career. I don't know why I keep treating that as a contradiction.\n\nShe asks you to help choose a notebook divider. A small problem, deliberately small enough to solve. The two sections remain in one book. She writes her own dates and goes home without anyone claiming her as a recruit.","What can this visit offer Emi?","Company while she makes her own two-part plan."],
 ["toma","A route appropriate for fourteen","town",32,"Toma wants to carry a message past his usual round. Akari has said the weather makes that route an adult task. He asks you to help persuade her.\n\nYou ask which part he wants: the dangerous route, or a job someone actually depends on. He is irritated by the question, then says the second.\n\ntoma|I still want a better job than being told to wait.\n\nSora gives him the local correction notices and shows him exactly where to deliver them. He checks the addresses, completes the safe round, and returns the receipts. His contribution is real without being made hazardous to feel important.","How should the hall recognize his work?","Thank him for the completed safe route, and name why it mattered."],
 ["natsume","The note after the inspection","hall",38,"Natsume has sent a corrected inspection note. She noticed an unclear clause in her own wording. Akari looks surprised that her aunt volunteered the correction.\n\nnatsume|A standard loses credibility when the person writing it considers herself exempt from revision.\n\nShe asks whether beginners understand who may teach what. You show the scope in the library and the distinction between a practice record and assessed skill. She suggests one clearer sentence. The new note remains in the file beside the old one, with the change dated. Her authority has become more accountable, not less serious.","What should the file preserve?","Keep both dated notes and the reason for the correction."],
];
export const QUESTS:StoryScene[]=quests.map(([member,title,location,gate,script,prompt,label])=>({id:`c1-quest-${member}`,member,title,location,episode:Math.ceil(gate/6),beat:1,practiceGate:gate,kind:"quest",lines:lines(script),choice:{flag:`quest:${member}`,prompt,options:[{id:"help",label,reply:reply(member,"Thank you. That's a useful kind of help. I can take the next part from here.","soft")},{id:"listen",label:"Listen and leave the final arrangement to them.",reply:reply(member,"Thanks for hearing me. I'll make the arrangement myself. It helps to say the actual problem aloud.","neutral")}]} }));
